// Capital Chronicle ContentOps V5 â€” local fixture view-model.
// LOCAL FIXTURE DATA ONLY. No runtime network, no credentials, no platform API.
// All ids/hashes are synthetic placeholders for UI demonstration.

import type { ContentOpsViewModel, JimDailyContentRunPacket, JimVariantPreviewBundle } from './types';
import jimDailyContentRun from '../../../fixtures/v6/jim_daily_content_run_packet_sample_v6.json';
import jimVariantPreviewBundle from '../../../fixtures/v6/jim_content_intent_to_variant_preview_bundle_sample_v6.json';
import {
  buildCockpitManualRecords,
  buildCockpitPreviews,
  buildCockpitSystemState,
  cockpitViewModel,
} from './data/cockpitReadModelAdapter';

export const viewModel: ContentOpsViewModel = {
  system_state: buildCockpitSystemState({
    product_mode: 'LOCAL_PRE_ALPHA',
    modes: [
      { code: 'LOCAL_PRE_ALPHA', active: true },
      { code: 'REVIEW_ONLY', active: true },
      { code: 'NOT_PUBLIC_POSTABLE', active: true },
      { code: 'FUTURE_LIVE_DISABLED', active: true },
      { code: 'MANUAL_APPROVAL_REQUIRED', active: true },
      { code: 'NO_FINANCIAL_ADVICE', active: true },
      { code: 'NO_SIGNAL_LANGUAGE', active: true },
      { code: 'NO_PLATFORM_API', active: true },
      { code: 'NO_PROVIDER_API', active: true },
      { code: 'NO_CREDENTIAL_READ', active: true },
      { code: 'NO_SCHEDULER', active: true },
      { code: 'NO_SCRAPING', active: true },
    ],
    verdict: 'SAFE â€” LOCAL REVIEW ONLY',
    verdict_status: 'verified',
    baseline_ref: 'baseline@342fc91',
    build_provenance: 'local-fixture Â· no-network Â· build-time-only',
    next_allowed_action: 'Review grounded news draft GN-0042 in Writer Studio',
    blockers: [
      {
        id: 'BLK-001',
        label: 'Internal alpha artifact intake not available',
        detail: 'Lane C artifact-backed content blocked until approved artifact spec + export gate exist.',
        severity: 'blocked',
      },
      {
        id: 'BLK-002',
        label: 'Platform live dispatch disabled',
        detail: 'No platform/provider API. All dispatch gates future-gated.',
        severity: 'blocked',
      },
      {
        id: 'BLK-003',
        label: 'LLM provider gate not opened',
        detail: 'AI Writer is UI-only. No provider calls until an explicit approved gate task.',
        severity: 'review',
      },
    ],
    validation_passes: [
      { id: 'VP-1', label: 'No runtime network', status: 'verified', detail: 'Static scan: no fetch/XHR/WebSocket.' },
      { id: 'VP-2', label: 'No credential/env read', status: 'verified', detail: 'No process.env / .env access in app.' },
      { id: 'VP-3', label: 'Build-time deps only', status: 'verified', detail: 'Bundled fonts + icons, no CDN.' },
      { id: 'VP-4', label: 'No-signal language guard', status: 'review', detail: 'Editorial guardrails enforced in Writer Studio.' },
    ],
    pipeline_health: [
      { label: 'Fixtures', value: 'loaded', status: 'verified' },
      { label: 'Lineage', value: 'verified', status: 'verified' },
      { label: 'Dispatch', value: 'gated', status: 'neutral' },
      { label: 'Providers', value: 'disabled', status: 'neutral' },
    ],
    queue_summary: [
      { label: 'Awaiting review', count: 3, status: 'review' },
      { label: 'Approved (manual)', count: 1, status: 'verified' },
      { label: 'Blocked', count: 2, status: 'blocked' },
    ],
  }),
  cockpit: cockpitViewModel,
  jim_daily_content_run: jimDailyContentRun as JimDailyContentRunPacket,
  jim_variant_preview_bundle: jimVariantPreviewBundle as JimVariantPreviewBundle,
  content_items: [
    {
      id: 'PA-0017',
      title: 'Why "no forecast" can be the correct output',
      lane: 'A_pre_alpha',
      content_type: 'process_essay',
      status: 'verified',
      status_label: 'Review passed',
      platform_fit: ['X', 'LinkedIn', 'Substack'],
      citation_state: 'verified',
      media_state: 'neutral',
      approval_state: 'Approved for manual',
      owner: 'Jim',
      last_updated: '2026-06-14',
      evidence_id: 'REF-8821',
    },
    {
      id: 'GN-0042',
      title: 'CPI print as a hook: data sufficiency, not a call',
      lane: 'B_grounded_news',
      content_type: 'grounded_explainer',
      status: 'review',
      status_label: 'Awaiting review',
      platform_fit: ['X', 'LinkedIn', 'Threads'],
      citation_state: 'review',
      media_state: 'review',
      approval_state: 'In review',
      owner: 'Jim',
      last_updated: '2026-06-15',
      evidence_id: 'REF-8830',
    },
    {
      id: 'GN-0043',
      title: 'Reading official-source revisions without implying a signal',
      lane: 'B_grounded_news',
      content_type: 'grounded_explainer',
      status: 'review',
      status_label: 'Awaiting review',
      platform_fit: ['LinkedIn', 'Substack'],
      citation_state: 'verified',
      media_state: 'neutral',
      approval_state: 'In review',
      owner: 'Jim',
      last_updated: '2026-06-15',
      evidence_id: 'REF-8831',
    },
    {
      id: 'CA-0009',
      title: 'Artifact-backed macro brief (BLOCKED â€” future)',
      lane: 'C_artifact_backed',
      content_type: 'artifact_backed_packet',
      status: 'blocked',
      status_label: 'Blocked â€” intake gate',
      platform_fit: [],
      citation_state: 'blocked',
      media_state: 'neutral',
      approval_state: 'Blocked',
      owner: 'system',
      last_updated: '2026-06-15',
      evidence_id: 'REF-8840',
    },
  ],
  editorial_draft: {
    id: 'GN-0042',
    title: 'CPI print as a hook: data sufficiency, not a call',
    outline: [
      'Hook: what the CPI print actually is',
      'Why a number is not a signal',
      'Data sufficiency lens',
      'Forecast-readiness caveats',
      'Safe takeaway for readers',
    ],
    body_excerpt:
      'Today\u2019s CPI print is a useful hook to explain how we read official data. It is context, not a call. We do not issue buy/sell/hold guidance...',
    platform_tabs: ['X', 'LinkedIn', 'Threads', 'Substack'],
    citations: [
      { id: 'CIT-1', label: 'BLS CPI release (official source)', status: 'verified' },
      { id: 'CIT-2', label: 'Methodology note', status: 'review' },
    ],
    limitation_note:
      'No predictive claim. No price target. News is a hook, not a signal. No financial advice.',
    claim_risks: [
      { id: 'CR-1', label: 'Avoid implied forecast authority', severity: 'review' },
      { id: 'CR-2', label: 'No unsupported numeric market claim', severity: 'review' },
    ],
    guardrails: [
      { id: 'G-1', label: 'No-signal language', status: 'verified' },
      { id: 'G-2', label: 'No financial advice', status: 'verified' },
      { id: 'G-3', label: 'Citations preserved', status: 'review' },
    ],
    seo: {
      keywords: ['CPI explainer', 'data sufficiency', 'macro education', 'inflation data'],
      title_candidates: [
        'CPI is a hook, not a signal',
        'How to read a CPI print without making a call',
        'Data sufficiency over predictions',
      ],
      hook_variants: [
        'A CPI print is context, not a command.',
        'The number matters less than what it can and cannot tell you.',
      ],
      editorial_score: 82,
      seo_score: 74,
      platform_fit_score: 88,
      readability: 'Grade 9 Â· clear',
    },
    ai_outputs: [
      {
        variant_id: 'AIV-001',
        source_draft_id: 'GN-0042',
        platform: 'LinkedIn',
        audience_mode: 'Macro professional',
        style_mode: 'Analytical',
        content_type: 'grounded_explainer',
        body: 'Today\u2019s CPI print is a useful teaching moment, not a market call. Here is how we read official data without implying a forecast...',
        hook_type: 'Educational framing',
        hashtags: ['#macro', '#CPI', '#dataliteracy'],
        seo_keywords: ['CPI explainer', 'data sufficiency', 'macro education'],
        title_candidates: ['CPI is a hook, not a signal', 'Reading a CPI print without a call'],
        limitations_preserved: true,
        source_references_preserved: true,
        safety_notes: ['No-signal language enforced', 'No financial advice', 'Citations preserved'],
        not_public_postable_reason: 'Review-only. No provider gate, no human approval yet.',
        editorial_score: 84,
        seo_score: 76,
        platform_fit_score: 90,
        guardrail_status: 'verified',
        human_review_required: true,
        publish_ready: false,
      },
      {
        variant_id: 'AIV-002',
        source_draft_id: 'GN-0042',
        platform: 'X',
        audience_mode: 'General educated macro audience',
        style_mode: 'Concise',
        content_type: 'grounded_explainer',
        body: 'A CPI print is context, not a command. What it can and cannot tell you, in plain terms...',
        hook_type: 'Contrarian framing',
        hashtags: ['#CPI', '#inflation'],
        seo_keywords: ['inflation data', 'CPI explainer'],
        title_candidates: ['The number is not the news', 'Context over calls'],
        limitations_preserved: true,
        source_references_preserved: true,
        safety_notes: ['No-signal language pending review', 'No financial advice'],
        not_public_postable_reason: 'Review-only. Guardrail check pending.',
        editorial_score: 71,
        seo_score: 68,
        platform_fit_score: 79,
        guardrail_status: 'review',
        human_review_required: true,
        publish_ready: false,
      },
    ],
    media: [
      {
        id: 'MED-001',
        name: 'cpi_data_sufficiency_card.png',
        kind: 'image/mock',
        alt_text: 'Illustrative data-sufficiency card (mock, redacted).',
        rights_status: 'verified',
        rights_label: 'Internal / cleared',
        platform_constraints: ['X: 16:9 preferred', 'LinkedIn: 1200x627'],
        selected: true,
      },
      {
        id: 'MED-002',
        name: 'forecast_readiness_explainer.png',
        kind: 'image/mock',
        alt_text: 'Forecast-readiness explainer placeholder (mock).',
        rights_status: 'review',
        rights_label: 'Pending rights',
        platform_constraints: ['Threads: 1:1'],
        selected: false,
      },
    ],
  },
  ai_writer_lab: {
    source_draft_id: 'GN-0042',
    audience_modes: ['Macro professional', 'General educated macro audience', 'Newsletter subscriber'],
    style_modes: ['Analytical', 'Concise', 'Explanatory'],
    keyword_groups: [
      {
        id: 'KG-1',
        label: 'Educational macro intent',
        intent: 'Inform / explain',
        keywords: ['CPI explainer', 'data sufficiency', 'macro education', 'how to read CPI'],
        seo_score: 78,
        status: 'verified',
      },
      {
        id: 'KG-2',
        label: 'News-hook intent',
        intent: 'Topical relevance',
        keywords: ['CPI print', 'inflation data', 'latest CPI'],
        seo_score: 64,
        status: 'review',
      },
      {
        id: 'KG-3',
        label: 'Forecast intent (excluded)',
        intent: 'Excluded â€” implies prediction',
        keywords: ['CPI forecast', 'rate prediction', 'buy signal'],
        seo_score: 0,
        status: 'blocked',
      },
    ],
    outputs: [
      {
        variant_id: 'AIV-001',
        source_draft_id: 'GN-0042',
        platform: 'LinkedIn',
        audience_mode: 'Macro professional',
        style_mode: 'Analytical',
        content_type: 'grounded_explainer',
        body: 'Today\u2019s CPI print is a useful teaching moment, not a market call. Here is how we read official data without implying a forecast. The release is context for understanding measurement, revisions, and data sufficiency...',
        hook_type: 'Educational framing',
        hashtags: ['#macro', '#CPI', '#dataliteracy'],
        seo_keywords: ['CPI explainer', 'data sufficiency', 'macro education'],
        title_candidates: ['CPI is a hook, not a signal', 'Reading a CPI print without a call'],
        limitations_preserved: true,
        source_references_preserved: true,
        safety_notes: ['No-signal language enforced', 'No financial advice', 'Citations preserved'],
        not_public_postable_reason: 'Review-only. No provider gate, no human approval yet.',
        editorial_score: 84,
        seo_score: 76,
        platform_fit_score: 90,
        guardrail_status: 'verified',
        human_review_required: true,
        publish_ready: false,
      },
      {
        variant_id: 'AIV-002',
        source_draft_id: 'GN-0042',
        platform: 'X',
        audience_mode: 'General educated macro audience',
        style_mode: 'Concise',
        content_type: 'grounded_explainer',
        body: 'A CPI print is context, not a command. What it can and cannot tell you, in plain terms. No call, no target, just how the data is built...',
        hook_type: 'Contrarian framing',
        hashtags: ['#CPI', '#inflation'],
        seo_keywords: ['inflation data', 'CPI explainer'],
        title_candidates: ['The number is not the news', 'Context over calls'],
        limitations_preserved: true,
        source_references_preserved: true,
        safety_notes: ['No-signal language pending review', 'No financial advice'],
        not_public_postable_reason: 'Review-only. Guardrail check pending.',
        editorial_score: 71,
        seo_score: 68,
        platform_fit_score: 79,
        guardrail_status: 'review',
        human_review_required: true,
        publish_ready: false,
      },
      {
        variant_id: 'AIV-003',
        source_draft_id: 'GN-0042',
        source_artifact_id: undefined,
        platform: 'Substack',
        audience_mode: 'Newsletter subscriber',
        style_mode: 'Explanatory',
        content_type: 'grounded_explainer',
        body: 'In this issue we walk through what a CPI release measures, why revisions happen, and why a single print is rarely sufficient to support a forecast...',
        hook_type: 'Long-form explainer',
        hashtags: [],
        seo_keywords: ['CPI explainer', 'inflation methodology', 'data revisions'],
        title_candidates: ['What a CPI print actually measures', 'Revisions, sufficiency, and restraint'],
        limitations_preserved: true,
        source_references_preserved: true,
        safety_notes: ['No-signal language enforced', 'No financial advice', 'Methodology caveat preserved'],
        not_public_postable_reason: 'Review-only. Editorial sign-off and provider gate both pending.',
        editorial_score: 88,
        seo_score: 72,
        platform_fit_score: 85,
        guardrail_status: 'verified',
        human_review_required: true,
        publish_ready: false,
      },
    ],
  },
  draft_inspections: [
    {
      id: 'DI-0042',
      draft_id: 'GN-0042',
      title: 'CPI print as a hook: data sufficiency, not a call',
      source_lineage: [
        { id: 'LIN-A', label: 'BLS CPI release (official source) \u2192 REF-8830' },
        { id: 'LIN-B', label: 'Methodology note \u2192 CIT-2 (pending verify)' },
        { id: 'LIN-C', label: 'Editorial draft GN-0042 (local working copy)' },
      ],
      citation_checks: [
        { id: 'CC-1', label: 'Primary source cited', source_ref: 'CIT-1', status: 'verified', detail: 'BLS CPI release linked to claim.' },
        { id: 'CC-2', label: 'Methodology note verified', source_ref: 'CIT-2', status: 'review', detail: 'Awaiting reviewer confirmation of methodology note.' },
        { id: 'CC-3', label: 'No uncited numeric claim', source_ref: '\u2014', status: 'verified', detail: 'No market number stated without a source.' },
      ],
      limitation_checks: [
        { id: 'LC-1', label: 'Limitation note present', status: 'verified', detail: 'Explicit "news is a hook, not a signal" caveat retained.' },
        { id: 'LC-2', label: 'No predictive claim', status: 'verified', detail: 'No forecast or price target language.' },
      ],
      claim_risk_items: [
        { id: 'CRI-1', label: 'Implied forecast authority', classification: 'Tone risk', severity: 'review', detail: 'Ensure framing stays explanatory, not directional.' },
        { id: 'CRI-2', label: 'Unsupported numeric market claim', classification: 'Evidence risk', severity: 'review', detail: 'Any number must trace to an official source.' },
        { id: 'CRI-3', label: 'Signal/advice language', classification: 'Policy risk', severity: 'verified', detail: 'No buy/sell/hold or signal phrasing detected.' },
      ],
      no_signal_checks: [
        { id: 'NS-1', label: 'No buy/sell/hold language', status: 'verified', detail: 'Forbidden directive terms absent.' },
        { id: 'NS-2', label: 'No price target / level call', status: 'verified', detail: 'No numeric target asserted.' },
        { id: 'NS-3', label: 'No financial advice phrasing', status: 'verified', detail: 'Advice-form sentences absent.' },
      ],
      artifact_eligibility_checks: [
        { id: 'AE-1', label: 'Lane C artifact intake', status: 'blocked', detail: 'No approved artifact spec/export gate yet.' },
        { id: 'AE-2', label: 'Lineage manifest + checksum', status: 'blocked', detail: 'Required before artifact-backed eligibility.' },
      ],
      approval_readiness: 'Not ready \u2014 1 citation pending, artifact intake blocked',
      approval_readiness_status: 'review',
      human_review_required: true,
      publish_ready: false,
    },
  ],
  platform_payload_previews: buildCockpitPreviews(),
  manual_publish_records: buildCockpitManualRecords(),
  approval_packets: [
    {
      id: 'AP-0031',
      title: 'CPI hook explainer â€” manual approval packet',
      required_approver: 'Jim',
      draft_hash: 'sha256:9f2aâ€¦c4e1',
      payload_hash: 'sha256:1b77â€¦aa90',
      approval_state: 'Awaiting signature',
      approval_status: 'review',
      revocation_state: 'none',
      redacted_audit_state: 'ready',
      risk_state: 'review',
      evidence_sources: ['REF-8830', 'CIT-1', 'CIT-2'],
      comments: [{ author: 'Jim', note: 'Hold until citation CIT-2 verified.' }],
      gates: [
        { id: 'GATE-approval', label: 'Approval ledger', status: 'review', cleared: false, detail: 'Signature pending.' },
        { id: 'GATE-payload', label: 'Payload hash match', status: 'verified', cleared: true, detail: 'Hash matches draft.' },
        { id: 'GATE-guardrail', label: 'Guardrail pass', status: 'review', cleared: false, detail: 'No-signal check pending.' },
        { id: 'GATE-kill', label: 'Kill switch', status: 'neutral', cleared: false, detail: 'Armed. Dispatch globally disabled.' },
        { id: 'GATE-cred', label: 'Credential slot', status: 'neutral', cleared: false, detail: 'Empty by policy. No credential read.' },
        { id: 'GATE-live', label: 'Platform live gate', status: 'blocked', cleared: false, detail: 'No platform API. Future-gated.' },
        { id: 'GATE-audit', label: 'Redacted audit ready', status: 'verified', cleared: true, detail: 'Audit trail prepared.' },
        { id: 'GATE-rollback', label: 'Rollback / manual fallback', status: 'verified', cleared: true, detail: 'Manual-only fallback.' },
      ],
      dispatch_enabled: false,
    },
  ],
  evidence_packets: [
    {
      id: 'EV-0174BZ',
      task_label: 'TASK_CONTENTOPS_0174BZ_V5_FRONTEND_SCAFFOLD_AND_DESIGN_SYSTEM_FOUNDATION_V0',
      result: 'verified',
      result_label: 'Verified local (foundation)',
      commit_ref: 'commit@pending',
      timestamp: '2026-06-15T09:22:00+07:00',
      validation_matrix: [
        { id: 'VM-1', label: 'V5 app builds', status: 'verified', detail: 'vite build passes.' },
        { id: 'VM-2', label: '5 flagship views', status: 'verified', detail: 'All present.' },
        { id: 'VM-3', label: 'Light + dark evidence mode', status: 'verified', detail: 'Theme tokens wired.' },
        { id: 'VM-4', label: 'No runtime CDN/remote font', status: 'verified', detail: 'Bundled assets only.' },
        { id: 'VM-5', label: 'No network/credential/platform API', status: 'verified', detail: 'Static scan clean.' },
      ],
      forbidden_scope: [
        { id: 'FS-1', label: 'Runtime network/fetch', status: 'verified' },
        { id: 'FS-2', label: 'localStorage/sessionStorage', status: 'verified' },
        { id: 'FS-3', label: 'Platform/provider API', status: 'verified' },
        { id: 'FS-4', label: 'Credential/env read', status: 'verified' },
      ],
      secret_scan: { label: 'Secret scan', status: 'verified', detail: 'No secrets in V5 source.' },
      provenance_chips: ['local-fixture', 'build-time-only', 'no-network', 'no-credentials'],
      source_lineage: [
        { id: 'LIN-1', label: 'V5 master plan @342fc91' },
        { id: 'LIN-2', label: 'Stitch v5.1 references (reference-only)' },
      ],
    },
  ],
  v6_operator_approval_evidence: {
    packet_id: 'operator_approval_queue_evidence_vault_d4a5afd3ecf03b1b',
    source_article_packet_id: 'article_engine_packet_d4a5afd3ecf03b1b',
    source_article_packet_hash: 'd4a5afd3ecf03b1b93caf5b9dbd204d93eb80237eb8d368c9eea24680fabe44e',
    sample_scope: 'sample_fixture_only',
    runtime_proof: false,
    provider_call_made: false,
    network_call_made: false,
    live_send_performed: false,
    browser_session_used: false,
    raw_secret_values_serialized: false,
    env_lines_serialized: false,
    approval_queue_items: [
      {
        queue_item_id: 'queue_approval_discord_1cd58fd896f19c77',
        platform: 'discord',
        variant_id: 'variant_discord_d4a5afd3ecf03b1b',
        preview_id: 'preview_discord_1cd58fd896f19c77',
        preview_hash: '1cd58fd896f19c77638e62c52f34700c8166bd9644a8d830071d174924ca9172',
        approval_status: 'pending_operator_review',
        live_dispatch_allowed: false,
        exact_preview_text_excerpt: '[discord] Capital Chronicle Educational Briefing: Evaluate historical volatility in macro calendar commentaries...',
        required_operator_action: 'Review exact preview hash and content; no live dispatch is enabled.',
      },
      {
        queue_item_id: 'queue_approval_telegram_operator_974e8509d7999aca',
        platform: 'telegram_operator',
        variant_id: 'variant_telegram_d4a5afd3ecf03b1b',
        preview_id: 'preview_telegram_operator_974e8509d7999aca',
        preview_hash: '974e8509d7999acad8cdf4855dc874d2d7182e766a51d4d1b4a6d6749126eb32',
        approval_status: 'pending_operator_review',
        live_dispatch_allowed: false,
        exact_preview_text_excerpt: '[telegram_operator] Capital Chronicle Educational Briefing: operator checkpoint...',
        required_operator_action: 'Review exact preview hash and content; no live dispatch is enabled.',
      },
      {
        queue_item_id: 'queue_approval_substack_c19e65c51abb0967',
        platform: 'substack',
        variant_id: 'variant_substack_d4a5afd3ecf03b1b',
        preview_id: 'preview_substack_c19e65c51abb0967',
        preview_hash: 'c19e65c51abb0967d25dde12e8c1b5ff2a3fa32ccac3b9e14eb7d73aa30b1b59',
        approval_status: 'pending_operator_review',
        live_dispatch_allowed: false,
        exact_preview_text_excerpt: '[substack] Capital Chronicle Educational Briefing: process-led analysis...',
        required_operator_action: 'Review exact preview hash and content; no live dispatch is enabled.',
      },
    ],
    evidence_vault_items: [
      {
        evidence_id: 'evidence_article_d4a5afd3ecf03b1b',
        evidence_type: 'canonical_article_packet',
        source_file_path: 'docs/automation/V6_AI_RESEARCH_CANONICAL_ARTICLE_ENGINE/sample_ai_research_canonical_article_packet.json',
        source_packet_id: 'article_engine_packet_d4a5afd3ecf03b1b',
        source_hash_or_preview_hash: 'd4a5afd3ecf03b1b93caf5b9dbd204d93eb80237eb8d368c9eea24680fabe44e',
        display_status: 'green_verified',
        caveats: ['Committed sample packet only.'],
        safety_flags: { provider_call_made: false, network_call_made: false, live_send_performed: false, browser_session_used: false, raw_secret_values_serialized: false, env_lines_serialized: false },
      },
      {
        evidence_id: 'evidence_variant_d4a5afd3ecf03b1b',
        evidence_type: 'variant_preview_hash_approval_packet',
        source_file_path: 'docs/automation/V6_VARIANT_PREVIEW_HASH_APPROVAL_TO_DISCORD_OUTBOX/sample_variant_preview_hash_approval_packet.json',
        source_packet_id: 'variant_preview_hash_packet_d4a5afd3ecf03b1b',
        source_hash_or_preview_hash: '1cd58fd896f19c77638e62c52f34700c8166bd9644a8d830071d174924ca9172',
        display_status: 'green_verified',
        caveats: ['Approval records remain pending.'],
        safety_flags: { provider_call_made: false, network_call_made: false, live_send_performed: false, browser_session_used: false, raw_secret_values_serialized: false, env_lines_serialized: false },
      },
    ],
    discord_outbox_card: {
      packet_id: 'discord_dry_run_outbox_e59579adf7eb8db3',
      outbox_id: 'discord_outbox_dry_run_e59579adf7eb8db3',
      approved_payload_hash: 'e59579adf7eb8db3839080f3b1b6f6744012d064f1fa58a96abb02bdff73bb80',
      operator_approval_status: 'pending',
      live_send_allowed: false,
      live_send_performed: false,
      sample_key_presence: { evidence_scope: 'sample_fixture_only', runtime_proof: false },
    },
    live_pilot_status_card: {
      result_class: 'blocked',
      display_status: 'red_blocked',
      live_send_attempted: false,
      live_send_succeeded: false,
      blockers: ['operator_approval_declaration_missing', 'operator_approval_status_not_approved', 'operator_approval_exact_payload_hash_mismatch'],
    },
  },  audit_events: [
    { id: 'AE-1', timestamp: '2026-06-15T09:00:00+07:00', actor: 'operator', action: 'Committed V5 master plan + references', ref: '342fc91' },
    { id: 'AE-2', timestamp: '2026-06-15T09:22:00+07:00', actor: 'agent', action: 'Scaffolded V5 frontend foundation', ref: 'pending' },
  ],
  policy_boundaries: [
    { id: 'PB-1', label: 'Local-only mode', status: 'verified', detail: 'No backend, no runtime network.' },
    { id: 'PB-2', label: 'Credential policy', status: 'verified', detail: 'No credential/env read. .env never accessed.' },
    { id: 'PB-3', label: 'No-advice policy', status: 'verified', detail: 'No financial advice or signals.' },
    { id: 'PB-4', label: 'AI provider gate', status: 'neutral', detail: 'LLM provider disabled until explicit task.' },
    { id: 'PB-5', label: 'Internal alpha intake gate', status: 'blocked', detail: 'Artifact intake not available yet.' },
  ],
  internal_alpha_artifacts: [
    {
      id: 'IA-PLACEHOLDER-1',
      artifact_type: 'forecast_readiness_artifact',
      intake_status: 'blocked',
      intake_label: 'Intake blocked',
      reason_blocked: 'No approved artifact spec, export location, or readiness gate exists yet.',
    },
    {
      id: 'IA-PLACEHOLDER-2',
      artifact_type: 'data_sufficiency_artifact',
      intake_status: 'blocked',
      intake_label: 'Intake blocked',
      reason_blocked: 'Awaiting lineage manifest + checksum contract.',
    },
  ],
};
