// Capital Chronicle ContentOps V5 — local fixture view-model.
// LOCAL FIXTURE DATA ONLY. No runtime network, no credentials, no platform API.
// All ids/hashes are synthetic placeholders for UI demonstration.

import type { ContentOpsViewModel } from './types';

export const viewModel: ContentOpsViewModel = {
  system_state: {
    product_mode: 'LOCAL_PRE_ALPHA',
    modes: [
      { code: 'LOCAL_PRE_ALPHA', active: true },
      { code: 'REVIEW_ONLY', active: true },
      { code: 'NOT_PUBLIC_POSTABLE', active: true },
      { code: 'FUTURE_LIVE_DISABLED', active: true },
      { code: 'MANUAL_APPROVAL_REQUIRED', active: true },
      { code: 'NO_FINANCIAL_ADVICE', active: true },
      { code: 'NO_SIGNAL_LANGUAGE', active: true },
      { code: 'NO_PLATFORM_API', active: true },
      { code: 'NO_PROVIDER_API', active: true },
      { code: 'NO_CREDENTIAL_READ', active: true },
      { code: 'NO_SCHEDULER', active: true },
      { code: 'NO_SCRAPING', active: true },
    ],
    verdict: 'SAFE — LOCAL REVIEW ONLY',
    verdict_status: 'verified',
    baseline_ref: 'baseline@342fc91',
    build_provenance: 'local-fixture · no-network · build-time-only',
    next_allowed_action: 'Review grounded news draft GN-0042 in Writer Studio',
    blockers: [
      {
        id: 'BLK-001',
        label: 'Internal alpha artifact intake not available',
        detail: 'Lane C artifact-backed content blocked until approved artifact spec + export gate exist.',
        severity: 'blocked',
      },
      {
        id: 'BLK-002',
        label: 'Platform live dispatch disabled',
        detail: 'No platform/provider API. All dispatch gates future-gated.',
        severity: 'blocked',
      },
      {
        id: 'BLK-003',
        label: 'LLM provider gate not opened',
        detail: 'AI Writer is UI-only. No provider calls until an explicit approved gate task.',
        severity: 'review',
      },
    ],
    validation_passes: [
      { id: 'VP-1', label: 'No runtime network', status: 'verified', detail: 'Static scan: no fetch/XHR/WebSocket.' },
      { id: 'VP-2', label: 'No credential/env read', status: 'verified', detail: 'No process.env / .env access in app.' },
      { id: 'VP-3', label: 'Build-time deps only', status: 'verified', detail: 'Bundled fonts + icons, no CDN.' },
      { id: 'VP-4', label: 'No-signal language guard', status: 'review', detail: 'Editorial guardrails enforced in Writer Studio.' },
    ],
    pipeline_health: [
      { label: 'Fixtures', value: 'loaded', status: 'verified' },
      { label: 'Lineage', value: 'verified', status: 'verified' },
      { label: 'Dispatch', value: 'gated', status: 'neutral' },
      { label: 'Providers', value: 'disabled', status: 'neutral' },
    ],
    queue_summary: [
      { label: 'Awaiting review', count: 3, status: 'review' },
      { label: 'Approved (manual)', count: 1, status: 'verified' },
      { label: 'Blocked', count: 2, status: 'blocked' },
    ],
  },
  content_items: [
    {
      id: 'PA-0017',
      title: 'Why "no forecast" can be the correct output',
      lane: 'A_pre_alpha',
      content_type: 'process_essay',
      status: 'verified',
      status_label: 'Review passed',
      platform_fit: ['X', 'LinkedIn', 'Substack'],
      citation_state: 'verified',
      media_state: 'neutral',
      approval_state: 'Approved for manual',
      owner: 'Jim',
      last_updated: '2026-06-14',
      evidence_id: 'REF-8821',
    },
    {
      id: 'GN-0042',
      title: 'CPI print as a hook: data sufficiency, not a call',
      lane: 'B_grounded_news',
      content_type: 'grounded_explainer',
      status: 'review',
      status_label: 'Awaiting review',
      platform_fit: ['X', 'LinkedIn', 'Threads'],
      citation_state: 'review',
      media_state: 'review',
      approval_state: 'In review',
      owner: 'Jim',
      last_updated: '2026-06-15',
      evidence_id: 'REF-8830',
    },
    {
      id: 'GN-0043',
      title: 'Reading official-source revisions without implying a signal',
      lane: 'B_grounded_news',
      content_type: 'grounded_explainer',
      status: 'review',
      status_label: 'Awaiting review',
      platform_fit: ['LinkedIn', 'Substack'],
      citation_state: 'verified',
      media_state: 'neutral',
      approval_state: 'In review',
      owner: 'Jim',
      last_updated: '2026-06-15',
      evidence_id: 'REF-8831',
    },
    {
      id: 'CA-0009',
      title: 'Artifact-backed macro brief (BLOCKED — future)',
      lane: 'C_artifact_backed',
      content_type: 'artifact_backed_packet',
      status: 'blocked',
      status_label: 'Blocked — intake gate',
      platform_fit: [],
      citation_state: 'blocked',
      media_state: 'neutral',
      approval_state: 'Blocked',
      owner: 'system',
      last_updated: '2026-06-15',
      evidence_id: 'REF-8840',
    },
  ],
  editorial_draft: {
    id: 'GN-0042',
    title: 'CPI print as a hook: data sufficiency, not a call',
    outline: [
      'Hook: what the CPI print actually is',
      'Why a number is not a signal',
      'Data sufficiency lens',
      'Forecast-readiness caveats',
      'Safe takeaway for readers',
    ],
    body_excerpt:
      'Today\u2019s CPI print is a useful hook to explain how we read official data. It is context, not a call. We do not issue buy/sell/hold guidance...',
    platform_tabs: ['X', 'LinkedIn', 'Threads', 'Substack'],
    citations: [
      { id: 'CIT-1', label: 'BLS CPI release (official source)', status: 'verified' },
      { id: 'CIT-2', label: 'Methodology note', status: 'review' },
    ],
    limitation_note:
      'No predictive claim. No price target. News is a hook, not a signal. No financial advice.',
    claim_risks: [
      { id: 'CR-1', label: 'Avoid implied forecast authority', severity: 'review' },
      { id: 'CR-2', label: 'No unsupported numeric market claim', severity: 'review' },
    ],
    guardrails: [
      { id: 'G-1', label: 'No-signal language', status: 'verified' },
      { id: 'G-2', label: 'No financial advice', status: 'verified' },
      { id: 'G-3', label: 'Citations preserved', status: 'review' },
    ],
    seo: {
      keywords: ['CPI explainer', 'data sufficiency', 'macro education', 'inflation data'],
      title_candidates: [
        'CPI is a hook, not a signal',
        'How to read a CPI print without making a call',
        'Data sufficiency over predictions',
      ],
      hook_variants: [
        'A CPI print is context, not a command.',
        'The number matters less than what it can and cannot tell you.',
      ],
      editorial_score: 82,
      seo_score: 74,
      platform_fit_score: 88,
      readability: 'Grade 9 · clear',
    },
    ai_outputs: [
      {
        variant_id: 'AIV-001',
        source_draft_id: 'GN-0042',
        platform: 'LinkedIn',
        audience_mode: 'Macro professional',
        style_mode: 'Analytical',
        content_type: 'grounded_explainer',
        guardrail_status: 'verified',
        human_review_required: true,
        publish_ready: false,
        not_public_postable_reason: 'Review-only. No provider gate, no human approval yet.',
        limitations_preserved: true,
        source_references_preserved: true,
      },
      {
        variant_id: 'AIV-002',
        source_draft_id: 'GN-0042',
        platform: 'X',
        audience_mode: 'General educated macro audience',
        style_mode: 'Concise',
        content_type: 'grounded_explainer',
        guardrail_status: 'review',
        human_review_required: true,
        publish_ready: false,
        not_public_postable_reason: 'Review-only. Guardrail check pending.',
        limitations_preserved: true,
        source_references_preserved: true,
      },
    ],
    media: [
      {
        id: 'MED-001',
        name: 'cpi_data_sufficiency_card.png',
        kind: 'image/mock',
        alt_text: 'Illustrative data-sufficiency card (mock, redacted).',
        rights_status: 'verified',
        rights_label: 'Internal / cleared',
        platform_constraints: ['X: 16:9 preferred', 'LinkedIn: 1200x627'],
        selected: true,
      },
      {
        id: 'MED-002',
        name: 'forecast_readiness_explainer.png',
        kind: 'image/mock',
        alt_text: 'Forecast-readiness explainer placeholder (mock).',
        rights_status: 'review',
        rights_label: 'Pending rights',
        platform_constraints: ['Threads: 1:1'],
        selected: false,
      },
    ],
  },
  approval_packets: [
    {
      id: 'AP-0031',
      title: 'CPI hook explainer — manual approval packet',
      required_approver: 'Jim',
      draft_hash: 'sha256:9f2a…c4e1',
      payload_hash: 'sha256:1b77…aa90',
      approval_state: 'Awaiting signature',
      approval_status: 'review',
      revocation_state: 'none',
      redacted_audit_state: 'ready',
      risk_state: 'review',
      evidence_sources: ['REF-8830', 'CIT-1', 'CIT-2'],
      comments: [{ author: 'Jim', note: 'Hold until citation CIT-2 verified.' }],
      gates: [
        { id: 'GATE-approval', label: 'Approval ledger', status: 'review', cleared: false, detail: 'Signature pending.' },
        { id: 'GATE-payload', label: 'Payload hash match', status: 'verified', cleared: true, detail: 'Hash matches draft.' },
        { id: 'GATE-guardrail', label: 'Guardrail pass', status: 'review', cleared: false, detail: 'No-signal check pending.' },
        { id: 'GATE-kill', label: 'Kill switch', status: 'neutral', cleared: false, detail: 'Armed. Dispatch globally disabled.' },
        { id: 'GATE-cred', label: 'Credential slot', status: 'neutral', cleared: false, detail: 'Empty by policy. No credential read.' },
        { id: 'GATE-live', label: 'Platform live gate', status: 'blocked', cleared: false, detail: 'No platform API. Future-gated.' },
        { id: 'GATE-audit', label: 'Redacted audit ready', status: 'verified', cleared: true, detail: 'Audit trail prepared.' },
        { id: 'GATE-rollback', label: 'Rollback / manual fallback', status: 'verified', cleared: true, detail: 'Manual-only fallback.' },
      ],
      dispatch_enabled: false,
    },
  ],
  evidence_packets: [
    {
      id: 'EV-0174BZ',
      task_label: 'TASK_CONTENTOPS_0174BZ_V5_FRONTEND_SCAFFOLD_AND_DESIGN_SYSTEM_FOUNDATION_V0',
      result: 'verified',
      result_label: 'Foundation shipped',
      commit_ref: 'commit@pending',
      timestamp: '2026-06-15T09:22:00+07:00',
      validation_matrix: [
        { id: 'VM-1', label: 'V5 app builds', status: 'verified', detail: 'vite build passes.' },
        { id: 'VM-2', label: '5 flagship views', status: 'verified', detail: 'All present.' },
        { id: 'VM-3', label: 'Light + dark evidence mode', status: 'verified', detail: 'Theme tokens wired.' },
        { id: 'VM-4', label: 'No runtime CDN/remote font', status: 'verified', detail: 'Bundled assets only.' },
        { id: 'VM-5', label: 'No network/credential/platform API', status: 'verified', detail: 'Static scan clean.' },
      ],
      forbidden_scope: [
        { id: 'FS-1', label: 'Runtime network/fetch', status: 'verified' },
        { id: 'FS-2', label: 'localStorage/sessionStorage', status: 'verified' },
        { id: 'FS-3', label: 'Platform/provider API', status: 'verified' },
        { id: 'FS-4', label: 'Credential/env read', status: 'verified' },
      ],
      secret_scan: { label: 'Secret scan', status: 'verified', detail: 'No secrets in V5 source.' },
      provenance_chips: ['local-fixture', 'build-time-only', 'no-network', 'no-credentials'],
      source_lineage: [
        { id: 'LIN-1', label: 'V5 master plan @342fc91' },
        { id: 'LIN-2', label: 'Stitch v5.1 references (reference-only)' },
      ],
    },
  ],
  audit_events: [
    { id: 'AE-1', timestamp: '2026-06-15T09:00:00+07:00', actor: 'operator', action: 'Committed V5 master plan + references', ref: '342fc91' },
    { id: 'AE-2', timestamp: '2026-06-15T09:22:00+07:00', actor: 'agent', action: 'Scaffolded V5 frontend foundation', ref: 'pending' },
  ],
  policy_boundaries: [
    { id: 'PB-1', label: 'Local-only mode', status: 'verified', detail: 'No backend, no runtime network.' },
    { id: 'PB-2', label: 'Credential policy', status: 'verified', detail: 'No credential/env read. .env never accessed.' },
    { id: 'PB-3', label: 'No-advice policy', status: 'verified', detail: 'No financial advice or signals.' },
    { id: 'PB-4', label: 'AI provider gate', status: 'neutral', detail: 'LLM provider disabled until explicit task.' },
    { id: 'PB-5', label: 'Internal alpha intake gate', status: 'blocked', detail: 'Artifact intake not available yet.' },
  ],
  internal_alpha_artifacts: [
    {
      id: 'IA-PLACEHOLDER-1',
      artifact_type: 'forecast_readiness_artifact',
      intake_status: 'blocked',
      intake_label: 'Intake blocked',
      reason_blocked: 'No approved artifact spec, export location, or readiness gate exists yet.',
    },
    {
      id: 'IA-PLACEHOLDER-2',
      artifact_type: 'data_sufficiency_artifact',
      intake_status: 'blocked',
      intake_label: 'Intake blocked',
      reason_blocked: 'Awaiting lineage manifest + checksum contract.',
    },
  ],
};
