// Capital Chronicle ContentOps V5 — local fixture view-model.
// LOCAL FIXTURE DATA ONLY. No runtime network, no credentials, no platform API.
// All ids/hashes are synthetic placeholders for UI demonstration.

import type { ContentOpsViewModel } from './types';

export const viewModel: ContentOpsViewModel = {
  system_state: {
    product_mode: 'LOCAL_PRE_ALPHA',
    modes: [
      { code: 'LOCAL_PRE_ALPHA', active: true },
      { code: 'REVIEW_ONLY', active: true },
      { code: 'NOT_PUBLIC_POSTABLE', active: true },
      { code: 'FUTURE_LIVE_DISABLED', active: true },
      { code: 'MANUAL_APPROVAL_REQUIRED', active: true },
      { code: 'NO_FINANCIAL_ADVICE', active: true },
      { code: 'NO_SIGNAL_LANGUAGE', active: true },
      { code: 'NO_PLATFORM_API', active: true },
      { code: 'NO_PROVIDER_API', active: true },
      { code: 'NO_CREDENTIAL_READ', active: true },
      { code: 'NO_SCHEDULER', active: true },
      { code: 'NO_SCRAPING', active: true },
    ],
    verdict: 'SAFE — LOCAL REVIEW ONLY',
    verdict_status: 'verified',
    baseline_ref: 'baseline@342fc91',
    build_provenance: 'local-fixture · no-network · build-time-only',
    next_allowed_action: 'Review grounded news draft GN-0042 in Writer Studio',
    blockers: [
      {
        id: 'BLK-001',
        label: 'Internal alpha artifact intake not available',
        detail: 'Lane C artifact-backed content blocked until approved artifact spec + export gate exist.',
        severity: 'blocked',
      },
      {
        id: 'BLK-002',
        label: 'Platform live dispatch disabled',
        detail: 'No platform/provider API. All dispatch gates future-gated.',
        severity: 'blocked',
      },
      {
        id: 'BLK-003',
        label: 'LLM provider gate not opened',
        detail: 'AI Writer is UI-only. No provider calls until an explicit approved gate task.',
        severity: 'review',
      },
    ],
    validation_passes: [
      { id: 'VP-1', label: 'No runtime network', status: 'verified', detail: 'Static scan: no fetch/XHR/WebSocket.' },
      { id: 'VP-2', label: 'No credential/env read', status: 'verified', detail: 'No process.env / .env access in app.' },
      { id: 'VP-3', label: 'Build-time deps only', status: 'verified', detail: 'Bundled fonts + icons, no CDN.' },
      { id: 'VP-4', label: 'No-signal language guard', status: 'review', detail: 'Editorial guardrails enforced in Writer Studio.' },
    ],
    pipeline_health: [
      { label: 'Fixtures', value: 'loaded', status: 'verified' },
      { label: 'Lineage', value: 'verified', status: 'verified' },
      { label: 'Dispatch', value: 'gated', status: 'neutral' },
      { label: 'Providers', value: 'disabled', status: 'neutral' },
    ],
    queue_summary: [
      { label: 'Awaiting review', count: 3, status: 'review' },
      { label: 'Approved (manual)', count: 1, status: 'verified' },
      { label: 'Blocked', count: 2, status: 'blocked' },
    ],
  },
  content_items: [
    {
      id: 'PA-0017',
      title: 'Why "no forecast" can be the correct output',
      lane: 'A_pre_alpha',
      content_type: 'process_essay',
      status: 'verified',
      status_label: 'Review passed',
      platform_fit: ['X', 'LinkedIn', 'Substack'],
      citation_state: 'verified',
      media_state: 'neutral',
      approval_state: 'Approved for manual',
      owner: 'Jim',
      last_updated: '2026-06-14',
      evidence_id: 'REF-8821',
    },
    {
      id: 'GN-0042',
      title: 'CPI print as a hook: data sufficiency, not a call',
      lane: 'B_grounded_news',
      content_type: 'grounded_explainer',
      status: 'review',
      status_label: 'Awaiting review',
      platform_fit: ['X', 'LinkedIn', 'Threads'],
      citation_state: 'review',
      media_state: 'review',
      approval_state: 'In review',
      owner: 'Jim',
      last_updated: '2026-06-15',
      evidence_id: 'REF-8830',
    },
    {
      id: 'GN-0043',
      title: 'Reading official-source revisions without implying a signal',
      lane: 'B_grounded_news',
      content_type: 'grounded_explainer',
      status: 'review',
      status_label: 'Awaiting review',
      platform_fit: ['LinkedIn', 'Substack'],
      citation_state: 'verified',
      media_state: 'neutral',
      approval_state: 'In review',
      owner: 'Jim',
      last_updated: '2026-06-15',
      evidence_id: 'REF-8831',
    },
    {
      id: 'CA-0009',
      title: 'Artifact-backed macro brief (BLOCKED — future)',
      lane: 'C_artifact_backed',
      content_type: 'artifact_backed_packet',
      status: 'blocked',
      status_label: 'Blocked — intake gate',
      platform_fit: [],
      citation_state: 'blocked',
      media_state: 'neutral',
      approval_state: 'Blocked',
      owner: 'system',
      last_updated: '2026-06-15',
      evidence_id: 'REF-8840',
    },
  ],
  editorial_draft: {
    id: 'GN-0042',
    title: 'CPI print as a hook: data sufficiency, not a call',
    outline: [
      'Hook: what the CPI print actually is',
      'Why a number is not a signal',
      'Data sufficiency lens',
      'Forecast-readiness caveats',
      'Safe takeaway for readers',
    ],
    body_excerpt:
      'Today\u2019s CPI print is a useful hook to explain how we read official data. It is context, not a call. We do not issue buy/sell/hold guidance...',
    platform_tabs: ['X', 'LinkedIn', 'Threads', 'Substack'],
    citations: [
      { id: 'CIT-1', label: 'BLS CPI release (official source)', status: 'verified' },
      { id: 'CIT-2', label: 'Methodology note', status: 'review' },
    ],
    limitation_note:
      'No predictive claim. No price target. News is a hook, not a signal. No financial advice.',
    claim_risks: [
      { id: 'CR-1', label: 'Avoid implied forecast authority', severity: 'review' },
      { id: 'CR-2', label: 'No unsupported numeric market claim', severity: 'review' },
    ],
    guardrails: [
      { id: 'G-1', label: 'No-signal language', status: 'verified' },
      { id: 'G-2', label: 'No financial advice', status: 'verified' },
      { id: 'G-3', label: 'Citations preserved', status: 'review' },
    ],
    seo: {
      keywords: ['CPI explainer', 'data sufficiency', 'macro education', 'inflation data'],
      title_candidates: [
        'CPI is a hook, not a signal',
        'How to read a CPI print without making a call',
        'Data sufficiency over predictions',
      ],
      hook_variants: [
        'A CPI print is context, not a command.',
        'The number matters less than what it can and cannot tell you.',
      ],
      editorial_score: 82,
      seo_score: 74,
      platform_fit_score: 88,
      readability: 'Grade 9 · clear',
    },
    ai_outputs: [
      {
        variant_id: 'AIV-001',
        source_draft_id: 'GN-0042',
        platform: 'LinkedIn',
        audience_mode: 'Macro professional',
        style_mode: 'Analytical',
        content_type: 'grounded_explainer',
        body: 'Today\u2019s CPI print is a useful teaching moment, not a market call. Here is how we read official data without implying a forecast...',
        hook_type: 'Educational framing',
        hashtags: ['#macro', '#CPI', '#dataliteracy'],
        seo_keywords: ['CPI explainer', 'data sufficiency', 'macro education'],
        title_candidates: ['CPI is a hook, not a signal', 'Reading a CPI print without a call'],
        limitations_preserved: true,
        source_references_preserved: true,
        safety_notes: ['No-signal language enforced', 'No financial advice', 'Citations preserved'],
        not_public_postable_reason: 'Review-only. No provider gate, no human approval yet.',
        editorial_score: 84,
        seo_score: 76,
        platform_fit_score: 90,
        guardrail_status: 'verified',
        human_review_required: true,
        publish_ready: false,
      },
      {
        variant_id: 'AIV-002',
        source_draft_id: 'GN-0042',
        platform: 'X',
        audience_mode: 'General educated macro audience',
        style_mode: 'Concise',
        content_type: 'grounded_explainer',
        body: 'A CPI print is context, not a command. What it can and cannot tell you, in plain terms...',
        hook_type: 'Contrarian framing',
        hashtags: ['#CPI', '#inflation'],
        seo_keywords: ['inflation data', 'CPI explainer'],
        title_candidates: ['The number is not the news', 'Context over calls'],
        limitations_preserved: true,
        source_references_preserved: true,
        safety_notes: ['No-signal language pending review', 'No financial advice'],
        not_public_postable_reason: 'Review-only. Guardrail check pending.',
        editorial_score: 71,
        seo_score: 68,
        platform_fit_score: 79,
        guardrail_status: 'review',
        human_review_required: true,
        publish_ready: false,
      },
    ],
    media: [
      {
        id: 'MED-001',
        name: 'cpi_data_sufficiency_card.png',
        kind: 'image/mock',
        alt_text: 'Illustrative data-sufficiency card (mock, redacted).',
        rights_status: 'verified',
        rights_label: 'Internal / cleared',
        platform_constraints: ['X: 16:9 preferred', 'LinkedIn: 1200x627'],
        selected: true,
      },
      {
        id: 'MED-002',
        name: 'forecast_readiness_explainer.png',
        kind: 'image/mock',
        alt_text: 'Forecast-readiness explainer placeholder (mock).',
        rights_status: 'review',
        rights_label: 'Pending rights',
        platform_constraints: ['Threads: 1:1'],
        selected: false,
      },
    ],
  },
  ai_writer_lab: {
    source_draft_id: 'GN-0042',
    audience_modes: ['Macro professional', 'General educated macro audience', 'Newsletter subscriber'],
    style_modes: ['Analytical', 'Concise', 'Explanatory'],
    keyword_groups: [
      {
        id: 'KG-1',
        label: 'Educational macro intent',
        intent: 'Inform / explain',
        keywords: ['CPI explainer', 'data sufficiency', 'macro education', 'how to read CPI'],
        seo_score: 78,
        status: 'verified',
      },
      {
        id: 'KG-2',
        label: 'News-hook intent',
        intent: 'Topical relevance',
        keywords: ['CPI print', 'inflation data', 'latest CPI'],
        seo_score: 64,
        status: 'review',
      },
      {
        id: 'KG-3',
        label: 'Forecast intent (excluded)',
        intent: 'Excluded — implies prediction',
        keywords: ['CPI forecast', 'rate prediction', 'buy signal'],
        seo_score: 0,
        status: 'blocked',
      },
    ],
    outputs: [
      {
        variant_id: 'AIV-001',
        source_draft_id: 'GN-0042',
        platform: 'LinkedIn',
        audience_mode: 'Macro professional',
        style_mode: 'Analytical',
        content_type: 'grounded_explainer',
        body: 'Today\u2019s CPI print is a useful teaching moment, not a market call. Here is how we read official data without implying a forecast. The release is context for understanding measurement, revisions, and data sufficiency...',
        hook_type: 'Educational framing',
        hashtags: ['#macro', '#CPI', '#dataliteracy'],
        seo_keywords: ['CPI explainer', 'data sufficiency', 'macro education'],
        title_candidates: ['CPI is a hook, not a signal', 'Reading a CPI print without a call'],
        limitations_preserved: true,
        source_references_preserved: true,
        safety_notes: ['No-signal language enforced', 'No financial advice', 'Citations preserved'],
        not_public_postable_reason: 'Review-only. No provider gate, no human approval yet.',
        editorial_score: 84,
        seo_score: 76,
        platform_fit_score: 90,
        guardrail_status: 'verified',
        human_review_required: true,
        publish_ready: false,
      },
      {
        variant_id: 'AIV-002',
        source_draft_id: 'GN-0042',
        platform: 'X',
        audience_mode: 'General educated macro audience',
        style_mode: 'Concise',
        content_type: 'grounded_explainer',
        body: 'A CPI print is context, not a command. What it can and cannot tell you, in plain terms. No call, no target, just how the data is built...',
        hook_type: 'Contrarian framing',
        hashtags: ['#CPI', '#inflation'],
        seo_keywords: ['inflation data', 'CPI explainer'],
        title_candidates: ['The number is not the news', 'Context over calls'],
        limitations_preserved: true,
        source_references_preserved: true,
        safety_notes: ['No-signal language pending review', 'No financial advice'],
        not_public_postable_reason: 'Review-only. Guardrail check pending.',
        editorial_score: 71,
        seo_score: 68,
        platform_fit_score: 79,
        guardrail_status: 'review',
        human_review_required: true,
        publish_ready: false,
      },
      {
        variant_id: 'AIV-003',
        source_draft_id: 'GN-0042',
        source_artifact_id: undefined,
        platform: 'Substack',
        audience_mode: 'Newsletter subscriber',
        style_mode: 'Explanatory',
        content_type: 'grounded_explainer',
        body: 'In this issue we walk through what a CPI release measures, why revisions happen, and why a single print is rarely sufficient to support a forecast...',
        hook_type: 'Long-form explainer',
        hashtags: [],
        seo_keywords: ['CPI explainer', 'inflation methodology', 'data revisions'],
        title_candidates: ['What a CPI print actually measures', 'Revisions, sufficiency, and restraint'],
        limitations_preserved: true,
        source_references_preserved: true,
        safety_notes: ['No-signal language enforced', 'No financial advice', 'Methodology caveat preserved'],
        not_public_postable_reason: 'Review-only. Editorial sign-off and provider gate both pending.',
        editorial_score: 88,
        seo_score: 72,
        platform_fit_score: 85,
        guardrail_status: 'verified',
        human_review_required: true,
        publish_ready: false,
      },
    ],
  },
  draft_inspections: [
    {
      id: 'DI-0042',
      draft_id: 'GN-0042',
      title: 'CPI print as a hook: data sufficiency, not a call',
      source_lineage: [
        { id: 'LIN-A', label: 'BLS CPI release (official source) \u2192 REF-8830' },
        { id: 'LIN-B', label: 'Methodology note \u2192 CIT-2 (pending verify)' },
        { id: 'LIN-C', label: 'Editorial draft GN-0042 (local working copy)' },
      ],
      citation_checks: [
        { id: 'CC-1', label: 'Primary source cited', source_ref: 'CIT-1', status: 'verified', detail: 'BLS CPI release linked to claim.' },
        { id: 'CC-2', label: 'Methodology note verified', source_ref: 'CIT-2', status: 'review', detail: 'Awaiting reviewer confirmation of methodology note.' },
        { id: 'CC-3', label: 'No uncited numeric claim', source_ref: '\u2014', status: 'verified', detail: 'No market number stated without a source.' },
      ],
      limitation_checks: [
        { id: 'LC-1', label: 'Limitation note present', status: 'verified', detail: 'Explicit "news is a hook, not a signal" caveat retained.' },
        { id: 'LC-2', label: 'No predictive claim', status: 'verified', detail: 'No forecast or price target language.' },
      ],
      claim_risk_items: [
        { id: 'CRI-1', label: 'Implied forecast authority', classification: 'Tone risk', severity: 'review', detail: 'Ensure framing stays explanatory, not directional.' },
        { id: 'CRI-2', label: 'Unsupported numeric market claim', classification: 'Evidence risk', severity: 'review', detail: 'Any number must trace to an official source.' },
        { id: 'CRI-3', label: 'Signal/advice language', classification: 'Policy risk', severity: 'verified', detail: 'No buy/sell/hold or signal phrasing detected.' },
      ],
      no_signal_checks: [
        { id: 'NS-1', label: 'No buy/sell/hold language', status: 'verified', detail: 'Forbidden directive terms absent.' },
        { id: 'NS-2', label: 'No price target / level call', status: 'verified', detail: 'No numeric target asserted.' },
        { id: 'NS-3', label: 'No financial advice phrasing', status: 'verified', detail: 'Advice-form sentences absent.' },
      ],
      artifact_eligibility_checks: [
        { id: 'AE-1', label: 'Lane C artifact intake', status: 'blocked', detail: 'No approved artifact spec/export gate yet.' },
        { id: 'AE-2', label: 'Lineage manifest + checksum', status: 'blocked', detail: 'Required before artifact-backed eligibility.' },
      ],
      approval_readiness: 'Not ready \u2014 1 citation pending, artifact intake blocked',
      approval_readiness_status: 'review',
      human_review_required: true,
      publish_ready: false,
    },
  ],
  platform_payload_previews: [
    {
      id: 'PP-X',
      platform: 'X',
      platform_key: 'x',
      source_draft_id: 'GN-0042',
      format_label: 'Single post · text + optional card',
      fit_status: 'review',
      fit_summary: 'Within length. Trim one hashtag for best fit.',
      fields: [
        { id: 'X-body', label: 'Post body', value: 'A CPI print is context, not a command. What it can and cannot tell you, in plain terms. News is a hook, not a signal. Not financial advice.' },
        { id: 'X-hashtags', label: 'Hashtags', value: '#CPI #inflation #dataliteracy', mono: true },
        { id: 'X-link', label: 'Link card', value: '(local fixture · no live URL)', mono: true },
      ],
      constraints: [
        { id: 'X-c1', label: 'Body length', limit: '280 chars', actual: '171 chars', status: 'verified', detail: 'Under the post character limit.' },
        { id: 'X-c2', label: 'Hashtag count', limit: '≤ 3 recommended', actual: '3', status: 'review', detail: 'At the recommended ceiling; consider trimming.' },
        { id: 'X-c3', label: 'Media ratio', limit: '16:9 preferred', actual: '16:9 (mock)', status: 'verified', detail: 'Mock card matches preferred aspect ratio.' },
      ],
      media_note: 'Mock card only · no upload, no media API.',
      live_status: 'LIVE_DISABLED',
      credential_status: 'NO_CREDENTIAL_READ',
      provider_status: 'NO_PROVIDER_CALL',
      not_dispatchable_reason: 'Dry-run preview only. No platform API, no credential, no posting.',
      dispatchable: false,
    },
    {
      id: 'PP-LinkedIn',
      platform: 'LinkedIn',
      platform_key: 'linkedin',
      source_draft_id: 'GN-0042',
      format_label: 'Single share · professional framing',
      fit_status: 'verified',
      fit_summary: 'Well within limits. Analytical tone suits the audience.',
      fields: [
        { id: 'LI-body', label: 'Share text', value: 'Today\u2019s CPI print is a useful teaching moment, not a market call. Here is how we read official data without implying a forecast. Context, not a command. Not financial advice.' },
        { id: 'LI-hashtags', label: 'Hashtags', value: '#macro #CPI #dataliteracy', mono: true },
        { id: 'LI-title', label: 'Headline', value: 'CPI is a hook, not a signal' },
      ],
      constraints: [
        { id: 'LI-c1', label: 'Body length', limit: '3,000 chars', actual: '188 chars', status: 'verified', detail: 'Far under the share limit.' },
        { id: 'LI-c2', label: 'Hashtag count', limit: '≤ 5 recommended', actual: '3', status: 'verified', detail: 'Within recommended range.' },
        { id: 'LI-c3', label: 'Media size', limit: '1200x627', actual: '1200x627 (mock)', status: 'verified', detail: 'Mock image matches recommended size.' },
      ],
      media_note: 'Mock image only · no upload, no media API.',
      live_status: 'LIVE_DISABLED',
      credential_status: 'NO_CREDENTIAL_READ',
      provider_status: 'NO_PROVIDER_CALL',
      not_dispatchable_reason: 'Dry-run preview only. No platform API, no credential, no posting.',
      dispatchable: false,
    },
    {
      id: 'PP-Threads',
      platform: 'Threads',
      platform_key: 'threads',
      source_draft_id: 'GN-0042',
      format_label: 'Single post · conversational',
      fit_status: 'verified',
      fit_summary: 'Within length. 1:1 media preferred.',
      fields: [
        { id: 'TH-body', label: 'Post body', value: 'The number matters less than what it can and cannot tell you. A CPI print is context, not a call. News is a hook, not a signal.' },
        { id: 'TH-hashtags', label: 'Hashtags', value: '#CPI #inflation', mono: true },
      ],
      constraints: [
        { id: 'TH-c1', label: 'Body length', limit: '500 chars', actual: '128 chars', status: 'verified', detail: 'Under the post character limit.' },
        { id: 'TH-c2', label: 'Media ratio', limit: '1:1 preferred', actual: '1:1 (mock)', status: 'verified', detail: 'Mock image matches preferred aspect ratio.' },
        { id: 'TH-c3', label: 'Reply chain', limit: 'optional', actual: 'none', status: 'neutral', detail: 'No reply chain in this fixture.' },
      ],
      media_note: 'Mock image only · no upload, no media API.',
      live_status: 'LIVE_DISABLED',
      credential_status: 'NO_CREDENTIAL_READ',
      provider_status: 'NO_PROVIDER_CALL',
      not_dispatchable_reason: 'Dry-run preview only. No platform API, no credential, no posting.',
      dispatchable: false,
    },
    {
      id: 'PP-Substack',
      platform: 'Substack',
      platform_key: 'substack',
      source_draft_id: 'GN-0042',
      format_label: 'Newsletter issue · long-form',
      fit_status: 'verified',
      fit_summary: 'Long-form body fits. Subject line within limit.',
      fields: [
        { id: 'SB-subject', label: 'Subject line', value: 'What a CPI print actually measures' },
        { id: 'SB-body', label: 'Issue body', value: 'In this issue we walk through what a CPI release measures, why revisions happen, and why a single print is rarely sufficient to support a forecast. Context, not a call. Not financial advice.' },
        { id: 'SB-footer', label: 'Footer note', value: 'News is a hook, not a signal. No buy/sell/hold guidance.' },
      ],
      constraints: [
        { id: 'SB-c1', label: 'Subject length', limit: '≤ 100 chars', actual: '34 chars', status: 'verified', detail: 'Under the subject line limit.' },
        { id: 'SB-c2', label: 'Body length', limit: 'no hard limit', actual: '195 chars (excerpt)', status: 'verified', detail: 'Excerpt shown; full issue is long-form.' },
        { id: 'SB-c3', label: 'Footer disclaimer', limit: 'required', actual: 'present', status: 'verified', detail: 'No-signal disclaimer retained.' },
      ],
      media_note: 'Mock header image only · no upload, no media API.',
      live_status: 'LIVE_DISABLED',
      credential_status: 'NO_CREDENTIAL_READ',
      provider_status: 'NO_PROVIDER_CALL',
      not_dispatchable_reason: 'Dry-run preview only. No platform API, no credential, no posting.',
      dispatchable: false,
    },
    {
      id: 'PP-Telegram',
      platform: 'Telegram',
      platform_key: 'telegram',
      source_draft_id: 'GN-0042',
      format_label: 'Channel message · markdown',
      fit_status: 'verified',
      fit_summary: 'Within message length. Markdown preserved.',
      fields: [
        { id: 'TG-body', label: 'Message body', value: '*CPI print:* context, not a call. How we read official data without implying a forecast. News is a hook, not a signal. _Not financial advice._' },
        { id: 'TG-link', label: 'Preview link', value: '(local fixture · no live URL)', mono: true },
      ],
      constraints: [
        { id: 'TG-c1', label: 'Message length', limit: '4,096 chars', actual: '142 chars', status: 'verified', detail: 'Far under the message limit.' },
        { id: 'TG-c2', label: 'Markdown', limit: 'MarkdownV2', actual: 'valid (mock)', status: 'verified', detail: 'Mock markdown parses cleanly.' },
        { id: 'TG-c3', label: 'Link preview', limit: 'optional', actual: 'disabled', status: 'neutral', detail: 'No live link preview in dry-run.' },
      ],
      media_note: 'Mock attachment only · no upload, no Bot API.',
      live_status: 'LIVE_DISABLED',
      credential_status: 'NO_CREDENTIAL_READ',
      provider_status: 'NO_PROVIDER_CALL',
      not_dispatchable_reason: 'Dry-run preview only. No Bot API, no token read, no posting.',
      dispatchable: false,
    },
    {
      id: 'PP-Facebook',
      platform: 'Facebook',
      platform_key: 'facebook',
      source_draft_id: 'GN-0042',
      format_label: 'Page post · text + link card',
      fit_status: 'review',
      fit_summary: 'Within length. Consider a shorter lead line.',
      fields: [
        { id: 'FB-body', label: 'Post body', value: 'A CPI print is context, not a command. Here is how we read official data without implying a forecast. News is a hook, not a signal. Not financial advice.' },
        { id: 'FB-link', label: 'Link card', value: '(local fixture · no live URL)', mono: true },
      ],
      constraints: [
        { id: 'FB-c1', label: 'Body length', limit: '63,206 chars', actual: '156 chars', status: 'verified', detail: 'Far under the post limit.' },
        { id: 'FB-c2', label: 'Lead visibility', limit: '~ 80 chars before fold', actual: '156 chars', status: 'review', detail: 'Lead line longer than the visible fold.' },
        { id: 'FB-c3', label: 'Media size', limit: '1200x630', actual: '1200x630 (mock)', status: 'verified', detail: 'Mock image matches recommended size.' },
      ],
      media_note: 'Mock image only · no upload, no Graph API.',
      live_status: 'LIVE_DISABLED',
      credential_status: 'NO_CREDENTIAL_READ',
      provider_status: 'NO_PROVIDER_CALL',
      not_dispatchable_reason: 'Dry-run preview only. No Graph API, no credential, no posting.',
      dispatchable: false,
    },
    {
      id: 'PP-Instagram',
      platform: 'Instagram',
      platform_key: 'instagram',
      source_draft_id: 'GN-0042',
      format_label: 'Single image · caption',
      fit_status: 'review',
      fit_summary: 'Caption fits. Media is required for this format.',
      fields: [
        { id: 'IG-caption', label: 'Caption', value: 'A CPI print is context, not a command. News is a hook, not a signal. Not financial advice. (Educational, not a call.)' },
        { id: 'IG-hashtags', label: 'Hashtags', value: '#CPI #inflation #macro #dataliteracy', mono: true },
      ],
      constraints: [
        { id: 'IG-c1', label: 'Caption length', limit: '2,200 chars', actual: '117 chars', status: 'verified', detail: 'Under the caption limit.' },
        { id: 'IG-c2', label: 'Hashtag count', limit: '≤ 30', actual: '4', status: 'verified', detail: 'Well within the hashtag ceiling.' },
        { id: 'IG-c3', label: 'Media required', limit: '1 image min', actual: '1 (mock)', status: 'review', detail: 'Mock image present; real media required for this format.' },
      ],
      media_note: 'Mock image only · no upload, no Graph API.',
      live_status: 'LIVE_DISABLED',
      credential_status: 'NO_CREDENTIAL_READ',
      provider_status: 'NO_PROVIDER_CALL',
      not_dispatchable_reason: 'Dry-run preview only. No Graph API, no credential, no posting.',
      dispatchable: false,
    },
    {
      id: 'PP-TikTok',
      platform: 'TikTok',
      platform_key: 'tiktok',
      source_draft_id: 'GN-0042',
      format_label: 'Video caption · script note',
      fit_status: 'blocked',
      fit_summary: 'Caption fits, but no video asset exists in this fixture.',
      fields: [
        { id: 'TT-caption', label: 'Caption', value: 'How to read a CPI print without making a call. News is a hook, not a signal. Not financial advice.' },
        { id: 'TT-hashtags', label: 'Hashtags', value: '#CPI #macro #learnontiktok', mono: true },
        { id: 'TT-script', label: 'Script note', value: '(local fixture · no video asset)', mono: true },
      ],
      constraints: [
        { id: 'TT-c1', label: 'Caption length', limit: '2,200 chars', actual: '98 chars', status: 'verified', detail: 'Under the caption limit.' },
        { id: 'TT-c2', label: 'Hashtag count', limit: '≤ 5 recommended', actual: '3', status: 'verified', detail: 'Within recommended range.' },
        { id: 'TT-c3', label: 'Video required', limit: 'video asset required', actual: 'none', status: 'blocked', detail: 'No video asset in this fixture; format cannot be assembled.' },
      ],
      media_note: 'No video asset · mock-only surface, no upload, no Content API.',
      live_status: 'LIVE_DISABLED',
      credential_status: 'NO_CREDENTIAL_READ',
      provider_status: 'NO_PROVIDER_CALL',
      not_dispatchable_reason: 'Dry-run preview only. No Content API, no credential, no posting.',
      dispatchable: false,
    },
  ],
  manual_publish_records: [
    {
      id: 'MP-X-0042',
      platform: 'X',
      platform_key: 'x',
      source_draft_id: 'GN-0042',
      payload_ref: 'PP-X',
      payload_hash: 'sha256:1b77…aa90',
      approval_packet_ref: 'AP-0031',
      approval_packet_hash: 'sha256:9f2a…c4e1',
      stage: 'approved_for_manual',
      stage_label: 'Approved for manual',
      stage_status: 'verified',
      manual_url: '',
      published_at: '',
      checklist: [
        { id: 'MP-X-ck1', label: 'Approval packet signed', status: 'verified', detail: 'AP-0031 signature present in local fixture.' },
        { id: 'MP-X-ck2', label: 'Payload hash matches preview', status: 'verified', detail: 'Local payload hash matches PP-X.' },
        { id: 'MP-X-ck3', label: 'No-signal language check', status: 'review', detail: 'Operator must reconfirm before manual post.' },
        { id: 'MP-X-ck4', label: 'Operator posted off-platform by hand', status: 'neutral', detail: 'Not yet posted. Manual action only.' },
      ],
      metrics: [],
      audit_state: 'Awaiting manual post',
      audit_status: 'review',
      caveat: 'Operator posts by hand off-platform. This screen only records what a human did.',
      blocked_reason: '',
      live_status: 'MANUAL_ONLY',
      platform_api_status: 'NO_PLATFORM_API',
      credential_status: 'NO_CREDENTIAL_READ',
      scheduler_status: 'NO_SCHEDULER',
      autonomous_status: 'NO_AUTONOMOUS_POSTING',
      metrics_status: 'METRICS_MANUAL_ENTRY_ONLY',
      review_status: 'HUMAN_REVIEW_REQUIRED',
      can_post_live: false,
    },
    {
      id: 'MP-LI-0042',
      platform: 'LinkedIn',
      platform_key: 'linkedin',
      source_draft_id: 'GN-0042',
      payload_ref: 'PP-LinkedIn',
      payload_hash: 'sha256:3c10…bd42',
      approval_packet_ref: 'AP-0031',
      approval_packet_hash: 'sha256:9f2a…c4e1',
      stage: 'manually_posted',
      stage_label: 'Manually posted',
      stage_status: 'verified',
      manual_url: 'https://example.invalid/linkedin/local-mock-post-0042',
      published_at: '2026-06-15T08:40:00+07:00',
      checklist: [
        { id: 'MP-LI-ck1', label: 'Approval packet signed', status: 'verified', detail: 'AP-0031 signature present.' },
        { id: 'MP-LI-ck2', label: 'Payload hash matches preview', status: 'verified', detail: 'Matches PP-LinkedIn.' },
        { id: 'MP-LI-ck3', label: 'No-signal language check', status: 'verified', detail: 'Reconfirmed before manual post.' },
        { id: 'MP-LI-ck4', label: 'Operator posted off-platform by hand', status: 'verified', detail: 'Recorded mock URL + timestamp.' },
      ],
      metrics: [],
      audit_state: 'Manually posted · metrics pending',
      audit_status: 'review',
      caveat: 'Manual URL is a local mock string. It is never fetched or validated against any platform.',
      blocked_reason: '',
      live_status: 'MANUAL_ONLY',
      platform_api_status: 'NO_PLATFORM_API',
      credential_status: 'NO_CREDENTIAL_READ',
      scheduler_status: 'NO_SCHEDULER',
      autonomous_status: 'NO_AUTONOMOUS_POSTING',
      metrics_status: 'METRICS_MANUAL_ENTRY_ONLY',
      review_status: 'HUMAN_REVIEW_REQUIRED',
      can_post_live: false,
    },
    {
      id: 'MP-TG-0042',
      platform: 'Telegram',
      platform_key: 'telegram',
      source_draft_id: 'GN-0042',
      payload_ref: 'PP-Telegram',
      payload_hash: 'sha256:7e21…0f3a',
      approval_packet_ref: 'AP-0031',
      approval_packet_hash: 'sha256:9f2a…c4e1',
      stage: 'metrics_entered',
      stage_label: 'Metrics entered',
      stage_status: 'verified',
      manual_url: 'https://example.invalid/t/local-mock-channel/512',
      published_at: '2026-06-14T19:05:00+07:00',
      checklist: [
        { id: 'MP-TG-ck1', label: 'Approval packet signed', status: 'verified', detail: 'AP-0031 signature present.' },
        { id: 'MP-TG-ck2', label: 'Payload hash matches preview', status: 'verified', detail: 'Matches PP-Telegram.' },
        { id: 'MP-TG-ck3', label: 'No-signal language check', status: 'verified', detail: 'Reconfirmed before manual post.' },
        { id: 'MP-TG-ck4', label: 'Operator posted off-platform by hand', status: 'verified', detail: 'Recorded mock URL + timestamp.' },
        { id: 'MP-TG-ck5', label: 'Metrics snapshot entered by hand', status: 'verified', detail: 'One manual snapshot recorded.' },
      ],
      metrics: [
        { id: 'MP-TG-m1', captured_at: '2026-06-15T08:00:00+07:00', impressions: 1840, likes: 73, comments: 11, shares: 9, saves: 4, click_count: 38, notes: 'Manual snapshot, ~12h after post. Typed in by operator.', source: 'MANUAL_ENTRY' },
      ],
      audit_state: 'Manual metrics recorded',
      audit_status: 'verified',
      caveat: 'All metrics are manually entered. No metrics API, no sync, no fetch.',
      blocked_reason: '',
      live_status: 'MANUAL_ONLY',
      platform_api_status: 'NO_PLATFORM_API',
      credential_status: 'NO_CREDENTIAL_READ',
      scheduler_status: 'NO_SCHEDULER',
      autonomous_status: 'NO_AUTONOMOUS_POSTING',
      metrics_status: 'METRICS_MANUAL_ENTRY_ONLY',
      review_status: 'HUMAN_REVIEW_REQUIRED',
      can_post_live: false,
    },
    {
      id: 'MP-TT-0042',
      platform: 'TikTok',
      platform_key: 'tiktok',
      source_draft_id: 'GN-0042',
      payload_ref: 'PP-TikTok',
      payload_hash: 'sha256:aa56…91cd',
      approval_packet_ref: 'AP-0031',
      approval_packet_hash: 'sha256:9f2a…c4e1',
      stage: 'blocked',
      stage_label: 'Blocked',
      stage_status: 'blocked',
      manual_url: '',
      published_at: '',
      checklist: [
        { id: 'MP-TT-ck1', label: 'Approval packet signed', status: 'verified', detail: 'AP-0031 signature present.' },
        { id: 'MP-TT-ck2', label: 'Video asset present', status: 'blocked', detail: 'No video asset in this fixture; cannot manually post.' },
        { id: 'MP-TT-ck3', label: 'No-signal language check', status: 'neutral', detail: 'Deferred until asset exists.' },
      ],
      metrics: [],
      audit_state: 'Blocked — missing video asset',
      audit_status: 'blocked',
      caveat: 'Blocked candidates cannot be manually posted until their blocker clears.',
      blocked_reason: 'No video asset exists for this fixture; the TikTok format cannot be assembled or manually posted.',
      live_status: 'MANUAL_ONLY',
      platform_api_status: 'NO_PLATFORM_API',
      credential_status: 'NO_CREDENTIAL_READ',
      scheduler_status: 'NO_SCHEDULER',
      autonomous_status: 'NO_AUTONOMOUS_POSTING',
      metrics_status: 'METRICS_MANUAL_ENTRY_ONLY',
      review_status: 'HUMAN_REVIEW_REQUIRED',
      can_post_live: false,
    },
  ],
  approval_packets: [
    {
      id: 'AP-0031',
      title: 'CPI hook explainer — manual approval packet',
      required_approver: 'Jim',
      draft_hash: 'sha256:9f2a…c4e1',
      payload_hash: 'sha256:1b77…aa90',
      approval_state: 'Awaiting signature',
      approval_status: 'review',
      revocation_state: 'none',
      redacted_audit_state: 'ready',
      risk_state: 'review',
      evidence_sources: ['REF-8830', 'CIT-1', 'CIT-2'],
      comments: [{ author: 'Jim', note: 'Hold until citation CIT-2 verified.' }],
      gates: [
        { id: 'GATE-approval', label: 'Approval ledger', status: 'review', cleared: false, detail: 'Signature pending.' },
        { id: 'GATE-payload', label: 'Payload hash match', status: 'verified', cleared: true, detail: 'Hash matches draft.' },
        { id: 'GATE-guardrail', label: 'Guardrail pass', status: 'review', cleared: false, detail: 'No-signal check pending.' },
        { id: 'GATE-kill', label: 'Kill switch', status: 'neutral', cleared: false, detail: 'Armed. Dispatch globally disabled.' },
        { id: 'GATE-cred', label: 'Credential slot', status: 'neutral', cleared: false, detail: 'Empty by policy. No credential read.' },
        { id: 'GATE-live', label: 'Platform live gate', status: 'blocked', cleared: false, detail: 'No platform API. Future-gated.' },
        { id: 'GATE-audit', label: 'Redacted audit ready', status: 'verified', cleared: true, detail: 'Audit trail prepared.' },
        { id: 'GATE-rollback', label: 'Rollback / manual fallback', status: 'verified', cleared: true, detail: 'Manual-only fallback.' },
      ],
      dispatch_enabled: false,
    },
  ],
  evidence_packets: [
    {
      id: 'EV-0174BZ',
      task_label: 'TASK_CONTENTOPS_0174BZ_V5_FRONTEND_SCAFFOLD_AND_DESIGN_SYSTEM_FOUNDATION_V0',
      result: 'verified',
      result_label: 'Foundation shipped',
      commit_ref: 'commit@pending',
      timestamp: '2026-06-15T09:22:00+07:00',
      validation_matrix: [
        { id: 'VM-1', label: 'V5 app builds', status: 'verified', detail: 'vite build passes.' },
        { id: 'VM-2', label: '5 flagship views', status: 'verified', detail: 'All present.' },
        { id: 'VM-3', label: 'Light + dark evidence mode', status: 'verified', detail: 'Theme tokens wired.' },
        { id: 'VM-4', label: 'No runtime CDN/remote font', status: 'verified', detail: 'Bundled assets only.' },
        { id: 'VM-5', label: 'No network/credential/platform API', status: 'verified', detail: 'Static scan clean.' },
      ],
      forbidden_scope: [
        { id: 'FS-1', label: 'Runtime network/fetch', status: 'verified' },
        { id: 'FS-2', label: 'localStorage/sessionStorage', status: 'verified' },
        { id: 'FS-3', label: 'Platform/provider API', status: 'verified' },
        { id: 'FS-4', label: 'Credential/env read', status: 'verified' },
      ],
      secret_scan: { label: 'Secret scan', status: 'verified', detail: 'No secrets in V5 source.' },
      provenance_chips: ['local-fixture', 'build-time-only', 'no-network', 'no-credentials'],
      source_lineage: [
        { id: 'LIN-1', label: 'V5 master plan @342fc91' },
        { id: 'LIN-2', label: 'Stitch v5.1 references (reference-only)' },
      ],
    },
  ],
  audit_events: [
    { id: 'AE-1', timestamp: '2026-06-15T09:00:00+07:00', actor: 'operator', action: 'Committed V5 master plan + references', ref: '342fc91' },
    { id: 'AE-2', timestamp: '2026-06-15T09:22:00+07:00', actor: 'agent', action: 'Scaffolded V5 frontend foundation', ref: 'pending' },
  ],
  policy_boundaries: [
    { id: 'PB-1', label: 'Local-only mode', status: 'verified', detail: 'No backend, no runtime network.' },
    { id: 'PB-2', label: 'Credential policy', status: 'verified', detail: 'No credential/env read. .env never accessed.' },
    { id: 'PB-3', label: 'No-advice policy', status: 'verified', detail: 'No financial advice or signals.' },
    { id: 'PB-4', label: 'AI provider gate', status: 'neutral', detail: 'LLM provider disabled until explicit task.' },
    { id: 'PB-5', label: 'Internal alpha intake gate', status: 'blocked', detail: 'Artifact intake not available yet.' },
  ],
  internal_alpha_artifacts: [
    {
      id: 'IA-PLACEHOLDER-1',
      artifact_type: 'forecast_readiness_artifact',
      intake_status: 'blocked',
      intake_label: 'Intake blocked',
      reason_blocked: 'No approved artifact spec, export location, or readiness gate exists yet.',
    },
    {
      id: 'IA-PLACEHOLDER-2',
      artifact_type: 'data_sufficiency_artifact',
      intake_status: 'blocked',
      intake_label: 'Intake blocked',
      reason_blocked: 'Awaiting lineage manifest + checksum contract.',
    },
  ],
};
