"""Tests for scd_provider_gateway_dry_run (0174BA).

Provider-gateway DRY-RUN facade contract. Local-only, fail-closed. No network,
no provider/LLM API, no credentials/env, no API keys, no client construction, no
platform API, no browser, no live dispatch. Fixtures are generated by the repo's
own validator-asserted generator and committed under
fixtures/scd_provider_gateway_dry_run/.
"""
import copy
import json
import os

import pytest

from live_contentops.scd_provider_gateway_dry_run import (
    validate_provider_gateway_dry_run_input,
    validate_provider_gateway_call_plan,
    validate_provider_gateway_spend_ledger_entry,
    validate_provider_gateway_dry_run_result,
    validate_provider_gateway_gate_report,
    build_provider_gateway_call_plan,
    build_spend_ledger_entry,
    build_provider_gateway_dry_run_result,
    PROVIDER_GATEWAY_DRY_RUN_VALIDATORS,
    FORBIDDEN_FALSE_FLAGS,
    FORBIDDEN_READY_FLAGS,
    REQUIRED_SPEND_FIELDS,
    VALID_OPERATIONS,
)

FIXTURE_DIR = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "fixtures",
    "scd_provider_gateway_dry_run",
)

MODULE_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "live_contentops",
    "scd_provider_gateway_dry_run.py",
)

# Fixture filename -> (validator registry key, expected validation_state).
EXPECTED = {
    "input_canonical_pass.json": ("provider_gateway_dry_run_input", "PASS"),
    "input_repair_pass.json": ("provider_gateway_dry_run_input", "PASS"),
    "call_plan_canonical_pass.json": ("provider_gateway_call_plan", "PASS"),
    "spend_ledger_entry_pass.json": ("provider_gateway_spend_ledger_entry", "PASS"),
    "dry_run_result_pass.json": ("provider_gateway_dry_run_result", "PASS"),
    "gate_report_pass.json": ("provider_gateway_gate_report", "PASS"),
    "input_blocked_quota_not_pass.json": ("provider_gateway_dry_run_input", "BLOCKED"),
    "input_blocked_prompt_pack_not_pass.json": ("provider_gateway_dry_run_input", "BLOCKED"),
    "input_blocked_canonical_attempt.json": ("provider_gateway_dry_run_input", "BLOCKED"),
    "input_blocked_repair_attempt.json": ("provider_gateway_dry_run_input", "BLOCKED"),
    "call_plan_blocked_executable.json": ("provider_gateway_call_plan", "BLOCKED"),
    "input_blocked_provider_flags.json": ("provider_gateway_dry_run_input", "BLOCKED"),
    "input_blocked_env_read.json": ("provider_gateway_dry_run_input", "BLOCKED"),
    "input_blocked_api_key.json": ("provider_gateway_dry_run_input", "BLOCKED"),
    "input_blocked_spend_missing.json": ("provider_gateway_dry_run_input", "BLOCKED"),
    "input_blocked_retry_loop.json": ("provider_gateway_dry_run_input", "BLOCKED"),
    "input_blocked_platform_variants.json": ("provider_gateway_dry_run_input", "BLOCKED"),
    "input_unknown_cache_missing.json": ("provider_gateway_dry_run_input", "UNKNOWN"),
    "input_review_cache_stale.json": ("provider_gateway_dry_run_input", "REVIEW_REQUIRED"),
}


def _load(name):
    with open(os.path.join(FIXTURE_DIR, name), encoding="utf-8") as fh:
        return json.load(fh)


def _input():
    return _load("input_canonical_pass.json")


def _repair_input():
    return _load("input_repair_pass.json")


def _call_plan():
    return _load("call_plan_canonical_pass.json")


def _spend():
    return _load("spend_ledger_entry_pass.json")


def _result():
    return _load("dry_run_result_pass.json")


def _report():
    return _load("gate_report_pass.json")


# --- Fixture-driven validation-state coverage ---

@pytest.mark.parametrize("name,spec", sorted(EXPECTED.items()))
def test_fixture_validation_state(name, spec):
    key, expected = spec
    payload = _load(name)
    result = PROVIDER_GATEWAY_DRY_RUN_VALIDATORS[key](payload)
    assert result["validation_state"] == expected, (name, result["reasons"])


def test_all_fixtures_covered():
    on_disk = {f for f in os.listdir(FIXTURE_DIR) if f.endswith(".json")}
    assert on_disk == set(EXPECTED), on_disk.symmetric_difference(EXPECTED)


def test_all_four_states_present():
    states = {state for _, state in EXPECTED.values()}
    assert states == {"PASS", "BLOCKED", "REVIEW_REQUIRED", "UNKNOWN"}


def test_registry_exposes_all_validators():
    assert set(PROVIDER_GATEWAY_DRY_RUN_VALIDATORS) == {
        "provider_gateway_dry_run_input",
        "provider_gateway_call_plan",
        "provider_gateway_spend_ledger_entry",
        "provider_gateway_dry_run_result",
        "provider_gateway_gate_report",
    }


# --- Quota policy + prompt pack PASS required ---

def test_quota_policy_must_be_pass():
    pkt = _input()
    pkt["quota_policy_summary"]["validation_state"] = "REVIEW_REQUIRED"
    assert validate_provider_gateway_dry_run_input(pkt)["validation_state"] == "BLOCKED"


def test_quota_policy_missing_blocks():
    pkt = _input()
    pkt.pop("quota_policy_summary", None)
    assert validate_provider_gateway_dry_run_input(pkt)["validation_state"] == "BLOCKED"


def test_quota_policy_generation_attempts_must_be_one():
    pkt = _input()
    pkt["quota_policy_summary"]["max_generation_attempts"] = 2
    assert validate_provider_gateway_dry_run_input(pkt)["validation_state"] == "BLOCKED"


def test_prompt_pack_must_be_pass():
    pkt = _input()
    pkt["prompt_pack_summary"]["validation_state"] = "BLOCKED"
    assert validate_provider_gateway_dry_run_input(pkt)["validation_state"] == "BLOCKED"


def test_prompt_pack_missing_blocks():
    pkt = _input()
    pkt.pop("prompt_pack_summary", None)
    assert validate_provider_gateway_dry_run_input(pkt)["validation_state"] == "BLOCKED"


# --- Attempt enforcement ---

def test_canonical_attempt_index_must_be_one():
    pkt = _input()
    pkt["attempt_index"] = 2
    assert validate_provider_gateway_dry_run_input(pkt)["validation_state"] == "BLOCKED"


def test_canonical_prior_attempt_must_be_zero():
    pkt = _input()
    pkt["prior_attempt_count"] = 1
    assert validate_provider_gateway_dry_run_input(pkt)["validation_state"] == "BLOCKED"


def test_repair_attempt_index_bounded():
    pkt = _repair_input()
    pkt["attempt_index"] = 2
    assert validate_provider_gateway_dry_run_input(pkt)["validation_state"] == "BLOCKED"


def test_repair_prior_attempt_bounded():
    pkt = _repair_input()
    pkt["prior_attempt_count"] = 2
    assert validate_provider_gateway_dry_run_input(pkt)["validation_state"] == "BLOCKED"


def test_invalid_operation_blocks():
    pkt = _input()
    pkt["requested_operation"] = "platform_variant_expansion"
    assert validate_provider_gateway_dry_run_input(pkt)["validation_state"] == "BLOCKED"


# --- Forbidden-false flags + ready flags must never be true ---

@pytest.mark.parametrize("flag", FORBIDDEN_FALSE_FLAGS)
def test_forbidden_false_flags_block(flag):
    pkt = _input()
    pkt[flag] = True
    assert validate_provider_gateway_dry_run_input(pkt)["validation_state"] == "BLOCKED"


@pytest.mark.parametrize("flag", FORBIDDEN_READY_FLAGS)
def test_ready_flags_block(flag):
    pkt = _input()
    pkt[flag] = True
    assert validate_provider_gateway_dry_run_input(pkt)["validation_state"] == "BLOCKED"


# --- Spend estimate + cache key required ---

@pytest.mark.parametrize("field", ["estimated_input_tokens", "estimated_output_tokens", "estimated_cost"])
def test_spend_estimate_required(field):
    pkt = _input()
    pkt.pop(field, None)
    assert validate_provider_gateway_dry_run_input(pkt)["validation_state"] == "BLOCKED"


def test_cache_key_missing_is_unknown():
    pkt = _input()
    pkt.pop("prompt_pack_cache_key", None)
    assert validate_provider_gateway_dry_run_input(pkt)["validation_state"] == "UNKNOWN"


# --- Retry-loop language + platform variants forbidden ---

@pytest.mark.parametrize("phrase", [
    "retry until success",
    "generate until pass",
    "auto-regenerate the draft",
    "full rewrite loop",
])
def test_retry_loop_language_blocks(phrase):
    pkt = _input()
    pkt["operator_context_ref"] = phrase
    assert validate_provider_gateway_dry_run_input(pkt)["validation_state"] == "BLOCKED"


def test_platform_variants_forbidden():
    pkt = _input()
    pkt["prompt_pack_summary"]["platform_variants_requested"] = True
    assert validate_provider_gateway_dry_run_input(pkt)["validation_state"] == "BLOCKED"


# --- Call plan / result: non-executable, dry-run-only ---

def test_call_plan_executable_true_blocks():
    plan = _call_plan()
    plan["executable"] = True
    assert validate_provider_gateway_call_plan(plan)["validation_state"] == "BLOCKED"


def test_call_plan_dry_run_only_false_blocks():
    plan = _call_plan()
    plan["dry_run_only"] = False
    assert validate_provider_gateway_call_plan(plan)["validation_state"] == "BLOCKED"


@pytest.mark.parametrize("flag", FORBIDDEN_FALSE_FLAGS)
def test_call_plan_forbidden_flags_block(flag):
    plan = _call_plan()
    plan[flag] = True
    assert validate_provider_gateway_call_plan(plan)["validation_state"] == "BLOCKED"


def test_result_executable_true_blocks():
    res = _result()
    res["executable"] = True
    assert validate_provider_gateway_dry_run_result(res)["validation_state"] == "BLOCKED"


@pytest.mark.parametrize("flag", FORBIDDEN_READY_FLAGS)
def test_result_ready_flags_block(flag):
    res = _result()
    res[flag] = True
    assert validate_provider_gateway_dry_run_result(res)["validation_state"] == "BLOCKED"


# --- Spend ledger: every estimate/lineage field required ---

@pytest.mark.parametrize("field", REQUIRED_SPEND_FIELDS)
def test_spend_ledger_field_required(field):
    spend = _spend()
    spend.pop(field, None)
    assert validate_provider_gateway_spend_ledger_entry(spend)["validation_state"] == "BLOCKED"


def test_spend_ledger_actual_cost_blocks():
    spend = _spend()
    spend["actual_cost"] = 1.23
    assert validate_provider_gateway_spend_ledger_entry(spend)["validation_state"] == "BLOCKED"


def test_spend_ledger_negative_estimate_blocks():
    spend = _spend()
    spend["estimated_cost"] = -1
    assert validate_provider_gateway_spend_ledger_entry(spend)["validation_state"] == "BLOCKED"


# --- Helper builds a SAFE, non-executable plan ---

def test_helper_builds_non_executable_call_plan():
    plan = build_provider_gateway_call_plan(_input())
    assert plan["executable"] is False
    assert plan["dry_run_only"] is True
    for flag in FORBIDDEN_FALSE_FLAGS:
        assert plan.get(flag) is False, flag
    assert validate_provider_gateway_call_plan(plan)["validation_state"] == "PASS"


def test_helper_result_never_provider_live_public_ready():
    ci = _input()
    plan = build_provider_gateway_call_plan(ci)
    spend = build_spend_ledger_entry(ci, plan)
    result = build_provider_gateway_dry_run_result(ci, plan, spend)
    assert result["provider_ready"] is False
    assert result["live_ready"] is False
    assert result["public_ready"] is False
    assert result["executable"] is False
    assert result["dry_run_only"] is True
    assert validate_provider_gateway_dry_run_result(result)["validation_state"] == "PASS"


# --- Gate report: fail-closed rollup ---

def test_gate_report_blocked_subresult_forces_block():
    rep = _report()
    rep["call_plan_result"] = "BLOCKED"
    assert validate_provider_gateway_gate_report(rep)["validation_state"] == "BLOCKED"


def test_gate_report_pass_contradiction_blocks():
    rep = _report()
    rep["spend_ledger_result"] = "UNKNOWN"  # final still PASS -> contradiction
    assert validate_provider_gateway_gate_report(rep)["validation_state"] == "BLOCKED"


def test_gate_report_requires_operator_review():
    rep = _report()
    rep["operator_review_required"] = False
    assert validate_provider_gateway_gate_report(rep)["validation_state"] == "BLOCKED"


@pytest.mark.parametrize("flag", ["provider_ready", "live_ready", "public_ready"])
def test_gate_report_never_ready(flag):
    rep = _report()
    rep[flag] = True
    assert validate_provider_gateway_gate_report(rep)["validation_state"] == "BLOCKED"


# --- Static guard: no provider / network / env / client imports in the module ---

def test_module_has_no_provider_network_env_imports():
    with open(MODULE_PATH, encoding="utf-8") as fh:
        src = fh.read()
    forbidden = [
        "import requests",
        "import httpx",
        "import urllib",
        "import socket",
        "import openai",
        "import anthropic",
        "subprocess.",
        "os.environ",
        "os.getenv",
        "webbrowser",
    ]
    hits = [tok for tok in forbidden if tok in src]
    assert hits == [], hits
