"""Tests for scd_llm_quota_retry_policy (0174AY).

LLM quota / retry discipline policy contract. Local-only, deterministic,
fail-closed. No network, no provider/LLM API, no credentials/env, no UI runtime,
no browser, no screenshots, no live dispatch. Fixtures are generated by the
repo's own validator-asserted generator and committed under
fixtures/scd_llm_quota_retry_policy/.
"""
import copy
import json
import os

import pytest

from live_contentops.scd_llm_quota_retry_policy import (
    validate_llm_quota_retry_policy,
    LLM_QUOTA_RETRY_VALIDATORS,
    REQUIRED_TRUE_FLAGS,
    REQUIRED_FALSE_FLAGS,
    REQUIRED_CACHE_COMPONENTS,
    REQUIRED_SPEND_FIELDS,
    LOOP_LANGUAGE_PATTERNS,
)

FIXTURE_DIR = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "fixtures",
    "scd_llm_quota_retry_policy",
)

# Fixture filename -> expected validation_state.
EXPECTED_STATES = {
    "policy_pass.json": "PASS",
    "policy_blocked_infinite_retry.json": "BLOCKED",
    "policy_blocked_full_rewrite_loop.json": "BLOCKED",
    "policy_blocked_generation_attempts.json": "BLOCKED",
    "policy_blocked_repair_attempts.json": "BLOCKED",
    "policy_blocked_platform_variants.json": "BLOCKED",
    "policy_blocked_provider_network.json": "BLOCKED",
    "policy_blocked_missing_cache_key.json": "BLOCKED",
    "policy_blocked_missing_spend.json": "BLOCKED",
    "policy_blocked_loop_language.json": "BLOCKED",
    "policy_review_critique_no_budget.json": "REVIEW_REQUIRED",
    "policy_unknown_missing_cache_components.json": "UNKNOWN",
}


def _load(name):
    with open(os.path.join(FIXTURE_DIR, name), encoding="utf-8") as fh:
        return json.load(fh)


def _pass_policy():
    return _load("policy_pass.json")


# --- Fixture-driven validation-state coverage ---

@pytest.mark.parametrize("name,expected", sorted(EXPECTED_STATES.items()))
def test_fixture_validation_state(name, expected):
    payload = _load(name)
    result = validate_llm_quota_retry_policy(payload)
    assert result["validation_state"] == expected, (name, result["reasons"])


def test_all_fixtures_covered():
    on_disk = {f for f in os.listdir(FIXTURE_DIR) if f.endswith(".json")}
    assert on_disk == set(EXPECTED_STATES), on_disk.symmetric_difference(EXPECTED_STATES)


def test_all_four_states_present():
    states = set(EXPECTED_STATES.values())
    assert states == {"PASS", "BLOCKED", "REVIEW_REQUIRED", "UNKNOWN"}


def test_registry_exposes_validator():
    assert LLM_QUOTA_RETRY_VALIDATORS["llm_quota_retry_policy"] is validate_llm_quota_retry_policy


# --- Retry loop blockers ---

def test_infinite_retry_blocks():
    p = _pass_policy()
    p["allow_infinite_retry"] = True
    assert validate_llm_quota_retry_policy(p)["validation_state"] == "BLOCKED"


def test_full_rewrite_loop_flag_blocks():
    p = _pass_policy()
    p["allow_full_rewrite_loop"] = True
    assert validate_llm_quota_retry_policy(p)["validation_state"] == "BLOCKED"


def test_more_than_one_generation_blocks():
    p = _pass_policy()
    p["max_generation_attempts"] = 2
    assert validate_llm_quota_retry_policy(p)["validation_state"] == "BLOCKED"


def test_more_than_one_repair_blocks():
    p = _pass_policy()
    p["max_targeted_repair_attempts"] = 2
    assert validate_llm_quota_retry_policy(p)["validation_state"] == "BLOCKED"


def test_full_rewrite_without_override_blocks():
    p = _pass_policy()
    p["max_full_rewrite_attempts"] = 1
    assert validate_llm_quota_retry_policy(p)["validation_state"] == "BLOCKED"


def test_full_rewrite_with_override_cannot_pass():
    p = _pass_policy()
    p["max_full_rewrite_attempts"] = 1
    p["explicit_operator_override"] = True
    # Override downgrades to REVIEW_REQUIRED; it can never be PASS.
    assert validate_llm_quota_retry_policy(p)["validation_state"] == "REVIEW_REQUIRED"


@pytest.mark.parametrize("pat_text", [
    "generate until pass",
    "retry until success",
    "auto-regenerate the draft",
    "this is an unbounded loop",
    "rewrite the entire draft repeatedly",
    "infinite retry",
    "full rewrite loop",
])
def test_forbidden_loop_language_blocks(pat_text):
    p = _pass_policy()
    p["policy_note"] = pat_text
    assert validate_llm_quota_retry_policy(p)["validation_state"] == "BLOCKED"


# --- Quota / spend tracking required ---

def test_missing_spend_field_blocks():
    p = _pass_policy()
    p["spend_fields_required"] = ["estimated_tokens", "actual_tokens"]
    assert validate_llm_quota_retry_policy(p)["validation_state"] == "BLOCKED"


def test_spend_tracking_flag_required():
    p = _pass_policy()
    p["spend_tracking_required"] = False
    assert validate_llm_quota_retry_policy(p)["validation_state"] == "BLOCKED"


# --- Cache key components required ---

def test_missing_cache_components_unknown():
    p = _pass_policy()
    p["cache_key_components"] = ["brief_hash", "prompt_version"]
    assert validate_llm_quota_retry_policy(p)["validation_state"] == "UNKNOWN"


def test_empty_cache_components_unknown():
    p = _pass_policy()
    p["cache_key_components"] = []
    assert validate_llm_quota_retry_policy(p)["validation_state"] == "UNKNOWN"


def test_cache_key_required_flag():
    p = _pass_policy()
    p["cache_key_required"] = False
    assert validate_llm_quota_retry_policy(p)["validation_state"] == "BLOCKED"


# --- Platform variants require canonical PASS ---

def test_platform_variants_flag_required():
    p = _pass_policy()
    p["platform_variants_require_canonical_pass"] = False
    assert validate_llm_quota_retry_policy(p)["validation_state"] == "BLOCKED"


# --- Provider / network / credential / live flags block ---

@pytest.mark.parametrize("flag", ["provider_api_allowed", "network_allowed", "credentials_required"])
def test_provider_network_credential_flags_block(flag):
    p = _pass_policy()
    p[flag] = True
    assert validate_llm_quota_retry_policy(p)["validation_state"] == "BLOCKED"


def test_no_live_dispatch_required():
    p = _pass_policy()
    p["no_live_dispatch"] = False
    assert validate_llm_quota_retry_policy(p)["validation_state"] == "BLOCKED"


def test_no_public_ready_claim_required():
    p = _pass_policy()
    p["no_public_ready_claim"] = False
    assert validate_llm_quota_retry_policy(p)["validation_state"] == "BLOCKED"


# --- Deterministic validator remains primary ---

def test_deterministic_validator_primary_required():
    p = _pass_policy()
    p["deterministic_validator_primary"] = False
    assert validate_llm_quota_retry_policy(p)["validation_state"] == "BLOCKED"


def test_llm_critique_optional_only_required():
    p = _pass_policy()
    p["llm_critique_optional_only"] = False
    assert validate_llm_quota_retry_policy(p)["validation_state"] == "BLOCKED"


def test_review_required_after_second_failure():
    p = _pass_policy()
    p["review_required_after_second_failure"] = False
    assert validate_llm_quota_retry_policy(p)["validation_state"] == "BLOCKED"


# --- Critique enabled but budget missing -> REVIEW_REQUIRED ---

def test_critique_enabled_without_budget_review():
    p = _pass_policy()
    p["llm_critique_enabled"] = True
    p.pop("llm_critique_budget", None)
    assert validate_llm_quota_retry_policy(p)["validation_state"] == "REVIEW_REQUIRED"


# --- Schema validation: every required true/false flag is enforced ---

def test_every_required_true_flag_blocks_when_false():
    for flag in REQUIRED_TRUE_FLAGS:
        p = _pass_policy()
        p[flag] = False
        assert validate_llm_quota_retry_policy(p)["validation_state"] == "BLOCKED", flag


def test_model_output_never_authority_required():
    p = _pass_policy()
    p["model_output_never_authority"] = False
    assert validate_llm_quota_retry_policy(p)["validation_state"] == "BLOCKED"
