"""Tests for scd_prompt_pack_compiler (0174AZ).

Deterministic prompt-pack compiler contract. Local-only, fail-closed. No
network, no provider/LLM API, no credentials/env, no UI runtime, no browser, no
screenshots, no live dispatch. Fixtures are generated by the repo's own
validator-asserted generator and committed under
fixtures/scd_prompt_pack_compiler/.
"""
import copy
import json
import os

import pytest

from live_contentops.scd_prompt_pack_compiler import (
    validate_prompt_pack_input,
    validate_canonical_writer_prompt_pack,
    validate_targeted_repair_prompt_pack,
    validate_prompt_pack_cache_key,
    validate_prompt_pack_validation_report,
    compile_prompt_pack_cache_key,
    compute_prompt_hash,
    PROMPT_PACK_VALIDATORS,
    REQUIRED_CACHE_KEY_FIELDS,
    REQUIRED_SAFETY_TRUE_FLAGS,
    REPAIR_PRESERVE_FLAGS,
    FORBIDDEN_READY_FLAGS,
    FORBIDDEN_PROVIDER_FLAGS,
)

FIXTURE_DIR = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "fixtures",
    "scd_prompt_pack_compiler",
)

MODULE_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "live_contentops",
    "scd_prompt_pack_compiler.py",
)

# Fixture filename -> (validator registry key, expected validation_state).
EXPECTED = {
    "input_pass.json": ("prompt_pack_input", "PASS"),
    "input_blocked_provider_network.json": ("prompt_pack_input", "BLOCKED"),
    "input_review_missing_audience.json": ("prompt_pack_input", "REVIEW_REQUIRED"),
    "input_unknown_missing_source_hash.json": ("prompt_pack_input", "UNKNOWN"),
    "canonical_pass.json": ("canonical_writer_prompt_pack", "PASS"),
    "canonical_blocked_forbidden_language.json": ("canonical_writer_prompt_pack", "BLOCKED"),
    "canonical_blocked_generation_attempts.json": ("canonical_writer_prompt_pack", "BLOCKED"),
    "canonical_blocked_missing_quota.json": ("canonical_writer_prompt_pack", "BLOCKED"),
    "canonical_blocked_platform_variants.json": ("canonical_writer_prompt_pack", "BLOCKED"),
    "canonical_blocked_quota_not_pass.json": ("canonical_writer_prompt_pack", "BLOCKED"),
    "repair_pass.json": ("targeted_repair_prompt_pack", "PASS"),
    "repair_blocked_full_rewrite.json": ("targeted_repair_prompt_pack", "BLOCKED"),
    "repair_blocked_missing_preservation.json": ("targeted_repair_prompt_pack", "BLOCKED"),
    "repair_blocked_new_claims.json": ("targeted_repair_prompt_pack", "BLOCKED"),
    "cache_key_pass.json": ("prompt_pack_cache_key", "PASS"),
    "report_pass.json": ("prompt_pack_validation_report", "PASS"),
}


def _load(name):
    with open(os.path.join(FIXTURE_DIR, name), encoding="utf-8") as fh:
        return json.load(fh)


def _canonical():
    return _load("canonical_pass.json")


def _repair():
    return _load("repair_pass.json")


def _input():
    return _load("input_pass.json")


def _cache_key():
    return _load("cache_key_pass.json")


# --- Fixture-driven validation-state coverage ---

@pytest.mark.parametrize("name,spec", sorted(EXPECTED.items()))
def test_fixture_validation_state(name, spec):
    key, expected = spec
    payload = _load(name)
    result = PROMPT_PACK_VALIDATORS[key](payload)
    assert result["validation_state"] == expected, (name, result["reasons"])


def test_all_fixtures_covered():
    on_disk = {f for f in os.listdir(FIXTURE_DIR) if f.endswith(".json")}
    assert on_disk == set(EXPECTED), on_disk.symmetric_difference(EXPECTED)


def test_all_four_states_present():
    states = {state for _, state in EXPECTED.values()}
    assert states == {"PASS", "BLOCKED", "REVIEW_REQUIRED", "UNKNOWN"}


def test_registry_exposes_all_validators():
    assert set(PROMPT_PACK_VALIDATORS) == {
        "prompt_pack_input",
        "canonical_writer_prompt_pack",
        "targeted_repair_prompt_pack",
        "prompt_pack_cache_key",
        "prompt_pack_validation_report",
    }


# --- Determinism: prompt hash + cache key recomputation ---

def test_prompt_hash_deterministic():
    pack = _canonical()
    first = compute_prompt_hash(pack)
    second = compute_prompt_hash(pack)
    assert first == second
    # Excludes the pack's own prompt_hash field, so reordering it is stable.
    mutated = copy.deepcopy(pack)
    mutated["prompt_hash"] = "sha256:different"
    assert compute_prompt_hash(mutated) == first


def test_prompt_hash_changes_with_body():
    pack = _canonical()
    base = compute_prompt_hash(pack)
    mutated = copy.deepcopy(pack)
    mutated["allowed_angle"] = "a different angle entirely"
    assert compute_prompt_hash(mutated) != base


def test_cache_key_deterministic():
    components = {f: _cache_key()[f] for f in REQUIRED_CACHE_KEY_FIELDS}
    first = compile_prompt_pack_cache_key(components)
    second = compile_prompt_pack_cache_key(components)
    assert first == second
    assert first["composite_key_hash"] == _cache_key()["composite_key_hash"]


def test_cache_key_hash_mismatch_blocks():
    ck = _cache_key()
    ck["composite_key_hash"] = "sha256:tampered"
    assert validate_prompt_pack_cache_key(ck)["validation_state"] == "BLOCKED"


def test_cache_key_missing_component_blocks():
    for field in REQUIRED_CACHE_KEY_FIELDS:
        ck = _cache_key()
        ck.pop("composite_key_hash", None)  # avoid mismatch masking the missing-field block
        ck[field] = ""
        assert validate_prompt_pack_cache_key(ck)["validation_state"] == "BLOCKED", field


# --- Quota policy enforcement ---

def test_canonical_requires_pass_quota_policy():
    pack = _canonical()
    pack["quota_policy_summary"]["validation_state"] = "REVIEW_REQUIRED"
    assert validate_canonical_writer_prompt_pack(pack)["validation_state"] == "BLOCKED"


def test_canonical_missing_quota_policy_blocks():
    pack = _canonical()
    pack.pop("quota_policy_summary", None)
    assert validate_canonical_writer_prompt_pack(pack)["validation_state"] == "BLOCKED"


def test_quota_policy_generation_attempts_must_be_one():
    pack = _canonical()
    pack["quota_policy_summary"]["max_generation_attempts"] = 2
    assert validate_canonical_writer_prompt_pack(pack)["validation_state"] == "BLOCKED"


def test_quota_policy_repair_attempts_bounded():
    pack = _repair()
    pack["quota_policy_summary"]["max_targeted_repair_attempts"] = 2
    assert validate_targeted_repair_prompt_pack(pack)["validation_state"] == "BLOCKED"


# --- Canonical: single generation + platform variant gating ---

def test_canonical_draft_count_must_be_one():
    pack = _canonical()
    pack["canonical_draft_count"] = 3
    assert validate_canonical_writer_prompt_pack(pack)["validation_state"] == "BLOCKED"


def test_platform_variants_gated_before_canonical_pass():
    pack = _canonical()
    pack["platform_variants_requested"] = True
    assert validate_canonical_writer_prompt_pack(pack)["validation_state"] == "BLOCKED"


@pytest.mark.parametrize("flag", REQUIRED_SAFETY_TRUE_FLAGS)
def test_canonical_safety_flags_required(flag):
    pack = _canonical()
    pack[flag] = False
    assert validate_canonical_writer_prompt_pack(pack)["validation_state"] == "BLOCKED"


# --- Targeted repair scope enforcement ---

def test_repair_forbid_full_rewrite():
    pack = _repair()
    pack["allow_full_rewrite"] = True
    assert validate_targeted_repair_prompt_pack(pack)["validation_state"] == "BLOCKED"


def test_repair_forbid_new_claims():
    pack = _repair()
    pack["allow_new_claims"] = True
    assert validate_targeted_repair_prompt_pack(pack)["validation_state"] == "BLOCKED"


def test_repair_patch_only_required():
    pack = _repair()
    pack["patch_only_failing_section"] = False
    assert validate_targeted_repair_prompt_pack(pack)["validation_state"] == "BLOCKED"


@pytest.mark.parametrize("flag", REPAIR_PRESERVE_FLAGS)
def test_repair_preservation_flags_required(flag):
    pack = _repair()
    pack[flag] = False
    assert validate_targeted_repair_prompt_pack(pack)["validation_state"] == "BLOCKED"


def test_repair_validator_failure_refs_required():
    pack = _repair()
    pack["validator_failure_refs"] = []
    assert validate_targeted_repair_prompt_pack(pack)["validation_state"] == "BLOCKED"


# --- Forbidden language / provider / ready flag blocking ---

@pytest.mark.parametrize("phrase", [
    "this is a strong buy signal",
    "set a price target of 100",
    "guaranteed profit for readers",
    "place an order with your broker",
])
def test_forbidden_financial_language_blocks(phrase):
    pack = _canonical()
    pack["allowed_angle"] = phrase
    assert validate_canonical_writer_prompt_pack(pack)["validation_state"] == "BLOCKED"


@pytest.mark.parametrize("phrase", [
    "retry until success",
    "auto-regenerate the draft",
    "rewrite the entire draft repeatedly",
])
def test_loop_language_blocks(phrase):
    pack = _canonical()
    pack["writer_instructions"] = phrase
    assert validate_canonical_writer_prompt_pack(pack)["validation_state"] == "BLOCKED"


@pytest.mark.parametrize("flag", FORBIDDEN_PROVIDER_FLAGS)
def test_provider_flags_block(flag):
    pack = _canonical()
    pack[flag] = True
    assert validate_canonical_writer_prompt_pack(pack)["validation_state"] == "BLOCKED"


@pytest.mark.parametrize("flag", FORBIDDEN_READY_FLAGS)
def test_ready_flags_block(flag):
    pack = _canonical()
    pack[flag] = True
    assert validate_canonical_writer_prompt_pack(pack)["validation_state"] == "BLOCKED"


def test_secret_like_value_blocks():
    pack = _canonical()
    pack["allowed_angle"] = "use api_key abc to call the service"
    assert validate_canonical_writer_prompt_pack(pack)["validation_state"] == "BLOCKED"


# --- Input lineage: UNKNOWN / REVIEW_REQUIRED behavior ---

def test_input_missing_source_hash_unknown():
    payload = _input()
    payload["source_packet_hash"] = ""
    assert validate_prompt_pack_input(payload)["validation_state"] == "UNKNOWN"


def test_input_missing_audience_review():
    payload = _input()
    payload.pop("audience_mode", None)
    payload.pop("voice_profile", None)
    assert validate_prompt_pack_input(payload)["validation_state"] == "REVIEW_REQUIRED"


def test_input_block_precedes_unknown():
    # A hard block must win over a missing-lineage UNKNOWN.
    payload = _input()
    payload["source_packet_hash"] = ""
    payload["provider_api_allowed"] = True
    assert validate_prompt_pack_input(payload)["validation_state"] == "BLOCKED"


# --- Validation report roll-up: fail closed ---

def test_report_pass_roundtrip():
    assert validate_prompt_pack_validation_report(_load("report_pass.json"))["validation_state"] == "PASS"


def test_report_blocked_subresult_forces_block():
    rep = _load("report_pass.json")
    rep["canonical_result"] = "BLOCKED"
    assert validate_prompt_pack_validation_report(rep)["validation_state"] == "BLOCKED"


def test_report_pass_contradicting_rollup_blocks():
    rep = _load("report_pass.json")
    rep["repair_result"] = "UNKNOWN"  # final still PASS -> contradiction
    assert validate_prompt_pack_validation_report(rep)["validation_state"] == "BLOCKED"


def test_report_requires_operator_review():
    rep = _load("report_pass.json")
    rep["operator_review_required"] = False
    assert validate_prompt_pack_validation_report(rep)["validation_state"] == "BLOCKED"


# --- Static guard: no provider / network / env / API imports in the module ---

def test_module_has_no_provider_network_env_imports():
    with open(MODULE_PATH, encoding="utf-8") as fh:
        src = fh.read()
    forbidden = [
        "import requests",
        "import httpx",
        "import urllib",
        "import socket",
        "import openai",
        "import anthropic",
        "subprocess.",
        "os.environ",
        "os.getenv",
        "webbrowser",
    ]
    hits = [tok for tok in forbidden if tok in src]
    assert hits == [], hits
