"""Exporter tests for V5 Supervised Operator Input Stub Contract packet.

Part of TASK_CONTENTOPS_0175BQ_SUPERVISED_INPUT_STUB_CONTRACT_TO_V5_READONLY_STUB_PANEL_BINDING_V0.
"""
from __future__ import annotations

import importlib.util
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
EXPORTER_PATH = ROOT / "tools" / "export_v5_supervised_input_stub_contract_packet.py"
ARTIFACT_PATH = ROOT / "ui" / "contentops_v5" / "src" / "data" / "supervisedInputStubContractPacket.ts"


def _load_exporter():
    spec = importlib.util.spec_from_file_location("export_v5_supervised_input_stub_contract_packet", EXPORTER_PATH)
    assert spec is not None
    assert spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_packet_loads_and_render_ts_is_deterministic():
    exporter = _load_exporter()
    packet = exporter.load_packet()

    assert packet["global_supervised_input_stub_status"] == "BLOCKED_SUPERVISED_INPUT_CAPTURE_NOT_ENABLED"
    assert packet["source_input_capture_precheck_item_count"] == 7
    assert len(packet["supervised_input_stub_items"]) == 7
    assert packet["future_capture_modes_enabled_in_this_task"] is False

    rendered_once = exporter.render_ts(packet)
    rendered_twice = exporter.render_ts(packet)

    assert rendered_once == rendered_twice
    assert rendered_once.startswith("// AUTO-GENERATED by tools/export_v5_supervised_input_stub_contract_packet.py")
    assert "export const supervisedInputStubContractPacket" in rendered_once


def test_cmd_check_and_main_check_return_success():
    exporter = _load_exporter()

    assert exporter.cmd_check() == 0
    assert exporter.main(["--check"]) == 0


def test_generated_ts_is_byte_identical_to_rendered_source_packet():
    exporter = _load_exporter()
    packet = exporter.load_packet()
    expected = exporter.render_ts(packet)
    actual = ARTIFACT_PATH.read_text(encoding="utf-8")

    assert actual == expected


def test_field_policy_remains_pending_disabled_and_schema_only():
    exporter = _load_exporter()
    packet = exporter.load_packet()

    for field_name, policy in packet["input_stub_field_policy"].items():
        assert field_name in packet["required_input_fields"]
        assert policy["required"] is True
        assert policy["slot_status"] == "STUB_SLOT_PENDING_SUPERVISED_INPUT"
        assert policy["value_status"] == "PENDING_OPERATOR_INPUT"
        assert policy["current_value"] is None
        assert policy["placeholder_value"] == "PENDING_OPERATOR_INPUT"
        assert policy["capture_enabled_in_this_task"] is False
        assert policy["editable_in_this_task"] is False
        assert policy["generated_by_system"] is False
        assert policy["operator_must_provide_later"] is True
        assert policy["future_supervised_capture_required"] is True
        assert policy["persistence_enabled"] is False
        assert policy["validation_enabled"] is False

    for item in packet["supervised_input_stub_items"]:
        assert item["supervised_input_stub_status"] == "SUPERVISED_INPUT_STUB_PENDING_FUTURE_CAPTURE"
        assert item["required_input_fields"] == packet["required_input_fields"]
        for policy in item["input_stub_field_policy"].values():
            assert policy["current_value"] is None
            assert policy["placeholder_value"] == "PENDING_OPERATOR_INPUT"
            assert policy["capture_enabled_in_this_task"] is False
            assert policy["editable_in_this_task"] is False
            assert policy["persistence_enabled"] is False


def test_safety_scan_blocks_forbidden_tokens_except_policy_list_entries():
    exporter = _load_exporter()

    allowed_text = '"headline" "hook" "caption" "draft_paragraph" "platform_copy" "prediction" "recommendation" "buy_sell_hold_sizing_signal_language" "actual_input_capture" "editable_input_fields"'
    assert exporter._safety_scan(allowed_text) == []

    blocked_text = "<input onChange= capture now submit save generate control buy sell hold price target dispatch live platform copy"
    hits = exporter._safety_scan(blocked_text)

    assert "<input" in hits
    assert "onChange=" in hits
    assert "capture now" in hits
    assert "submit" in hits
    assert "save" in hits
    assert "generate control" in hits
    assert "buy" in hits
    assert "sell" in hits
    assert "hold" in hits
    assert "price target" in hits
    assert "dispatch live" in hits
    assert "platform copy" in hits


def test_generated_ts_has_no_env_secret_or_editable_control_language():
    exporter = _load_exporter()
    text = ARTIFACT_PATH.read_text(encoding="utf-8")

    assert exporter._safety_scan(text) == []
