"""Tests for scd_render_golden_snapshot (0174AX).

Render golden-snapshot / binding-conformance contract. Local-only, deterministic,
fail-closed. No network, no UI runtime, no browser, no screenshots. Fixtures are
generated by the repo's own helpers so canonical hashes are authoritative.
"""
import copy
import json
import os

import pytest

from live_contentops.scd_render_golden_snapshot import (
    canonical_json_sha256,
    freeze_render_golden_snapshot,
    compare_render_spec_to_golden_snapshot,
    build_golden_snapshot_manifest,
    build_golden_snapshot_report,
    validate_render_golden_snapshot_input,
    validate_render_golden_snapshot,
    validate_render_binding_conformance_result,
    validate_render_golden_snapshot_manifest,
    validate_render_golden_snapshot_report,
    RENDER_GOLDEN_SNAPSHOT_VALIDATORS,
    REQUIRED_REPLAY_STATES,
)

FIX = os.path.join(os.path.dirname(__file__), "..", "fixtures", "scd_render_golden_snapshot")


def load(name):
    with open(os.path.join(FIX, name), encoding="utf-8") as f:
        return json.load(f)


def _render_spec(state, rs_id):
    return {
        "schema_version": "1.0",
        "render_spec_id": rs_id,
        "view_model_id": "vm_" + state.lower(),
        "render_mode": "display_spec_only",
        "layout_regions": ["command_hero", "stage_matrix", "current_truth_panel"],
        "display_slot_bindings": ["headline_status_slot", "current_truth_slot"],
        "status_token_bindings": ["token_" + state.lower()],
        "current_vs_historical_truth_binding": {
            "current_replay_report_slot": "current_truth_slot",
            "historical_evidence_slot": "historical_truth_slot",
            "current_state_is_authoritative": True,
            "stale_or_historical_refs_separated": True,
        },
        "display_only": True,
        "action_enabled": False,
        "validation_state": state,
    }


# (fixture, registry validator key, expected validation_state)
FIXTURE_CASES = [
    ("input_pass.json", "render_golden_snapshot_input", "PASS"),
    ("input_blocked_ui_runtime.json", "render_golden_snapshot_input", "BLOCKED"),
    ("input_blocked_html_network.json", "render_golden_snapshot_input", "BLOCKED"),
    ("input_unknown_missing_refs.json", "render_golden_snapshot_input", "UNKNOWN"),
    ("golden_snapshot_pass.json", "render_golden_snapshot", "PASS"),
    ("golden_snapshot_blocked_state.json", "render_golden_snapshot", "PASS"),
    ("golden_snapshot_review_required_state.json", "render_golden_snapshot", "PASS"),
    ("golden_snapshot_unknown_state.json", "render_golden_snapshot", "PASS"),
    ("golden_snapshot_blocked_hash_mismatch.json", "render_golden_snapshot", "BLOCKED"),
    ("golden_snapshot_blocked_ui_required.json", "render_golden_snapshot", "BLOCKED"),
    ("golden_snapshot_blocked_telegram.json", "render_golden_snapshot", "BLOCKED"),
    ("golden_snapshot_blocked_html_dom.json", "render_golden_snapshot", "BLOCKED"),
    ("conformance_pass.json", "render_binding_conformance_result", "PASS"),
    ("conformance_blocked_canonical_mismatch.json", "render_binding_conformance_result", "BLOCKED"),
    ("conformance_blocked_structural.json", "render_binding_conformance_result", "BLOCKED"),
    ("conformance_blocked_bindings.json", "render_binding_conformance_result", "BLOCKED"),
    ("conformance_blocked_mutation.json", "render_binding_conformance_result", "BLOCKED"),
    ("conformance_blocked_financial_language.json", "render_binding_conformance_result", "BLOCKED"),
    ("manifest_pass.json", "render_golden_snapshot_manifest", "PASS"),
    ("manifest_blocked_missing_state.json", "render_golden_snapshot_manifest", "BLOCKED"),
    ("manifest_blocked_mutation_after_freeze.json", "render_golden_snapshot_manifest", "BLOCKED"),
    ("manifest_unknown_missing_refs.json", "render_golden_snapshot_manifest", "UNKNOWN"),
    ("report_pass.json", "render_golden_snapshot_report", "PASS"),
    ("report_blocked_failed_hash_pass.json", "render_golden_snapshot_report", "BLOCKED"),
    ("report_blocked_no_html_false.json", "render_golden_snapshot_report", "BLOCKED"),
    ("report_review_required.json", "render_golden_snapshot_report", "REVIEW_REQUIRED"),
    ("report_unknown.json", "render_golden_snapshot_report", "UNKNOWN"),
]


@pytest.mark.parametrize("fixture,validator_key,expected", FIXTURE_CASES)
def test_fixture_validation_state(fixture, validator_key, expected):
    payload = load(fixture)
    validator = RENDER_GOLDEN_SNAPSHOT_VALIDATORS[validator_key]
    result = validator(payload)
    assert result["validation_state"] == expected, (fixture, result)


def test_registry_covers_all_validators():
    assert set(RENDER_GOLDEN_SNAPSHOT_VALIDATORS) == {
        "render_golden_snapshot_input",
        "render_golden_snapshot",
        "render_binding_conformance_result",
        "render_golden_snapshot_manifest",
        "render_golden_snapshot_report",
    }


def test_required_replay_states():
    assert set(REQUIRED_REPLAY_STATES) == {"PASS", "BLOCKED", "REVIEW_REQUIRED", "UNKNOWN"}


def test_all_four_replay_states_have_pass_golden_snapshot():
    states = set()
    for name in ("golden_snapshot_pass.json", "golden_snapshot_blocked_state.json",
                 "golden_snapshot_review_required_state.json", "golden_snapshot_unknown_state.json"):
        snap = load(name)
        assert validate_render_golden_snapshot(snap)["validation_state"] == "PASS"
        states.add(snap["replay_state"])
    assert states == {"PASS", "BLOCKED", "REVIEW_REQUIRED", "UNKNOWN"}


# --- Deterministic canonical hash ---

def test_canonical_hash_key_order_independent():
    a = {"b": 1, "a": 2, "nested": {"y": 1, "x": 2}}
    b = {"a": 2, "b": 1, "nested": {"x": 2, "y": 1}}
    assert canonical_json_sha256(a) == canonical_json_sha256(b)


def test_canonical_hash_changes_after_mutation():
    base = {"render_spec_id": "rs", "regions": ["a", "b"]}
    mutated = {"render_spec_id": "rs", "regions": ["a", "c"]}
    assert canonical_json_sha256(base) != canonical_json_sha256(mutated)


def test_canonical_hash_is_prefixed_and_stable():
    h = canonical_json_sha256({"x": 1})
    assert h.startswith("canonical_json_sha256:")
    assert h == canonical_json_sha256({"x": 1})


# --- Helper: freeze ---

def test_freeze_produces_matching_hash_and_pass():
    spec = _render_spec("PASS", "rs_freeze")
    snap = freeze_render_golden_snapshot(spec, "PASS", ["fixtures/scd_render_spec/render_spec_pass.json"])
    assert snap["canonical_json_sha256"] == canonical_json_sha256(snap["snapshot_payload"])
    assert validate_render_golden_snapshot(snap)["validation_state"] == "PASS"
    assert snap["display_only"] is True
    assert snap["action_enabled"] is False
    for flag in ("ui_runtime_required", "browser_required", "screenshot_required",
                 "html_css_js_required", "public_ready", "live_ready",
                 "executable_dispatch", "api_gate_required"):
        assert snap[flag] is False


def test_freeze_invents_no_refs():
    spec = _render_spec("PASS", "rs_freeze")
    snap = freeze_render_golden_snapshot(spec, "PASS")
    assert snap["source_fixture_refs"] == []
    assert snap["render_spec_report_ref"] == ""


# --- Helper: compare ---

def test_compare_matching_spec_is_pass():
    spec = _render_spec("PASS", "rs_cmp")
    snap = freeze_render_golden_snapshot(spec, "PASS")
    result = compare_render_spec_to_golden_snapshot(spec, snap)
    assert result["canonical_json_match"] is True
    assert result["structural_binding_match"] is True
    assert result["mutation_detected"] is False
    assert validate_render_binding_conformance_result(result)["validation_state"] == "PASS"


def test_compare_detects_mutation_after_freeze():
    spec = _render_spec("PASS", "rs_cmp")
    snap = freeze_render_golden_snapshot(spec, "PASS")
    snap["snapshot_payload"]["view_model_id"] = "vm_tampered"
    result = compare_render_spec_to_golden_snapshot(spec, snap)
    assert result["mutation_detected"] is True
    assert validate_render_binding_conformance_result(result)["validation_state"] == "BLOCKED"


def test_compare_detects_structural_divergence():
    spec = _render_spec("PASS", "rs_cmp")
    snap = freeze_render_golden_snapshot(spec, "PASS")
    altered = copy.deepcopy(spec)
    altered["layout_regions"] = ["command_hero"]
    result = compare_render_spec_to_golden_snapshot(altered, snap)
    assert result["missing_regions"]
    assert result["structural_binding_match"] is False
    assert validate_render_binding_conformance_result(result)["validation_state"] == "BLOCKED"


# --- Helper: manifest / report ---

def _all_state_snapshots():
    return [freeze_render_golden_snapshot(_render_spec(s, "rs_" + s.lower()), s)
            for s in ("PASS", "BLOCKED", "REVIEW_REQUIRED", "UNKNOWN")]


def test_manifest_requires_all_four_states():
    full = build_golden_snapshot_manifest(_all_state_snapshots(), "v1")
    assert validate_render_golden_snapshot_manifest(full)["validation_state"] == "PASS"
    partial = build_golden_snapshot_manifest(_all_state_snapshots()[:3], "v1")
    assert validate_render_golden_snapshot_manifest(partial)["validation_state"] == "BLOCKED"


def test_report_pass_requires_all_conformance_pass():
    snaps = _all_state_snapshots()
    manifest = build_golden_snapshot_manifest(snaps, "v1")
    confs = [compare_render_spec_to_golden_snapshot(
        _render_spec(s, "rs_" + s.lower()), snaps[i])
        for i, s in enumerate(("PASS", "BLOCKED", "REVIEW_REQUIRED", "UNKNOWN"))]
    report = build_golden_snapshot_report(manifest, confs)
    assert report["final_recommendation"] == "PASS"
    assert report["display_contract_locked"] is True
    assert validate_render_golden_snapshot_report(report)["validation_state"] == "PASS"


def test_report_fail_closed_precedence():
    snaps = _all_state_snapshots()
    manifest = build_golden_snapshot_manifest(snaps, "v1")
    good = compare_render_spec_to_golden_snapshot(_render_spec("PASS", "rs_pass"), snaps[0])

    blocked = copy.deepcopy(good)
    blocked["validation_state"] = "BLOCKED"
    unknown = copy.deepcopy(good)
    unknown["validation_state"] = "UNKNOWN"
    review = copy.deepcopy(good)
    review["validation_state"] = "REVIEW_REQUIRED"

    # BLOCKED dominates everything.
    rep = build_golden_snapshot_report(manifest, [good, review, unknown, blocked])
    assert rep["final_recommendation"] == "BLOCKED"
    # UNKNOWN dominates REVIEW_REQUIRED and PASS.
    rep = build_golden_snapshot_report(manifest, [good, review, unknown])
    assert rep["final_recommendation"] == "UNKNOWN"
    # REVIEW_REQUIRED dominates PASS.
    rep = build_golden_snapshot_report(manifest, [good, review])
    assert rep["final_recommendation"] == "REVIEW_REQUIRED"


def test_report_pass_is_not_publish_or_dispatch_ready():
    snaps = _all_state_snapshots()
    manifest = build_golden_snapshot_manifest(snaps, "v1")
    confs = [compare_render_spec_to_golden_snapshot(
        _render_spec(s, "rs_" + s.lower()), snaps[i])
        for i, s in enumerate(("PASS", "BLOCKED", "REVIEW_REQUIRED", "UNKNOWN"))]
    report = build_golden_snapshot_report(manifest, confs)
    assert report["public_ready"] is False
    assert report["live_ready"] is False
    assert report["executable_dispatch"] is False
    assert report["api_gate_required"] is False


# --- Direct invariant blocking ---

def test_action_enabled_blocks_when_true():
    snap = freeze_render_golden_snapshot(_render_spec("PASS", "rs_a"), "PASS")
    snap["action_enabled"] = True
    assert validate_render_golden_snapshot(snap)["validation_state"] == "BLOCKED"


def test_ui_runtime_required_blocks_when_true():
    for flag in ("ui_runtime_required", "browser_required",
                 "screenshot_required", "html_css_js_required"):
        snap = freeze_render_golden_snapshot(_render_spec("PASS", "rs_u"), "PASS")
        snap[flag] = True
        assert validate_render_golden_snapshot(snap)["validation_state"] == "BLOCKED", flag


def test_forbidden_ready_flags_block():
    for flag in ("public_ready", "live_ready", "executable_dispatch"):
        snap = freeze_render_golden_snapshot(_render_spec("PASS", "rs_r"), "PASS")
        snap[flag] = True
        assert validate_render_golden_snapshot(snap)["validation_state"] == "BLOCKED", flag


def test_api_gate_required_blocks():
    snap = freeze_render_golden_snapshot(_render_spec("PASS", "rs_g"), "PASS")
    snap["api_gate_required"] = True
    assert validate_render_golden_snapshot(snap)["validation_state"] == "BLOCKED"


def test_input_allow_flags_block():
    base = load("input_pass.json")
    for flag in ("allow_ui_runtime", "allow_browser", "allow_screenshot",
                 "allow_html_css_js", "allow_network", "allow_credentials",
                 "allow_platform_api", "allow_live_dispatch"):
        payload = copy.deepcopy(base)
        payload[flag] = True
        assert validate_render_golden_snapshot_input(payload)["validation_state"] == "BLOCKED", flag


def test_report_no_html_css_js_edits_required_true():
    rep = load("report_pass.json")
    assert rep["no_html_css_js_edits"] is True
    assert rep["no_api_required"] is True
    rep_bad = copy.deepcopy(rep)
    rep_bad["no_html_css_js_edits"] = False
    assert validate_render_golden_snapshot_report(rep_bad)["validation_state"] == "BLOCKED"


def test_forbidden_financial_language_blocks_any_object():
    snap = freeze_render_golden_snapshot(_render_spec("PASS", "rs_f"), "PASS")
    snap["note"] = "buy now and sell at the price target, this signal guarantees gains"
    assert validate_render_golden_snapshot(snap)["validation_state"] == "BLOCKED"


def test_telegram_api_webhook_implication_blocks():
    snap = freeze_render_golden_snapshot(_render_spec("PASS", "rs_t"), "PASS")
    snap["note"] = "telegram bot sendMessage chat_id webhook bearer token"
    assert validate_render_golden_snapshot(snap)["validation_state"] == "BLOCKED"


def test_html_dom_browser_runtime_implication_blocks():
    snap = freeze_render_golden_snapshot(_render_spec("PASS", "rs_h"), "PASS")
    snap["note"] = "<script>document.querySelector('x').innerHTML = y</script>"
    assert validate_render_golden_snapshot(snap)["validation_state"] == "BLOCKED"


# --- Static no-UI-runtime / no-network source scan ---

def test_module_source_has_no_runtime_or_network_patterns():
    src_path = os.path.join(os.path.dirname(__file__), "..",
                            "live_contentops", "scd_render_golden_snapshot.py")
    with open(src_path, encoding="utf-8") as f:
        src = f.read()
    forbidden = [
        "import requests", "import urllib", "import socket", "import httpx",
        "import openai", "import anthropic", "os.environ", "getenv", "dotenv",
        ".post(", "fetch(", "document.querySelector", "window.",
        "addEventListener", "innerHTML", "<script", "playwright", "selenium",
        "sendMessage", "chat_id", "webhook",
    ]
    hits = [p for p in forbidden if p in src]
    assert hits == [], hits
