"""Exporter tests for V5 Operator Input Capture Precheck packet.

Part of TASK_CONTENTOPS_0175BO_COMPLETION_EVIDENCE_TEST_AND_DOCS_REPAIR_V0.
"""
from __future__ import annotations

import importlib.util
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
EXPORTER_PATH = ROOT / "tools" / "export_v5_operator_input_capture_precheck_packet.py"
ARTIFACT_PATH = ROOT / "ui" / "contentops_v5" / "src" / "data" / "operatorInputCapturePrecheckPacket.ts"


def _load_exporter():
    spec = importlib.util.spec_from_file_location("export_v5_operator_input_capture_precheck_packet", EXPORTER_PATH)
    assert spec is not None
    assert spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_packet_loads_and_render_ts_is_deterministic():
    exporter = _load_exporter()
    packet = exporter.load_packet()

    assert packet["global_operator_input_capture_status"] == "BLOCKED_OPERATOR_INPUT_CAPTURE_NOT_ENABLED"
    assert packet["source_intent_item_count"] > 0
    assert packet["input_capture_precheck_items"]

    rendered_once = exporter.render_ts(packet)
    rendered_twice = exporter.render_ts(packet)

    assert rendered_once == rendered_twice
    assert rendered_once.startswith("// AUTO-GENERATED by tools/export_v5_operator_input_capture_precheck_packet.py")
    assert "export const operatorInputCapturePrecheckPacket" in rendered_once


def test_cmd_check_and_main_check_return_success():
    exporter = _load_exporter()

    assert exporter.cmd_check() == 0
    assert exporter.main(["--check"]) == 0


def test_generated_ts_is_byte_identical_to_rendered_source_packet():
    exporter = _load_exporter()
    packet = exporter.load_packet()
    expected = exporter.render_ts(packet)
    actual = ARTIFACT_PATH.read_text(encoding="utf-8")

    assert actual == expected


def test_safety_scan_blocks_forbidden_tokens_except_disallowed_output_list_entries():
    exporter = _load_exporter()

    allowed_text = '"headline" "hook" "caption" "draft_paragraph" "platform_copy" "prediction" "recommendation" "buy_sell_hold_sizing_signal_language"'
    assert exporter._safety_scan(allowed_text) == []

    blocked_text = "<input onChange= capture now submit save generate control buy sell hold price target dispatch live platform copy"
    hits = exporter._safety_scan(blocked_text)

    assert "<input" in hits
    assert "onChange=" in hits
    assert "capture now" in hits
    assert "submit" in hits
    assert "save" in hits
    assert "generate control" in hits
    assert "buy" in hits
    assert "sell" in hits
    assert "hold" in hits
    assert "price target" in hits
    assert "dispatch live" in hits
    assert "platform copy" in hits


def test_generated_ts_has_no_env_secret_or_editable_control_language():
    text = ARTIFACT_PATH.read_text(encoding="utf-8")
    disallowed_output_context = text
    for allowed in (
        '"headline"',
        '"hook"',
        '"caption"',
        '"draft_paragraph"',
        '"platform_copy"',
        '"prediction"',
        '"recommendation"',
        '"buy_sell_hold_sizing_signal_language"',
    ):
        disallowed_output_context = disallowed_output_context.replace(allowed, '"_allowed_forbidden_output_label_"')

    forbidden_fragments = (
        "process.env",
        ".env",
        "API key",
        "bearer token",
        "credential string",
        "<input",
        "<textarea",
        "contentEditable",
        "onChange=",
        "onSubmit=",
        "capture now",
        "publish now",
        "post now",
        "dispatch live",
        "approve button",
        "generate control",
    )

    for fragment in forbidden_fragments:
        assert fragment not in disallowed_output_context
