"""Exporter tests for V5 Draft Eligibility Gate Precheck packet.

Part of TASK_CONTENTOPS_0175BT_DRAFT_ELIGIBILITY_GATE_TO_V5_READONLY_STATUS_PANEL_BINDING_V0.
"""
from __future__ import annotations

import importlib.util
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EXPORTER_PATH = ROOT / "tools" / "export_v5_draft_eligibility_gate_precheck_packet.py"
ARTIFACT_PATH = ROOT / "ui" / "contentops_v5" / "src" / "data" / "draftEligibilityGatePrecheckPacket.ts"


def _load_exporter():
    spec = importlib.util.spec_from_file_location("export_v5_draft_eligibility_gate_precheck_packet", EXPORTER_PATH)
    assert spec is not None
    assert spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_packet_loads_and_render_ts_is_deterministic():
    exporter = _load_exporter()
    packet = exporter.load_packet()

    assert packet["global_draft_eligibility_status"] == "BLOCKED_DRAFT_ELIGIBILITY_SUPERVISED_INPUT_REQUIRED"
    assert packet["source_supervised_input_stub_item_count"] == 7
    assert len(packet["draft_eligibility_items"]) == 7
    assert len(packet["required_input_fields"]) == 6
    assert len(packet["missing_required_input_fields"]) == 6

    rendered_once = exporter.render_ts(packet)
    rendered_twice = exporter.render_ts(packet)

    assert rendered_once == rendered_twice
    assert rendered_once.startswith("// AUTO-GENERATED by tools/export_v5_draft_eligibility_gate_precheck_packet.py")
    assert "export const draftEligibilityGatePrecheckPacket" in rendered_once


def test_cmd_check_and_main_check_return_success():
    exporter = _load_exporter()

    assert exporter.cmd_check() == 0
    assert exporter.main(["--check"]) == 0


def test_generated_ts_is_byte_identical_to_rendered_source_packet():
    exporter = _load_exporter()
    packet = exporter.load_packet()
    expected = exporter.render_ts(packet)
    actual = ARTIFACT_PATH.read_text(encoding="utf-8")

    assert actual == expected


def test_field_policy_remains_blocked_disabled_and_schema_only():
    exporter = _load_exporter()
    packet = exporter.load_packet()

    # Verify global fields
    for field_name in packet["required_input_fields"]:
        assert field_name in packet["missing_required_input_fields"]

    for item in packet["draft_eligibility_items"]:
        assert item["draft_eligibility_status"] == "BLOCKED_DRAFT_ELIGIBILITY_SUPERVISED_INPUT_REQUIRED"
        assert len(item["required_input_fields"]) == 6
        assert len(item["missing_required_input_fields"]) == 6

        # Check policy flags are fail-closed/all false
        policy = item["draft_generation_policy"]
        assert policy["draft_generation_enabled"] is False
        assert policy["headline_generation_enabled"] is False
        assert policy["hook_generation_enabled"] is False
        assert policy["caption_generation_enabled"] is False
        assert policy["platform_copy_generation_enabled"] is False
        assert policy["ai_writer_generation_enabled"] is False
        assert policy["public_postable"] is False
        assert policy["dispatch_ready"] is False
        assert policy["draft_storage_enabled"] is False
        assert policy["operator_input_capture_enabled"] is False
        assert policy["validation_enabled"] is False

        # Check eligibility field policy
        field_policy = item["eligibility_field_policy"]
        for field_name, fp in field_policy.items():
            assert field_name in item["required_input_fields"]
            assert fp["required"] is True
            assert fp["source_slot_status"] == "STUB_SLOT_PENDING_SUPERVISED_INPUT"
            assert fp["source_value_status"] == "PENDING_OPERATOR_INPUT"
            assert fp["current_value"] is None
            assert fp["placeholder_value"] == "PENDING_OPERATOR_INPUT"
            assert fp["missing"] is True
            assert fp["pending_operator_input"] is True
            assert fp["capture_enabled_in_source_task"] is False
            assert fp["editable_in_source_task"] is False
            assert fp["generated_by_system"] is False
            assert fp["persistence_enabled"] is False
            assert fp["validation_enabled"] is False
            assert fp["draft_eligible"] is False
            assert fp["blocking_reason"] == "supervised_input_required_before_draft_eligibility"


def test_safety_scan_blocks_forbidden_tokens_except_policy_list_entries():
    exporter = _load_exporter()

    allowed_text = '"headline" "hook" "caption" "draft_paragraph" "platform_copy" "prediction" "recommendation" "buy_sell_hold_sizing_signal_language" "actual_input_capture" "editable_input_fields" "draft_generation_enabled" "public_postable"'
    assert exporter._safety_scan(allowed_text) == []

    blocked_text = "<input onChange= capture now submit save generate control buy sell hold price target dispatch live platform copy"
    hits = exporter._safety_scan(blocked_text)

    assert "<input" in hits
    assert "onChange=" in hits
    assert "capture now" in hits
    assert "submit" in hits
    assert "save" in hits
    assert "generate control" in hits
    assert "buy" in hits
    assert "sell" in hits
    assert "hold" in hits
    assert "price target" in hits
    assert "dispatch live" in hits
    assert "platform copy" in hits


def test_generated_ts_has_no_env_secret_or_editable_control_language():
    exporter = _load_exporter()
    text = ARTIFACT_PATH.read_text(encoding="utf-8")

    assert exporter._safety_scan(text) == []
