/* Institutional Shell Prototype fixture (0160). */
/* Local-only, fixture-driven. Derived from the accepted 0159 valid view-model */
/* fixture. No network, no fetch, no remote URLs, no secrets, no env paths. */
window.CC_INSTITUTIONAL_SHELL_FIXTURE = {
  packet_id: "institutional_shell_prototype_0160",
  shell_mode: "static_local_only",
  view_model_contract_version: "v2",
  global_state: {
    repo_path_label: "cc-live-contentops",
    branch_label: "master",
    accepted_head_short: "15b87ff",
    system_mode: "local_pre_alpha",
    kill_switch_status: "active",
    live_posting_enabled_now: false,
    platform_api_allowed_now: false,
    credential_state_summary: "credentials_present_redacted_no_values",
    current_gate: "telegram_official_docs_credential_validation_gate",
    next_allowed_action: "await_operator_audit",
    active_blockers: [],
    evidence_count: 12,
    known_residual_drift_count: 0,
    not_public_postable_count: 12,
    manual_review_required_count: 12
  },
  global_safety_banners: [
    { id: "LOCAL_ONLY", tone: "locked" },
    { id: "DRY_RUN_ONLY", tone: "locked" },
    { id: "REVIEW_ONLY", tone: "review" },
    { id: "MANUAL_REVIEW_REQUIRED", tone: "review" },
    { id: "NOT_PUBLIC_POSTABLE", tone: "locked" },
    { id: "LIVE_DISABLED", tone: "locked" },
    { id: "KILL_SWITCH_ACTIVE", tone: "blocked" },
    { id: "SECRET_REDACTED", tone: "redacted" },
    { id: "NO_FINANCIAL_ADVICE", tone: "caution" },
    { id: "NO_SIGNAL_LANGUAGE", tone: "caution" }
  ],
  status_token_tones: {
    PASS: "pass",
    DEGRADED: "degraded",
    BLOCKED: "blocked",
    REVIEW_REQUIRED: "review",
    NOT_PUBLIC_POSTABLE: "locked",
    LIVE_DISABLED: "locked",
    UNKNOWN: "unknown",
    PROXY_ONLY: "proxy",
    STALE: "degraded",
    SECRET_REDACTED: "redacted",
    CREDENTIAL_PRESENT_REDACTED: "redacted",
    CREDENTIAL_VALIDATED_NO_POST: "locked",
    API_VALIDATED_NO_POST: "locked",
    CHANNEL_PERMISSION_UNVALIDATED: "degraded",
    DQR_BLOCKING: "blocked",
    FORECAST_NOT_READY: "degraded",
    MANUAL_ONLY: "review",
    DRY_RUN_ONLY: "locked",
    KILL_SWITCH_ACTIVE: "blocked"
  },
  redaction_policy: {
    redact_secrets: true,
    redact_env_paths: true,
    redact_raw_platform_responses: true,
    redact_request_urls: true,
    no_raw_vendor_data: true
  },
  screenshot_safe_mode: {
    present: true,
    active_label: "SCREENSHOT-SAFE / LOCAL ONLY / NOT PUBLIC-POSTABLE / LIVE DISABLED",
    note: "Secrets, env paths, raw platform responses, raw request URLs and raw vendor data are redacted."
  },
  components_catalog: [
    "global_safety_ribbon", "command_center_status_header", "gate_card",
    "blocked_reason_stack", "evidence_link_card", "source_lineage_panel",
    "data_sufficiency_matrix", "forecast_readiness_card", "credential_redaction_badge",
    "platform_readiness_card", "telegram_gate_stepper", "approval_decision_card",
    "audit_timeline", "draft_inspector_panel", "claim_risk_panel",
    "content_lane_badge", "publish_disabled_control", "screenshot_safe_watermark",
    "limitation_strip", "freshness_chip", "proxy_only_warning", "missing_data_row",
    "not_public_postable_banner", "manual_review_required_banner",
    "kill_switch_indicator", "forbidden_action_tooltip"
  ],
  command_center_detail: {
    hero_status_band: {
      title: "Capital Chronicle ContentOps Command Center",
      system_mode: "local / static / fixture-driven",
      accepted_head: "1c03ca0",
      kill_switch: "active",
      public_state: "not_public_postable",
      live_api_state: "disabled",
      current_gate: "0161 command center screen implementation",
      next_allowed_action: "AWAIT OPERATOR/CHATGPT AUDIT_OF_0161_EVIDENCE_BEFORE_ANY_NEXT_TASK"
    },
    executive_status_cards: [
      { id: "system_safety", title: "System Safety", state: "PASS", detail: "Kill switch active. Live disabled. Review-only. Not public-postable." },
      { id: "build_baseline", title: "Build Baseline", state: "PASS", detail: "Accepted HEAD 1c03ca0. 0160 static shell prototype accepted." },
      { id: "publish_automation", title: "Publish Automation", state: "LIVE_DISABLED", detail: "Dry-run only. Platform API disabled. One-button publish-all disabled." },
      { id: "telegram_pilot_gate", title: "Telegram Pilot Gate", state: "API_VALIDATED_NO_POST", detail: "Credentials redacted. sendMessage disabled. Channel permission unvalidated." },
      { id: "evidence_audit", title: "Evidence / Audit", state: "PASS", detail: "Full suite green at fixture baseline. Secret scan clean. Forbidden scope clean." },
      { id: "ui_rebuild_track", title: "UI Rebuild Track", state: "REVIEW_REQUIRED", detail: "0157-0160 accepted. 0161 current. Antigravity future-only." },
      { id: "content_studio_track", title: "Content Studio Track", state: "REVIEW_REQUIRED", detail: "Review-only. Source/evidence required. No final social copy." },
      { id: "residual_drift", title: "Residual Drift", state: "MANUAL_ONLY", detail: "Local env file and strategy docs untouched/untracked. No cleanup allowed." }
    ],
    gate_timeline: [
      { gate: "0157", label: "UI/UX master plan", state: "PASS" },
      { gate: "0158", label: "design system", state: "PASS" },
      { gate: "0159", label: "view-model contract", state: "PASS" },
      { gate: "0160", label: "static shell prototype", state: "PASS" },
      { gate: "0161", label: "command center screen", state: "REVIEW_REQUIRED" },
      { gate: "0162", label: "content studio rebuild", state: "UNKNOWN" },
      { gate: "0163", label: "publish readiness tower", state: "UNKNOWN" },
      { gate: "0164", label: "evidence vault", state: "UNKNOWN" },
      { gate: "0165", label: "calendar/workflow board", state: "UNKNOWN" },
      { gate: "0166", label: "visual export/screenshot-safe mode", state: "UNKNOWN" },
      { gate: "0167", label: "Antigravity browser QA", state: "UNKNOWN" },
      { gate: "0168", label: "Cline polish pass", state: "UNKNOWN" }
    ],
    blocked_action_matrix: [
      { action: "live_posting", state: "disabled" },
      { action: "scheduler", state: "disabled" },
      { action: "platform_api", state: "disabled" },
      { action: "provider_llm_api", state: "disabled" },
      { action: "scraping", state: "disabled" },
      { action: "autonomous_replies_dms", state: "disabled" },
      { action: "one_button_publish_all", state: "disabled" },
      { action: "public_ready_final_copy", state: "disabled" },
      { action: "credential_display", state: "disabled" },
      { action: "raw_env_paths", state: "disabled" },
      { action: "raw_request_urls", state: "disabled" },
      { action: "raw_platform_responses", state: "disabled" },
      { action: "broker_execution_order_routing", state: "disabled" }
    ],
    evidence_summary: {
      full_suite_result: "1402 passed, 28 skipped (fixture baseline)",
      focused_tests_result: "shell + command center focused tests passing (fixture baseline)",
      cli_summaries: "passing",
      secret_scan_status: "clean (0 secrets)",
      forbidden_scope_status: "clean",
      git_status_summary: "only known residual drift untouched",
      known_residual_drift: "untouched",
      evidence_packet_required: true
    },
    telegram_gate_state: {
      credential_presence: "redacted_presence_only",
      official_docs_gate: "implemented",
      live_getme: "not_run_unless_explicitly_executed_later",
      channel_write_permission: "unvalidated",
      send_message: "disabled",
      live_adapter: "disabled",
      posting: "disabled",
      next_step: "requires separate audit/gate"
    },
    publish_automation_state: {
      mode: "dry_run_only",
      platform_capability_registry: "modeled",
      dry_run_batch_manifest: "modeled",
      redacted_audit: "modeled",
      manual_approval_required: true,
      live: "disabled",
      one_button_publish_all: "disabled"
    },
    content_studio_state: {
      content_lanes: "process lane + grounded-news context lane",
      grounded_news: "hook_not_signal",
      review_only: true,
      source_evidence_required: true,
      not_public_postable: true,
      final_social_copy_generated_by_repo: false
    },
    ui_rebuild_state: {
      accepted: ["0157", "0158", "0159", "0160"],
      current: "0161",
      antigravity: "future_only",
      browser_qa: "none_yet",
      screenshots: "none_yet"
    },
    residual_drift_panel: {
      env_local: "exists locally; must remain untouched/untracked",
      strategy_docs_pdfs: "untracked if present; untouched",
      old_bundles: "project_sources_bundle_AFTER_0074 and recovered_strategy_docs untouched",
      cleanup_commands_allowed: false
    },
    next_allowed_action_panel: {
      directive: "AWAIT OPERATOR/CHATGPT AUDIT_OF_0161_EVIDENCE_BEFORE_ANY_NEXT_TASK",
      future_task: "0162 Content Studio Rebuild only after audit"
    }
  },
  screens: [
    {
      screen_id: "command_center",
      title: "Command Center",
      purpose: "Global operational status landing. State before action.",
      primary_components: ["global_safety_ribbon", "command_center_status_header", "blocked_reason_stack", "kill_switch_indicator"],
      required_banners: ["LOCAL_ONLY", "KILL_SWITCH_ACTIVE", "LIVE_DISABLED"],
      required_status_tokens: ["PASS", "DEGRADED", "BLOCKED", "KILL_SWITCH_ACTIVE"],
      evidence_refs: ["evidence_vault_link"],
      blocked_reasons: ["Live posting disabled by kill switch", "Awaiting operator audit before next task"],
      blocked_action_policy: "no_live_action",
      redaction_state: "no_secrets",
      forbidden_controls: ["publish", "schedule", "connect", "oauth", "one_button_publish_all"],
      screenshot_safe_behavior: "redacted_no_secrets_no_false_readiness"
    },
    {
      screen_id: "content_lane_control",
      title: "Content Lane Control",
      purpose: "Lane separation and lane policy. No lane mixing.",
      primary_components: ["content_lane_badge", "not_public_postable_banner", "blocked_reason_stack"],
      required_banners: ["NOT_PUBLIC_POSTABLE", "REVIEW_ONLY"],
      required_status_tokens: ["NOT_PUBLIC_POSTABLE", "MANUAL_ONLY", "BLOCKED"],
      evidence_refs: ["lane_policy_ref"],
      blocked_reasons: ["Artifact-backed lane blocked until real approved artifacts exist", "Lane mixing blocked"],
      blocked_action_policy: "no_lane_mixing",
      redaction_state: "no_secrets",
      forbidden_controls: ["publish", "schedule", "connect", "oauth", "one_button_publish_all", "lane_mix_enable"],
      screenshot_safe_behavior: "redacted_no_secrets_no_false_readiness"
    },
    {
      screen_id: "daily_content_studio",
      title: "Daily Content Studio",
      purpose: "Daily run packet view, review-only. No final copy generation.",
      primary_components: ["draft_inspector_panel", "limitation_strip", "not_public_postable_banner", "manual_review_required_banner"],
      required_banners: ["NOT_PUBLIC_POSTABLE", "REVIEW_ONLY", "MANUAL_REVIEW_REQUIRED"],
      required_status_tokens: ["REVIEW_REQUIRED", "NOT_PUBLIC_POSTABLE", "DEGRADED"],
      evidence_refs: ["source_lineage_ref"],
      blocked_reasons: ["Draft requires source and limitation context before review can complete"],
      blocked_action_policy: "no_final_copy_generation",
      redaction_state: "no_secrets_no_final_copy",
      forbidden_controls: ["publish", "schedule", "connect", "oauth", "one_button_publish_all", "final_copy_generation"],
      screenshot_safe_behavior: "redacted_no_secrets_no_false_readiness"
    },
    {
      screen_id: "draft_inspector",
      title: "Draft Inspector",
      purpose: "One draft deep: source/lineage, draft/review text, guardrails/limitations.",
      primary_components: ["source_lineage_panel", "draft_inspector_panel", "claim_risk_panel", "limitation_strip"],
      required_banners: ["NOT_PUBLIC_POSTABLE", "MANUAL_REVIEW_REQUIRED"],
      required_status_tokens: ["REVIEW_REQUIRED", "DEGRADED", "BLOCKED"],
      evidence_refs: ["per_claim_source_ref"],
      blocked_reasons: ["Unsupported numeric/current claim must be sourced before review"],
      blocked_action_policy: "no_public_ready_state",
      redaction_state: "no_secrets",
      forbidden_controls: ["publish", "schedule", "connect", "oauth", "one_button_publish_all", "approve_public_ready"],
      screenshot_safe_behavior: "redacted_no_secrets_no_false_readiness"
    },
    {
      screen_id: "grounded_news_angle_lab",
      title: "Grounded News Angle Lab",
      purpose: "Grounded-news angles from supplied sources. News is a hook, not a signal.",
      primary_components: ["evidence_link_card", "proxy_only_warning", "limitation_strip", "not_public_postable_banner"],
      required_banners: ["PROXY_ONLY", "NOT_PUBLIC_POSTABLE", "NO_SIGNAL_LANGUAGE"],
      required_status_tokens: ["PROXY_ONLY", "REVIEW_REQUIRED", "DEGRADED"],
      evidence_refs: ["angle_citation_ref"],
      blocked_reasons: ["Current source metadata must be supplied externally; no repo web/search call"],
      blocked_action_policy: "no_repo_web_search_call",
      redaction_state: "no_secrets",
      forbidden_controls: ["publish", "schedule", "connect", "oauth", "one_button_publish_all", "repo_web_search_call"],
      screenshot_safe_behavior: "redacted_no_secrets_no_false_readiness"
    },
    {
      screen_id: "publish_readiness_tower",
      title: "Publish Readiness Tower",
      purpose: "Dry-run readiness matrix and gates. Live disabled, credentials redacted.",
      primary_components: ["platform_readiness_card", "gate_card", "credential_redaction_badge", "publish_disabled_control"],
      required_banners: ["LIVE_DISABLED", "DRY_RUN_ONLY", "NOT_PUBLIC_POSTABLE", "SECRET_REDACTED"],
      required_status_tokens: ["LIVE_DISABLED", "DRY_RUN_ONLY", "BLOCKED", "SECRET_REDACTED"],
      evidence_refs: ["readiness_evidence_ref"],
      blocked_reasons: ["Platform API disabled", "Scheduler disabled", "Manual approval required", "One-button publish-all disabled"],
      blocked_action_policy: "no_publish_all",
      redaction_state: "credentials_redacted_no_values",
      forbidden_controls: ["publish", "schedule", "connect", "oauth", "one_button_publish_all"],
      screenshot_safe_behavior: "redacted_no_secrets_no_false_readiness"
    },
    {
      screen_id: "telegram_pilot_gate",
      title: "Telegram Pilot Gate",
      purpose: "Read-only redacted gate status. No live calls from the UI.",
      primary_components: ["telegram_gate_stepper", "credential_redaction_badge", "gate_card", "publish_disabled_control"],
      required_banners: ["SECRET_REDACTED", "LIVE_DISABLED", "API_VALIDATED_NO_POST", "CHANNEL_PERMISSION_UNVALIDATED"],
      required_status_tokens: ["CREDENTIAL_PRESENT_REDACTED", "API_VALIDATED_NO_POST", "CHANNEL_PERMISSION_UNVALIDATED", "LIVE_DISABLED"],
      evidence_refs: ["gate_evidence_ref"],
      blocked_reasons: ["Bot token presence redacted only", "Target channel presence redacted only", "Channel write permission unvalidated", "Next gate required before posting"],
      blocked_action_policy: "no_getme_no_sendmessage_no_post",
      redaction_state: "token_chatid_never_shown",
      forbidden_controls: ["publish", "schedule", "connect", "oauth", "one_button_publish_all", "getme_call", "sendmessage", "live_adapter"],
      gate_steps: [
        { step: "presence_check", state: "CREDENTIAL_PRESENT_REDACTED" },
        { step: "official_docs", state: "PASS" },
        { step: "getme_validation_no_post", state: "API_VALIDATED_NO_POST" },
        { step: "channel_permission_future", state: "CHANNEL_PERMISSION_UNVALIDATED" },
        { step: "explicit_go_future", state: "LIVE_DISABLED" }
      ],
      screenshot_safe_behavior: "redacted_no_secrets_no_false_readiness"
    },
    {
      screen_id: "approval_queue",
      title: "Approval Queue",
      purpose: "Human review queue. Human approval only, no auto-approval.",
      primary_components: ["approval_decision_card", "audit_timeline", "manual_review_required_banner"],
      required_banners: ["MANUAL_REVIEW_REQUIRED", "REVIEW_ONLY"],
      required_status_tokens: ["REVIEW_REQUIRED", "MANUAL_ONLY", "PASS", "BLOCKED"],
      evidence_refs: ["per_item_evidence_ref"],
      blocked_reasons: ["Decision requires a human reviewer", "No auto-approval path"],
      blocked_action_policy: "no_auto_approval",
      redaction_state: "history_redacted_safe",
      forbidden_controls: ["publish", "schedule", "connect", "oauth", "one_button_publish_all", "auto_approval"],
      screenshot_safe_behavior: "redacted_no_secrets_no_false_readiness"
    },
    {
      screen_id: "content_calendar",
      title: "Content Calendar",
      purpose: "Planning calendar; never public-ready. No scheduling or live state.",
      primary_components: ["content_lane_badge", "not_public_postable_banner", "manual_review_required_banner"],
      required_banners: ["NOT_PUBLIC_POSTABLE", "REVIEW_ONLY", "MANUAL_REVIEW_REQUIRED"],
      required_status_tokens: ["NOT_PUBLIC_POSTABLE", "REVIEW_REQUIRED", "MANUAL_ONLY"],
      evidence_refs: ["item_source_needed_ref"],
      blocked_reasons: ["No scheduled state", "No system live-publish", "No auto-publish-ready", "No public-ready marking"],
      blocked_action_policy: "no_scheduled_or_live_state",
      redaction_state: "no_secrets",
      allowed_item_states: ["idea", "source-needed", "draft-review", "blocked", "operator-approved-for-manual", "manually-posted", "metrics-entered"],
      forbidden_controls: ["publish", "schedule", "connect", "oauth", "one_button_publish_all", "scheduled_post", "auto_publish", "live_state"],
      screenshot_safe_behavior: "redacted_no_secrets_no_false_readiness"
    },
    {
      screen_id: "evidence_vault",
      title: "Evidence Vault",
      purpose: "Evidence, lineage, data sufficiency, freshness, missing data — all visible.",
      primary_components: ["evidence_link_card", "source_lineage_panel", "data_sufficiency_matrix", "freshness_chip", "missing_data_row", "audit_timeline"],
      required_banners: ["PROXY_ONLY", "MISSING_DATA_VISIBLE", "DQR_BLOCKING"],
      required_status_tokens: ["PASS", "DEGRADED", "PROXY_ONLY", "STALE", "UNKNOWN", "DQR_BLOCKING"],
      evidence_refs: ["artifact_evidence_ref"],
      blocked_reasons: ["Data quality / sufficiency blocking on at least one dimension"],
      blocked_action_policy: "no_live_data_fetch",
      redaction_state: "no_raw_vendor_data_references_only",
      forbidden_controls: ["publish", "schedule", "connect", "oauth", "one_button_publish_all", "live_data_fetch"],
      screenshot_safe_behavior: "redacted_no_secrets_no_false_readiness"
    },
    {
      screen_id: "visual_export_studio",
      title: "Visual Export Studio",
      purpose: "Screenshot/briefing-safe export of redacted views. No file/network export.",
      primary_components: ["screenshot_safe_watermark", "screenshot_safe_toggle", "visual_export_preview"],
      required_banners: ["SECRET_REDACTED", "NOT_PUBLIC_POSTABLE", "LIVE_DISABLED"],
      required_status_tokens: ["SECRET_REDACTED", "NOT_PUBLIC_POSTABLE", "LIVE_DISABLED"],
      evidence_refs: ["report_card_evidence_ref"],
      blocked_reasons: ["No unredacted capture", "No file write", "No network export"],
      blocked_action_policy: "no_unredacted_capture",
      redaction_state: "redact_secrets_env_responses_urls",
      forbidden_controls: ["publish", "schedule", "connect", "oauth", "one_button_publish_all", "file_write", "network_export", "unredacted_capture"],
      screenshot_safe_behavior: "redacted_no_secrets_no_false_readiness"
    },
    {
      screen_id: "settings_safety_policy",
      title: "Settings / Safety Policy",
      purpose: "Read-only posture and policy. No credentials, no API or live toggles.",
      primary_components: ["safety_policy_panel", "posture_summary_row", "kill_switch_indicator"],
      required_banners: ["LIVE_DISABLED", "KILL_SWITCH_ACTIVE", "DRY_RUN_ONLY"],
      required_status_tokens: ["LIVE_DISABLED", "KILL_SWITCH_ACTIVE", "DRY_RUN_ONLY"],
      evidence_refs: [],
      blocked_reasons: ["Policy display only", "No credential values displayed", "No API or live publishing toggles"],
      blocked_action_policy: "no_credential_display",
      redaction_state: "no_credentials_displayed",
      policy_flags: [
        { name: "live_posting_enabled", state: "false", read_only: true },
        { name: "scheduler_enabled", state: "false", read_only: true },
        { name: "scraping_enabled", state: "false", read_only: true },
        { name: "kill_switch", state: "active", read_only: true }
      ],
      forbidden_controls: ["publish", "schedule", "connect", "oauth", "one_button_publish_all", "api_controls", "live_publishing_toggle", "credential_display"],
      screenshot_safe_behavior: "redacted_no_secrets_no_false_readiness"
    }
  ]
};
