import React from 'react';
import {AbsoluteFill, Img, interpolate, spring, staticFile, useCurrentFrame, useVideoConfig} from 'remotion';

export const BRAND = {navy:'#06121c', ink:'#f5f0e6', muted:'#a8b8c4', teal:'#42d5b8', copper:'#e6a45e', red:'#f37d73', line:'rgba(168,184,196,.25)'};
export const clamp = {extrapolateLeft:'clamp' as const, extrapolateRight:'clamp' as const};
export const asset = (name:string) => staticFile(`assets/${name}`);

export const Canvas:React.FC<{children:React.ReactNode; portrait?:boolean; style?:React.CSSProperties}> = ({children,portrait=false,style}) => <AbsoluteFill style={{background:BRAND.navy,color:BRAND.ink,overflow:'hidden',fontFamily:'Arial, Helvetica, sans-serif',padding:portrait?'76px 54px 116px':'54px 68px 70px',...style}}>{children}</AbsoluteFill>;
export const Brand:React.FC<{portrait?:boolean}> = ({portrait=false}) => <div style={{position:'absolute',right:portrait?48:60,top:portrait?42:34,zIndex:60,fontSize:portrait?18:15,fontWeight:900,letterSpacing:2.1}}>CAPITAL <span style={{color:BRAND.teal}}>CHRONICLE</span></div>;
export const Source:React.FC<{children:React.ReactNode;portrait?:boolean;dark?:boolean}> = ({children,portrait=false,dark=true}) => <div style={{position:'absolute',left:portrait?48:64,right:portrait?48:64,bottom:portrait?38:25,zIndex:90,fontSize:portrait?22:18,lineHeight:1.25,fontWeight:650,color:dark?'#d9e4e9':BRAND.navy,textShadow:dark?'0 2px 8px #000':'none'}}>{children}</div>;
export const Eyebrow:React.FC<{children:React.ReactNode;portrait?:boolean}> = ({children,portrait=false}) => <div style={{color:BRAND.teal,fontSize:portrait?21:17,fontWeight:900,letterSpacing:portrait?3.2:2.5,textTransform:'uppercase'}}>{children}</div>;
export const Title:React.FC<{children:React.ReactNode;size:number;maxWidth?:number|string;style?:React.CSSProperties}> = ({children,size,maxWidth='100%',style}) => <div style={{color:BRAND.ink,fontSize:size,lineHeight:1.02,fontWeight:900,letterSpacing:'-.035em',maxWidth,overflowWrap:'break-word',...style}}>{children}</div>;
export const Enter:React.FC<{children:React.ReactNode;delay?:number;axis?:'x'|'y';distance?:number;style?:React.CSSProperties}> = ({children,delay=0,axis='y',distance=28,style}) => {const frame=useCurrentFrame();const {fps}=useVideoConfig();const p=spring({frame:frame-delay,fps,config:{damping:20,stiffness:145,mass:.85}});return <div style={{opacity:p,transform:axis==='x'?`translateX(${(1-p)*distance}px)`:`translateY(${(1-p)*distance}px)`,...style}}>{children}</div>};
export const Photo:React.FC<{name:string;position?:string;fit?:'cover'|'contain';style?:React.CSSProperties}> = ({name,position='center',fit='cover',style}) => {const frame=useCurrentFrame();const {durationInFrames}=useVideoConfig();const scale=interpolate(frame,[0,durationInFrames],[1,1.05],clamp);return <Img src={asset(name)} style={{width:'100%',height:'100%',objectFit:fit,objectPosition:position,transform:`scale(${scale})`,...style}}/>};
export const Scrim:React.FC<{opacity?:number}> = ({opacity=.58}) => <AbsoluteFill style={{background:`linear-gradient(110deg,rgba(3,10,16,${Math.min(.94,opacity+.22)}) 0%,rgba(3,10,16,${opacity}) 48%,rgba(3,10,16,.12) 100%)`}}/>;
export const Pill:React.FC<{children:React.ReactNode;color?:string}> = ({children,color=BRAND.teal}) => <div style={{display:'inline-flex',padding:'8px 13px',border:`1px solid ${color}`,borderRadius:99,color,fontWeight:850,fontSize:18,letterSpacing:.2}}>{children}</div>;
export const Grid:React.FC = () => <AbsoluteFill style={{opacity:.15,backgroundImage:'linear-gradient(rgba(66,213,184,.22) 1px,transparent 1px),linear-gradient(90deg,rgba(66,213,184,.22) 1px,transparent 1px)',backgroundSize:'52px 52px',maskImage:'linear-gradient(180deg,transparent,black 22%,black 75%,transparent)'}}/>;

export type CurvePoint={label:string;value:number;previous:number};
export const YieldCurve:React.FC<{points:CurvePoint[];portrait?:boolean;showPrevious?:boolean;active?:number}> = ({points,portrait=false,showPrevious=true,active=-1}) => {const frame=useCurrentFrame();const {fps}=useVideoConfig();const w=portrait?900:1120,h=portrait?500:455,min=3.65,max=5.2;const x=(i:number)=>42+i*(w-84)/(points.length-1);const y=(v:number)=>36+(max-v)*(h-78)/(max-min);const reveal=interpolate(frame,[5,fps*1.4],[0,1],clamp);const current=points.map((p,i)=>`${x(i)},${y(p.value)}`).join(' ');const prior=points.map((p,i)=>`${x(i)},${y(p.previous)}`).join(' ');return <div style={{width:w,height:h,position:'relative'}}><svg width={w} height={h} style={{overflow:'visible'}}>{[4,4.5,5].map(v=><g key={v}><line x1={42} x2={w-42} y1={y(v)} y2={y(v)} stroke={BRAND.line}/><text x={0} y={y(v)+7} fill={BRAND.muted} fontSize={18}>{v.toFixed(1)}%</text></g>)}{showPrevious&&<polyline points={prior} fill="none" stroke={BRAND.muted} strokeWidth={4} strokeDasharray="9 10" opacity={reveal*.72}/>}<polyline points={current} fill="none" stroke={BRAND.teal} strokeWidth={7} strokeLinejoin="round" pathLength={1} strokeDasharray={1} strokeDashoffset={1-reveal}/>{points.map((p,i)=><g key={p.label} opacity={reveal}><circle cx={x(i)} cy={y(p.value)} r={active===i?13:8} fill={active===i?BRAND.copper:BRAND.teal}/><text x={x(i)} y={h-12} fill={BRAND.ink} fontSize={18} textAnchor="middle" fontWeight={750}>{p.label}</text>{(active===i||i===0||i===points.length-1)&&<text x={x(i)} y={y(p.value)-18} fill={active===i?BRAND.copper:BRAND.ink} fontSize={22} textAnchor="middle" fontWeight={900}>{p.value.toFixed(2)}%</text>}</g>)}</svg></div>};

export const SplitMechanism:React.FC<{portrait?:boolean}> = ({portrait=false}) => {const frame=useCurrentFrame();const a=spring({frame:frame-8,fps:30,config:{damping:20}});const b=spring({frame:frame-48,fps:30,config:{damping:20}});const card=(label:string,sub:string,color:string,p:number)=><div style={{flex:1,padding:portrait?'30px 26px':'26px 30px',border:`2px solid ${color}`,borderRadius:18,opacity:p,transform:`translateY(${(1-p)*30}px)`,background:'rgba(6,18,28,.88)'}}><div style={{fontSize:portrait?35:30,fontWeight:900,color}}>{label}</div><div style={{fontSize:portrait?24:21,lineHeight:1.25,color:BRAND.muted,marginTop:12}}>{sub}</div></div>;return <div style={{display:'flex',gap:portrait?20:26,flexDirection:portrait?'column':'row'}}>{card('Expected short-rate path','What markets think policy and inflation will do.',BRAND.teal,a)}{card('Term premium','Extra compensation for holding duration. It is estimated, not observed.',BRAND.copper,b)}</div>};
