"""V5 TypeScript Adapter Codegen for Dispatch Outbox Dry Run Packet."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
JSON_PATH = ROOT / "docs" / "automation" / "V6_APPROVAL_PACKET_PREVIEW_TO_DISPATCH_OUTBOX_DRY_RUN" / "approval_packet_preview_to_dispatch_outbox_dry_run_packet.json"
TS_PATH = ROOT / "ui" / "contentops_v5" / "src" / "data" / "dispatchOutboxDryRunAdapter.ts"


def generate_or_check_adapter(verify_only: bool = False) -> dict:
    if not JSON_PATH.exists():
        raise FileNotFoundError(f"JSON packet not found at {JSON_PATH}")

    with open(JSON_PATH, "r", encoding="utf-8") as f:
        packet = json.load(f)

    # Convert the JSON packet into a static TypeScript structure
    # Use exact type formatting so we preserve strong typings
    ts_content = f"""// Capital Chronicle ContentOps V5 Adapter
// Automatically generated by dispatch_outbox_dry_run_v5_adapter_codegen_v6.py. Do not edit manually.

export interface DryRunOutboxEntry {{
  platform_id: string;
  source_approval_target_key: string;
  adapter_class: string;
  dry_run_entry_id: string;
  dry_run_payload_text: string;
  dry_run_payload_hash: string;
  source_approval_payload_hash: string;
  destination_binding_status: string;
  credential_handle_status: string;
  request_method_preview: string;
  request_url_preview_status: string;
  request_body_hash_preview: string;
  executable: boolean;
  dispatchable: boolean;
  approved: boolean;
  approval_required: boolean;
  blocked_reason?: string;
  deferred_reason?: string;
  no_public_url_claim: boolean;
  no_metrics_claim: boolean;
  no_network_request_made: boolean;
  no_secret_material_present: boolean;
}}

export interface DispatchOutboxDryRunPacket {{
  packet_kind: "approval_packet_preview_to_dispatch_outbox_dry_run_v0";
  dispatch_outbox_dry_run_status: "dispatch_outbox_dry_run_created_for_operator_review";
  dry_run_outbox_package_created: boolean;
  dry_run_entries_created: boolean;
  executable_outbox_entry_created: boolean;
  real_outbox_entry_created: boolean;
  dispatch_outbox_ready: boolean;
  dispatch_attempted: boolean;
  dispatch_request_count: number;
  webhook_request_count: number;
  platform_api_request_count: number;
  scheduler_enabled: boolean;
  retry_enabled: boolean;
  kill_switch_required: boolean;
  kill_switch_active: boolean;
  exact_payload_hashes_preserved: boolean;
  actual_operator_approval_recorded: boolean;
  approval_ledger_entry_created: boolean;
  approval_record_created: boolean;
  approval_signature_present: boolean;
  approval_signature_required: boolean;
  platform_payloads_approved: boolean;
  final_article_approved: boolean;
  ready_for_auto_publish: boolean;
  ready_for_dispatch: boolean;
  live_action_allowed: boolean;
  public_url_verification_performed: boolean;
  llm_provider_call_made: boolean;
  provider_call_made: boolean;
  platform_api_used: boolean;
  network_call_made: boolean;
  public_url_fetch_made: boolean;
  env_value_read_made: boolean;
  credential_read_made: boolean;
  browser_session_used: boolean;
  live_publish_performed_by_contentops: boolean;
  enabled_publish_send_dispatch_approve_controls: boolean;
  forbidden_financial_advice_or_signal_wording_present: boolean;
  dispatch_outbox_dry_run_packet_id: string;
  exact_payload_hash: string;
  source_approval_preview_packet_id: string;
  source_approval_preview_exact_payload_hash: string;
  source_final_review_packet_id: string;
  source_final_review_hash: string;
  source_local_draft_preview_packet_id: string;
  source_draft_review_packet_id: string;
  source_local_draft_hash: string;
  dry_run_entries: {{ [key: string]: DryRunOutboxEntry }};
  task_label: string;
}}

export const dispatchOutboxDryRunPacket: DispatchOutboxDryRunPacket = {json.dumps(packet, indent=2)};
"""

    if verify_only:
        if not TS_PATH.exists():
            return {"adapter_in_sync": False, "packet_hash_matches": False}
        current_content = TS_PATH.read_text(encoding="utf-8")
        in_sync = current_content.strip() == ts_content.strip()
        return {"adapter_in_sync": in_sync, "packet_hash_matches": in_sync}

    TS_PATH.write_text(ts_content, encoding="utf-8")
    print(f"Generated TypeScript adapter at: {TS_PATH}")
    return {"adapter_in_sync": True, "packet_hash_matches": True}


if __name__ == "__main__":
    generate_or_check_adapter()
