"""V5 TypeScript Adapter Codegen for Dispatch Outbox Operator Recovery Packet."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
JSON_PATH = ROOT / "docs" / "automation" / "V6_DISPATCH_OUTBOX_DRY_RUN_OPERATOR_RUNBOOK_AND_RECOVERY" / "dispatch_outbox_dry_run_operator_recovery_packet.json"
TS_PATH = ROOT / "ui" / "contentops_v5" / "src" / "data" / "dispatchOutboxOperatorRecoveryAdapter.ts"


def generate_or_check_recovery_adapter(verify_only: bool = False) -> dict:
    if not JSON_PATH.exists():
        raise FileNotFoundError(f"JSON packet not found at {JSON_PATH}")

    with open(JSON_PATH, "r", encoding="utf-8") as f:
        packet = json.load(f)

    ts_content = f"""// Capital Chronicle ContentOps V5 Adapter
// Automatically generated by dispatch_outbox_operator_recovery_v5_adapter_codegen_v6.py. Do not edit manually.

export interface OperatorPreflightChecklist {{
  check_id: string;
  label: string;
  status: string;
}}

export interface ManualDispatchFallbackStep {{
  step_id: string;
  action: string;
  target: string;
}}

export interface DryRunReplayStep {{
  replay_id: string;
  action: string;
  status: string;
}}

export interface RollbackAndStopCondition {{
  condition_id: string;
  event: string;
  action: string;
}}

export interface FailureModeMatrix {{
  failure_mode: string;
  impact: string;
  recovery_action: string;
}}

export interface EvidenceCollectionChecklist {{
  item_id: string;
  label: string;
  status: string;
}}

export interface DispatchOutboxOperatorRecoveryPacket {{
  packet_kind: "dispatch_outbox_dry_run_operator_runbook_and_recovery_v0";
  operator_recovery_status: "operator_recovery_runbook_created_for_review";
  recovery_runbook_created: boolean;
  manual_fallback_plan_created: boolean;
  rollback_plan_created: boolean;
  dry_run_replay_plan_created: boolean;
  failure_mode_matrix_created: boolean;
  evidence_collection_checklist_created: boolean;
  dispatch_preflight_checklist_created: boolean;
  executable_outbox_entry_created: boolean;
  real_outbox_entry_created: boolean;
  dispatch_outbox_ready: boolean;
  dispatch_attempted: boolean;
  dispatch_request_count: number;
  webhook_request_count: number;
  platform_api_request_count: number;
  scheduler_enabled: boolean;
  retry_enabled: boolean;
  kill_switch_required: boolean;
  kill_switch_active: boolean;
  actual_operator_approval_recorded: boolean;
  approval_ledger_entry_created: boolean;
  approval_record_created: boolean;
  approval_signature_present: boolean;
  approval_signature_required: boolean;
  platform_payloads_approved: boolean;
  final_article_approved: boolean;
  ready_for_auto_publish: boolean;
  ready_for_dispatch: boolean;
  live_action_allowed: boolean;
  public_url_verification_performed: boolean;
  llm_provider_call_made: boolean;
  provider_call_made: boolean;
  platform_api_used: boolean;
  network_call_made: boolean;
  public_url_fetch_made: boolean;
  env_value_read_made: boolean;
  credential_read_made: boolean;
  browser_session_used: boolean;
  live_publish_performed_by_contentops: boolean;
  enabled_publish_send_dispatch_approve_controls: boolean;
  forbidden_financial_advice_or_signal_wording_present: boolean;
  dispatch_outbox_operator_recovery_packet_id: string;
  exact_payload_hash: string;
  source_dispatch_outbox_dry_run_packet_id: string;
  source_dispatch_outbox_dry_run_exact_hash: string;
  source_approval_preview_packet_id: string;
  source_approval_preview_exact_hash: string;
  source_final_review_packet_id: string;
  source_final_review_hash: string;
  operator_preflight_checklist: OperatorPreflightChecklist[];
  manual_dispatch_fallback_steps: ManualDispatchFallbackStep[];
  dry_run_replay_steps: DryRunReplayStep[];
  rollback_and_stop_conditions: RollbackAndStopCondition[];
  failure_mode_matrix: FailureModeMatrix[];
  evidence_collection_checklist: EvidenceCollectionChecklist[];
  platform_specific_recovery_notes: {{ [key: string]: string }};
  blocked_until_explicit_live_scope: boolean;
  task_label: string;
}}

export const dispatchOutboxOperatorRecoveryPacket: DispatchOutboxOperatorRecoveryPacket = {json.dumps(packet, indent=2)};
"""

    if verify_only:
        if not TS_PATH.exists():
            return {"adapter_in_sync": False, "packet_hash_matches": False}
        current_content = TS_PATH.read_text(encoding="utf-8")
        in_sync = current_content.strip() == ts_content.strip()
        return {"adapter_in_sync": in_sync, "packet_hash_matches": in_sync}

    TS_PATH.write_text(ts_content, encoding="utf-8")
    print(f"Generated TypeScript adapter at: {TS_PATH}")
    return {"adapter_in_sync": True, "packet_hash_matches": True}


if __name__ == "__main__":
    generate_or_check_recovery_adapter()
