"""Deterministic static TypeScript exporter for the Content Intent Gate Precheck Packet.

Part of TASK_CONTENTOPS_0175BK_CONTENT_INTENT_GATE_PRECHECK_TO_V5_INTENT_QUEUE_BINDING_V0.
Exports the 0175BJ Content Intent Gate Precheck packet into V5 TypeScript format.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

ARTIFACT = (
    ROOT / "ui" / "contentops_v5" / "src" / "data" / "contentIntentGatePrecheckPacket.ts"
)

HEADER = (
    "// AUTO-GENERATED by tools/export_v5_content_intent_gate_precheck_packet.py -- do not edit by hand.\n"
    "// Local-only, evidence-only, no-grant projection. Defines a frozen read-only packet.\n"
)

# Literal substrings that must never appear in the generated artifact.
FORBIDDEN_TOKENS = (
    "process.env", ".env", "API key", "bearer token", "credential string",
    "buy", "sell", "hold", "guaranteed", "price target", "order execution"
)


def load_packet() -> dict[str, Any]:
    """Loads the 0175BJ packet from JSON or regenerates it from the 0175BH brief review packet fallback."""
    json_path = ROOT / "docs" / "automation" / "0175BJ" / "editorial_brief_review_to_content_intent_gate_precheck_packet.json"
    if json_path.is_file():
        with open(json_path, "r", encoding="utf-8") as f:
            return json.load(f)

    bh_path = ROOT / "docs" / "automation" / "0175BH" / "lifecycle_intake_bridge_to_editorial_brief_review_packet.json"
    with open(bh_path, "r", encoding="utf-8") as f:
        bh_packet = json.load(f)

    from live_contentops.editorial_brief_review_to_content_intent_gate_precheck import create_content_intent_gate_precheck
    return create_content_intent_gate_precheck(bh_packet)


def render_ts(packet: dict[str, Any]) -> str:
    """Render the canonical, deterministic TS artifact text for a content intent gate precheck packet."""
    body = json.dumps(packet, indent=2, sort_keys=True, ensure_ascii=False)
    return (
        HEADER
        + "export const contentIntentGatePrecheckPacket = " + body + " as const;\n"
    )


def _safety_scan(text: str) -> list[str]:
    # We allow the forbidden keywords ONLY when they appear as strings inside the disallowed_outputs lists.
    # To implement this scan correctly, we replace the allowed list value first, then check remaining hits.
    clean_text = text
    # Replace the disallowed outputs list block with dummy values
    for word in ("buy", "sell", "hold", "price target", "prediction", "headline", "hook", "caption", "draft_paragraph", "platform_copy"):
        clean_text = clean_text.replace(f'"{word}"', '"_redacted_"')
        clean_text = clean_text.replace(f'"{word}_sell_hold_sizing_signal_language"', '"_redacted_"')
        clean_text = clean_text.replace(f'"buy_{word}_hold_sizing_signal_language"', '"_redacted_"')
        clean_text = clean_text.replace(f'"buy_sell_{word}_sizing_signal_language"', '"_redacted_"')
        clean_text = clean_text.replace(f'"{word}_values"', '"_redacted_"')
        clean_text = clean_text.replace(f'"{word}_target"', '"_redacted_"')
        clean_text = clean_text.replace(f'"target_{word}"', '"_redacted_"')
        clean_text = clean_text.replace(f'"{word}_paragraph"', '"_redacted_"')
    return [token for token in FORBIDDEN_TOKENS if token in clean_text]


def _build_expected() -> str:
    packet = load_packet()
    text = render_ts(packet)
    hits = _safety_scan(text)
    if hits:
        raise SystemExit("SAFETY_SCAN_FAILED tokens=" + ",".join(hits))
    return text


def cmd_write() -> int:
    text = _build_expected()
    ARTIFACT.parent.mkdir(parents=True, exist_ok=True)
    ARTIFACT.write_text(text, encoding="utf-8", newline="\n")
    print("WROTE " + str(ARTIFACT.relative_to(ROOT)))
    print("BYTES " + str(len(text.encode("utf-8"))))
    print("SAFETY_SCAN_CLEAN")
    return 0


def cmd_check() -> int:
    expected = _build_expected()
    if not ARTIFACT.is_file():
        print("STALE artifact missing: " + str(ARTIFACT.relative_to(ROOT)))
        return 1
    actual = ARTIFACT.read_text(encoding="utf-8")
    if actual != expected:
        print("STALE artifact differs from regenerated output; run export script")
        return 1
    print("CHECK_OK artifact is byte-identical to regenerated output")
    print("SAFETY_SCAN_CLEAN")
    return 0


def main(argv: list[str]) -> int:
    if "--check" in argv:
        return cmd_check()
    # Default behavior is to write the file
    return cmd_write()


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
