"""Deterministic static TypeScript exporter for the Draft Eligibility Gate Precheck Packet.

Part of TASK_CONTENTOPS_0175BT_DRAFT_ELIGIBILITY_GATE_TO_V5_READONLY_STATUS_PANEL_BINDING_V0.
Exports the 0175BS Draft Eligibility Gate Precheck packet into V5 TypeScript format.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

ARTIFACT = (
    ROOT / "ui" / "contentops_v5" / "src" / "data" / "draftEligibilityGatePrecheckPacket.ts"
)

HEADER = (
    "// AUTO-GENERATED by tools/export_v5_draft_eligibility_gate_precheck_packet.py -- do not edit by hand.\n"
    "// Local-only, readonly, no-capture/no-generation projection.\n"
)

FORBIDDEN_TOKENS = (
    "process.env", ".env", "API key", "bearer token", "credential string",
    "buy", "sell", "hold", "price target", "target price", "signal",
    "prediction", "guaranteed", "order", "fill", "PnL", "publish now",
    "post now", "dispatch live", "headline", "hook", "caption",
    "draft paragraph", "draft_paragraph", "platform copy", "platform_copy",
    "thesis", "recommendation", "<input", "<textarea", "contentEditable",
    "onChange=", "onSubmit=", "capture now", "submit", "save",
    "approve button", "generate control",
)

ALLOWED_POLICY_TOKENS = (
    "actual_input_capture",
    "editable_input_fields",
    "form_submission",
    "save_capture_approve_generate_controls",
    "operator_prose_generation",
    "content_generation",
    "draft_generation",
    "headline_hook_caption_generation",
    "platform_copy_generation",
    "ai_writer_generation",
    "draft_storage",
    "public_posting",
    "live_dispatch",
    "provider_or_platform_api_call",
    "buy_sell_hold_sizing_signal_language",
    "headline",
    "hook",
    "caption",
    "draft_paragraph",
    "platform_copy",
    "prediction",
    "recommendation",
    "narrative_thesis",
    "draft_generation_enabled",
    "headline_generation_enabled",
    "hook_generation_enabled",
    "caption_generation_enabled",
    "platform_copy_generation_enabled",
    "ai_writer_generation_enabled",
    "public_postable",
    "dispatch_ready",
    "draft_storage_enabled",
    "operator_input_capture_enabled",
    "validation_enabled",
    "actual_operator_input_capture_enabled",
    "editable_ui_enabled",
    "persistence_enabled",
    "draft_truth_promoted",
)


def load_packet() -> dict[str, Any]:
    """Loads the 0175BS Draft Eligibility Gate Precheck packet."""
    json_path = (
        ROOT
        / "docs"
        / "automation"
        / "0175BS"
        / "supervised_input_stub_to_draft_eligibility_gate_precheck_packet.json"
    )
    with open(json_path, "r", encoding="utf-8") as f:
        return json.load(f)


def render_ts(packet: dict[str, Any]) -> str:
    """Render deterministic TS artifact text for the draft eligibility packet."""
    body = json.dumps(packet, indent=2, sort_keys=True, ensure_ascii=False)
    return HEADER + "export const draftEligibilityGatePrecheckPacket = " + body + " as const;\n"


def _safety_scan(text: str) -> list[str]:
    clean_text = text
    for token in ALLOWED_POLICY_TOKENS:
        clean_text = clean_text.replace(f'\"{token}\"', '\"_redacted_\"')
    clean_text = clean_text.replace("buy_sell_hold", "_redacted_")
    hits: list[str] = []
    for token in FORBIDDEN_TOKENS:
        if token.replace(" ", "").replace("_", "").isalnum():
            pattern = r"(?<![A-Za-z0-9_])" + re.escape(token) + r"(?![A-Za-z0-9_])"
            if re.search(pattern, clean_text):
                hits.append(token)
        elif token in clean_text:
            hits.append(token)
    return hits


def _build_expected() -> str:
    packet = load_packet()
    text = render_ts(packet)
    hits = _safety_scan(text)
    if hits:
        raise SystemExit("SAFETY_SCAN_FAILED tokens=" + ",".join(hits))
    return text


def cmd_write() -> int:
    text = _build_expected()
    ARTIFACT.parent.mkdir(parents=True, exist_ok=True)
    ARTIFACT.write_text(text, encoding="utf-8", newline="\n")
    print("WROTE " + str(ARTIFACT.relative_to(ROOT)))
    print("BYTES " + str(len(text.encode("utf-8"))))
    print("SAFETY_SCAN_CLEAN")
    return 0


def cmd_check() -> int:
    expected = _build_expected()
    if not ARTIFACT.is_file():
        print("STALE artifact missing: " + str(ARTIFACT.relative_to(ROOT)))
        return 1
    actual = ARTIFACT.read_text(encoding="utf-8")
    if actual != expected:
        print("STALE artifact differs from regenerated output; run export script")
        return 1
    print("CHECK_OK artifact is byte-identical to regenerated output")
    print("SAFETY_SCAN_CLEAN")
    return 0


def main(argv: list[str]) -> int:
    if "--check" in argv:
        return cmd_check()
    return cmd_write()


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
