// AUTO-GENERATED by tools/export_v5_content_intent_gate_precheck_packet.py -- do not edit by hand.
// Local-only, evidence-only, no-grant projection. Defines a frozen read-only packet.
export const contentIntentGatePrecheckPacket = {
  "allowed_next_step": "operator_must_sign_off_content_intent_gate_precheck_to_unlock_drafting",
  "blocked_reasons": [
    "operator_brief_review_pending",
    "content_intent_gate_locked_until_operator_review"
  ],
  "candidate_gate_items": [
    {
      "advisory_only": true,
      "allowed_next_step": "operator_must_review_metadata_before_intent_drafting",
      "blocked_reasons": [
        "waiting_for_operator_intent_review"
      ],
      "candidate_id": "STEP1_OFFICIAL_TEXT_LIVE_PROBE_MANIFEST_V1",
      "candidate_only": true,
      "content_intent_gate_status": "READY_FOR_OPERATOR_INTENT_REVIEW",
      "contract_name": null,
      "evidence_role": "manifest",
      "missing_requirements": [],
      "operator_review_required": true,
      "records_count": 6,
      "relative_path": "docs/research/database_foundation/pre_ia_acceleration/STEP1_OFFICIAL_TEXT_LIVE_PROBE_MANIFEST_V1.json",
      "source_family": "Official Text Spine"
    },
    {
      "advisory_only": true,
      "allowed_next_step": "operator_must_review_metadata_before_intent_drafting",
      "blocked_reasons": [
        "waiting_for_operator_intent_review"
      ],
      "candidate_id": "STEP1_OFFICIAL_TEXT_SPINE_CONTRACT_V1",
      "candidate_only": true,
      "content_intent_gate_status": "READY_FOR_OPERATOR_INTENT_REVIEW",
      "contract_name": "STEP1_OFFICIAL_TEXT_SPINE_CONTRACT_V1",
      "evidence_role": "contract",
      "missing_requirements": [],
      "operator_review_required": true,
      "records_count": 1,
      "relative_path": "docs/research/database_foundation/pre_ia_acceleration/STEP1_OFFICIAL_TEXT_SPINE_CONTRACT_V1.json",
      "source_family": "Official Text Spine"
    },
    {
      "advisory_only": true,
      "allowed_next_step": "operator_must_review_metadata_before_intent_drafting",
      "blocked_reasons": [
        "waiting_for_operator_intent_review"
      ],
      "candidate_id": "BEA_BLS_CENSUS_NORMALIZED_CONTRACT_V1",
      "candidate_only": true,
      "content_intent_gate_status": "READY_FOR_OPERATOR_INTENT_REVIEW",
      "contract_name": "BEA_BLS_CENSUS_NORMALIZED_CONTRACT_V1",
      "evidence_role": "contract",
      "missing_requirements": [],
      "operator_review_required": true,
      "records_count": 1,
      "relative_path": "docs/research/database_foundation/pre_ia_acceleration/BEA_BLS_CENSUS_NORMALIZED_CONTRACT_V1.json",
      "source_family": "US Macro"
    },
    {
      "advisory_only": true,
      "allowed_next_step": "operator_must_review_metadata_before_intent_drafting",
      "blocked_reasons": [
        "waiting_for_operator_intent_review"
      ],
      "candidate_id": "BEA_BLS_CENSUS_NORMALIZED_CANDIDATE_RECORDS_V1",
      "candidate_only": true,
      "content_intent_gate_status": "READY_FOR_OPERATOR_INTENT_REVIEW",
      "contract_name": null,
      "evidence_role": "candidates",
      "missing_requirements": [],
      "operator_review_required": true,
      "records_count": 9,
      "relative_path": "docs/research/database_foundation/pre_ia_acceleration/BEA_BLS_CENSUS_NORMALIZED_CANDIDATE_RECORDS_V1.json",
      "source_family": "US Macro"
    },
    {
      "advisory_only": true,
      "allowed_next_step": "operator_must_review_metadata_before_intent_drafting",
      "blocked_reasons": [
        "waiting_for_operator_intent_review"
      ],
      "candidate_id": "BROKER_PROXY_NO_VALUE_SNAPSHOT_MANIFEST_V1",
      "candidate_only": true,
      "content_intent_gate_status": "READY_FOR_OPERATOR_INTENT_REVIEW",
      "contract_name": null,
      "evidence_role": "manifest",
      "missing_requirements": [],
      "operator_review_required": true,
      "records_count": 1,
      "relative_path": "docs/research/database_foundation/pre_ia_acceleration/BROKER_PROXY_NO_VALUE_SNAPSHOT_MANIFEST_V1.json",
      "source_family": "Broker Proxy"
    },
    {
      "advisory_only": true,
      "allowed_next_step": "operator_must_review_metadata_before_intent_drafting",
      "blocked_reasons": [
        "waiting_for_operator_intent_review"
      ],
      "candidate_id": "DATABASE_FOUNDATION_TTL_FRESHNESS_POLICY_CONTRACT_V1",
      "candidate_only": true,
      "content_intent_gate_status": "READY_FOR_OPERATOR_INTENT_REVIEW",
      "contract_name": null,
      "evidence_role": "contract",
      "missing_requirements": [],
      "operator_review_required": true,
      "records_count": 1,
      "relative_path": "docs/research/database_foundation/pre_ia_acceleration/DATABASE_FOUNDATION_TTL_FRESHNESS_POLICY_CONTRACT_V1.json",
      "source_family": "US Macro"
    },
    {
      "advisory_only": true,
      "allowed_next_step": "operator_must_review_metadata_before_intent_drafting",
      "blocked_reasons": [
        "waiting_for_operator_intent_review"
      ],
      "candidate_id": "ECONOMIC_PRINTS_SCHEMA_CONTRACT_V1",
      "candidate_only": true,
      "content_intent_gate_status": "READY_FOR_OPERATOR_INTENT_REVIEW",
      "contract_name": null,
      "evidence_role": "contract",
      "missing_requirements": [],
      "operator_review_required": true,
      "records_count": 1,
      "relative_path": "docs/research/database_foundation/pre_ia_acceleration/ECONOMIC_PRINTS_SCHEMA_CONTRACT_V1.json",
      "source_family": "US Macro"
    }
  ],
  "content_intent_gate_status": "BLOCKED_OPERATOR_REVIEW_REQUIRED",
  "disallowed_outputs": [
    "raw_record_contents",
    "source_extracted_facts",
    "market_values",
    "narrative_thesis",
    "headline",
    "hook",
    "caption",
    "draft_paragraph",
    "platform_copy",
    "prediction",
    "buy_sell_hold_sizing_signal_language"
  ],
  "hash_algorithm": "sha256",
  "ledger_family": "editorial_brief_review_to_content_intent_gate_precheck_future",
  "lifecycle_overlays": {
    "artifact_or_brief_intake": {
      "operator_action_required": true,
      "state": "PENDING"
    },
    "content_intent": {
      "operator_action_required": true,
      "state": "BLOCKED"
    }
  },
  "next_recommended_task": "TASK_CONTENTOPS_0175BK_CONTENT_INTENT_GATE_PRECHECK_TO_V5_INTENT_QUEUE_BINDING_V0",
  "operator_review_required": true,
  "packet_hash": "3ecf32419922a98e422b1290c44caf7623010fc06f6f20da2afa266ae2af0dfa",
  "safety_flags": {
    "credential_hydrated": false,
    "dispatch_ready": false,
    "env_secret_read": false,
    "live_api_called": false,
    "platform_api_called": false,
    "provider_api_called": false,
    "public_postable": false,
    "scheduler_enabled": false,
    "scraping_performed": false,
    "secret_values_observed": false
  },
  "source_candidate_count": 7,
  "source_editorial_brief_review_packet_hash": "1b5d799c189af120f7f0b0c668cce3f9442fbebc46f3aa6704581f3e865f9e77",
  "source_packet_task_label": "TASK_CONTENTOPS_0175BH_LIFECYCLE_INTAKE_BRIDGE_TO_EDITORIAL_BRIEF_REVIEW_PACKET_V0",
  "task_label": "TASK_CONTENTOPS_0175BJ_EDITORIAL_BRIEF_REVIEW_TO_CONTENT_INTENT_GATE_PRECHECK_V0",
  "truth_protection_flags": {
    "current_truth_promoted": false,
    "dqr_cleared_by_contentops": false,
    "market_data_promoted": false,
    "numeric_truth_promoted": false,
    "readiness_cleared_by_contentops": false
  }
} as const;
