// Capital Chronicle ContentOps V5 Adapter
// Automatically generated by dispatch_outbox_dry_run_v5_adapter_codegen_v6.py. Do not edit manually.

export interface DryRunOutboxEntry {
  platform_id: string;
  source_approval_target_key: string;
  adapter_class: string;
  dry_run_entry_id: string;
  dry_run_payload_text: string;
  dry_run_payload_hash: string;
  source_approval_payload_hash: string;
  destination_binding_status: string;
  credential_handle_status: string;
  request_method_preview: string;
  request_url_preview_status: string;
  request_body_hash_preview: string;
  executable: boolean;
  dispatchable: boolean;
  approved: boolean;
  approval_required: boolean;
  blocked_reason?: string;
  deferred_reason?: string;
  no_public_url_claim: boolean;
  no_metrics_claim: boolean;
  no_network_request_made: boolean;
  no_secret_material_present: boolean;
}

export interface DispatchOutboxDryRunPacket {
  packet_kind: "approval_packet_preview_to_dispatch_outbox_dry_run_v0";
  dispatch_outbox_dry_run_status: "dispatch_outbox_dry_run_created_for_operator_review";
  dry_run_outbox_package_created: boolean;
  dry_run_entries_created: boolean;
  executable_outbox_entry_created: boolean;
  real_outbox_entry_created: boolean;
  dispatch_outbox_ready: boolean;
  dispatch_attempted: boolean;
  dispatch_request_count: number;
  webhook_request_count: number;
  platform_api_request_count: number;
  scheduler_enabled: boolean;
  retry_enabled: boolean;
  kill_switch_required: boolean;
  kill_switch_active: boolean;
  exact_payload_hashes_preserved: boolean;
  actual_operator_approval_recorded: boolean;
  approval_ledger_entry_created: boolean;
  approval_record_created: boolean;
  approval_signature_present: boolean;
  approval_signature_required: boolean;
  platform_payloads_approved: boolean;
  final_article_approved: boolean;
  ready_for_auto_publish: boolean;
  ready_for_dispatch: boolean;
  live_action_allowed: boolean;
  public_url_verification_performed: boolean;
  llm_provider_call_made: boolean;
  provider_call_made: boolean;
  platform_api_used: boolean;
  network_call_made: boolean;
  public_url_fetch_made: boolean;
  env_value_read_made: boolean;
  credential_read_made: boolean;
  browser_session_used: boolean;
  live_publish_performed_by_contentops: boolean;
  enabled_publish_send_dispatch_approve_controls: boolean;
  forbidden_financial_advice_or_signal_wording_present: boolean;
  dispatch_outbox_dry_run_packet_id: string;
  exact_payload_hash: string;
  source_approval_preview_packet_id: string;
  source_approval_preview_exact_payload_hash: string;
  source_final_review_packet_id: string;
  source_final_review_hash: string;
  source_local_draft_preview_packet_id: string;
  source_draft_review_packet_id: string;
  source_local_draft_hash: string;
  dry_run_entries: { [key: string]: DryRunOutboxEntry };
  task_label: string;
}

export const dispatchOutboxDryRunPacket: DispatchOutboxDryRunPacket = {
  "actual_operator_approval_recorded": false,
  "approval_ledger_entry_created": false,
  "approval_record_created": false,
  "approval_signature_present": false,
  "approval_signature_required": true,
  "browser_session_used": false,
  "credential_read_made": false,
  "dispatch_attempted": false,
  "dispatch_outbox_dry_run_packet_id": "outbox_dry_run_7cfc24c5b0c0eded",
  "dispatch_outbox_dry_run_status": "dispatch_outbox_dry_run_created_for_operator_review",
  "dispatch_outbox_ready": false,
  "dispatch_request_count": 0,
  "dry_run_entries": {
    "discord_webhook_dry_run_entry": {
      "adapter_class": "webhook_adapter_preview_only",
      "approval_required": true,
      "approved": false,
      "blocked_reason": "Separate final operator approval signature required.",
      "credential_handle_status": "fixture_only",
      "destination_binding_status": "webhook_mock_bound",
      "dispatchable": false,
      "dry_run_entry_id": "dry_run_discord_28f5ef142e404225",
      "dry_run_payload_hash": "2035a06c36af9c6da38ca4e93d7c31434a281bf20a27aa41f06dcd9adeb5d1fd",
      "dry_run_payload_text": "How do we evaluate the quality of a firm's reported cash flows without reliance on advisory predictions? Let's discuss Days Sales Outstanding and Cash Conversion Cycle metrics.",
      "executable": false,
      "no_metrics_claim": true,
      "no_network_request_made": true,
      "no_public_url_claim": true,
      "no_secret_material_present": true,
      "platform_id": "discord",
      "request_body_hash_preview": "a77b2098f30aae877f68feccc263e8b2648647b094299799c3c1b8a6967bb640",
      "request_method_preview": "POST_JSON",
      "request_url_preview_status": "webhook_mock_preview_only",
      "source_approval_payload_hash": "2035a06c36af9c6da38ca4e93d7c31434a281bf20a27aa41f06dcd9adeb5d1fd",
      "source_approval_target_key": "discord_approval_preview"
    },
    "facebook_manual_dry_run_entry": {
      "adapter_class": "manual_fallback_adapter",
      "approval_required": true,
      "approved": false,
      "blocked_reason": "Separate final operator approval signature required.",
      "credential_handle_status": "fixture_only",
      "destination_binding_status": "preview_bound_manual",
      "dispatchable": false,
      "dry_run_entry_id": "dry_run_facebook_28f5ef142e404225",
      "dry_run_payload_hash": "05af2ed21a39ec2cee73c609af3c06392876f4ec5581f4369c07216ca13fddc3",
      "dry_run_payload_text": "Earnings Quality analysis: comparing net income to operating cash flows to identify qualitative discrepancies. Standard financial literacy.",
      "executable": false,
      "no_metrics_claim": true,
      "no_network_request_made": true,
      "no_public_url_claim": true,
      "no_secret_material_present": true,
      "platform_id": "facebook",
      "request_body_hash_preview": "d88ddef8a0085d99fc5bf51b91e99fd1ac889646237fde0fda300fb53d2a9cc1",
      "request_method_preview": "POST_MANUAL",
      "request_url_preview_status": "manual_copy_block_only",
      "source_approval_payload_hash": "05af2ed21a39ec2cee73c609af3c06392876f4ec5581f4369c07216ca13fddc3",
      "source_approval_target_key": "facebook_approval_preview"
    },
    "instagram_deferred_dry_run_entry": {
      "adapter_class": "deferred_adapter",
      "approval_required": true,
      "approved": false,
      "credential_handle_status": "fixture_only",
      "deferred_reason": "Deferred until subsequent explicit publication task.",
      "destination_binding_status": "deferred_future",
      "dispatchable": false,
      "dry_run_entry_id": "dry_run_instagram_28f5ef142e404225",
      "dry_run_payload_hash": "3970b2777898f615fdebcb456b5be50f64eb31a446ee63bb826bca8ef0404269",
      "dry_run_payload_text": "Profits vs Cash: A look at cash conversion cycle mechanics. Details and formulas inside. #finance #education #accounting",
      "executable": false,
      "no_metrics_claim": true,
      "no_network_request_made": true,
      "no_public_url_claim": true,
      "no_secret_material_present": true,
      "platform_id": "instagram",
      "request_body_hash_preview": "c48e0804c113983c7da90ee1135908335de6b0846c98690cce2fffebc1990cf9",
      "request_method_preview": "DEFERRED",
      "request_url_preview_status": "deferred_future_task",
      "source_approval_payload_hash": "3970b2777898f615fdebcb456b5be50f64eb31a446ee63bb826bca8ef0404269",
      "source_approval_target_key": "instagram_approval_preview"
    },
    "linkedin_deferred_dry_run_entry": {
      "adapter_class": "deferred_adapter",
      "approval_required": true,
      "approved": false,
      "credential_handle_status": "fixture_only",
      "deferred_reason": "Deferred until subsequent explicit publication task.",
      "destination_binding_status": "deferred_future",
      "dispatchable": false,
      "dry_run_entry_id": "dry_run_linkedin_28f5ef142e404225",
      "dry_run_payload_hash": "e62b097f655d61575b1e1618cdd96c764de57c99cc78cb8f38792bef47144b42",
      "dry_run_payload_text": "A qualitative overview of Earnings Quality, cash conversion speed, and dividend safety cushions based on historical SEC filing structures. Strictly educational.",
      "executable": false,
      "no_metrics_claim": true,
      "no_network_request_made": true,
      "no_public_url_claim": true,
      "no_secret_material_present": true,
      "platform_id": "linkedin",
      "request_body_hash_preview": "ad6c427654aca0c103ef495aeae619f911f5d1cc89933650cff2b0fe45703021",
      "request_method_preview": "DEFERRED",
      "request_url_preview_status": "deferred_future_task",
      "source_approval_payload_hash": "e62b097f655d61575b1e1618cdd96c764de57c99cc78cb8f38792bef47144b42",
      "source_approval_target_key": "linkedin_approval_preview"
    },
    "substack_manual_dry_run_entry": {
      "adapter_class": "manual_fallback_adapter",
      "approval_required": true,
      "approved": false,
      "blocked_reason": "Separate final operator approval signature required.",
      "credential_handle_status": "fixture_only",
      "destination_binding_status": "preview_bound_manual",
      "dispatchable": false,
      "dry_run_entry_id": "dry_run_substack_28f5ef142e404225",
      "dry_run_payload_hash": "e3ea8a276004201a61f8b794cd8b75c980d263bed6defcef517e15990d1844bc",
      "dry_run_payload_text": "Financial reporting lists profits, but cash quality shows underlying strength. This educational explainer focuses on understanding standard accounting principles.",
      "executable": false,
      "no_metrics_claim": true,
      "no_network_request_made": true,
      "no_public_url_claim": true,
      "no_secret_material_present": true,
      "platform_id": "substack",
      "request_body_hash_preview": "06d4126cc3bb0e60ea895beae4c653b7a217ec92686225523ceadbec297f42bb",
      "request_method_preview": "POST_MANUAL",
      "request_url_preview_status": "manual_copy_block_only",
      "source_approval_payload_hash": "e3ea8a276004201a61f8b794cd8b75c980d263bed6defcef517e15990d1844bc",
      "source_approval_target_key": "substack_approval_preview"
    },
    "telegram_operator_dry_run_entry": {
      "adapter_class": "webhook_adapter_preview_only",
      "approval_required": true,
      "approved": false,
      "blocked_reason": "Separate final operator approval signature required.",
      "credential_handle_status": "fixture_only",
      "destination_binding_status": "webhook_mock_bound",
      "dispatchable": false,
      "dry_run_entry_id": "dry_run_telegram_28f5ef142e404225",
      "dry_run_payload_hash": "779750a3840ddc365f479c63773b6e7081000ff6da480ede4dd5af5ceb8d1636",
      "dry_run_payload_text": "Local canonical draft preview is ready for operator final review. No LLM or provider API was called.",
      "executable": false,
      "no_metrics_claim": true,
      "no_network_request_made": true,
      "no_public_url_claim": true,
      "no_secret_material_present": true,
      "platform_id": "telegram",
      "request_body_hash_preview": "c9f8fc7d48d2982a88f56c5702ab7bebe12c280190412272f91d90f39abc7dbf",
      "request_method_preview": "POST_JSON",
      "request_url_preview_status": "webhook_mock_preview_only",
      "source_approval_payload_hash": "779750a3840ddc365f479c63773b6e7081000ff6da480ede4dd5af5ceb8d1636",
      "source_approval_target_key": "telegram_approval_preview"
    },
    "threads_manual_dry_run_entry": {
      "adapter_class": "manual_fallback_adapter",
      "approval_required": true,
      "approved": false,
      "blocked_reason": "Separate final operator approval signature required.",
      "credential_handle_status": "fixture_only",
      "destination_binding_status": "preview_bound_manual",
      "dispatchable": false,
      "dry_run_entry_id": "dry_run_threads_28f5ef142e404225",
      "dry_run_payload_hash": "0be3e24ba7b6d44fb86fa36b0a355f165e7a42907be59e87e8cf1fa8f8384569",
      "dry_run_payload_text": "Understanding standard accounting metrics like Days Inventory Outstanding (DIO) without guaranteed market predictions. What indicators do you prioritize?",
      "executable": false,
      "no_metrics_claim": true,
      "no_network_request_made": true,
      "no_public_url_claim": true,
      "no_secret_material_present": true,
      "platform_id": "threads",
      "request_body_hash_preview": "3fb7f1f5d3a1d66b4d567868b1a2e937a29f83b50698b848f770b9ed47d04255",
      "request_method_preview": "POST_MANUAL",
      "request_url_preview_status": "manual_copy_block_only",
      "source_approval_payload_hash": "0be3e24ba7b6d44fb86fa36b0a355f165e7a42907be59e87e8cf1fa8f8384569",
      "source_approval_target_key": "threads_approval_preview"
    },
    "tiktok_deferred_dry_run_entry": {
      "adapter_class": "deferred_adapter",
      "approval_required": true,
      "approved": false,
      "credential_handle_status": "fixture_only",
      "deferred_reason": "Deferred until subsequent explicit publication task.",
      "destination_binding_status": "deferred_future",
      "dispatchable": false,
      "dry_run_entry_id": "dry_run_tiktok_28f5ef142e404225",
      "dry_run_payload_hash": "b07f54e673565ed663e2155a4a830d25b677e8f0348df7be865d20fa7ef2969e",
      "dry_run_payload_text": "Why cash conversion matter. Educational outline on DSO and DPO formulas.",
      "executable": false,
      "no_metrics_claim": true,
      "no_network_request_made": true,
      "no_public_url_claim": true,
      "no_secret_material_present": true,
      "platform_id": "tiktok",
      "request_body_hash_preview": "097ecec8976525c61096d8b27b11708b11da0d90a5e23c12b4118f5269414b86",
      "request_method_preview": "DEFERRED",
      "request_url_preview_status": "deferred_future_task",
      "source_approval_payload_hash": "b07f54e673565ed663e2155a4a830d25b677e8f0348df7be865d20fa7ef2969e",
      "source_approval_target_key": "tiktok_approval_preview"
    },
    "x_manual_dry_run_entry": {
      "adapter_class": "manual_fallback_adapter",
      "approval_required": true,
      "approved": false,
      "blocked_reason": "Separate final operator approval signature required.",
      "credential_handle_status": "fixture_only",
      "destination_binding_status": "preview_bound_manual",
      "dispatchable": false,
      "dry_run_entry_id": "dry_run_x_28f5ef142e404225",
      "dry_run_payload_hash": "b9c61b8a0139570226f1bc69c2cf5128dfbd1cfb17d3fe8c590ebd37fa9e773d",
      "dry_run_payload_text": "Profits are fine, but cash is king. Let's learn standard cash conversion cycle components qualitatively: DIO + DSO - DPO. Educational only, no financial advice.",
      "executable": false,
      "no_metrics_claim": true,
      "no_network_request_made": true,
      "no_public_url_claim": true,
      "no_secret_material_present": true,
      "platform_id": "x",
      "request_body_hash_preview": "d1cb493aa5aa6ce3b028719024574738ec10b404b564e72eedc5bb0a30282251",
      "request_method_preview": "POST_MANUAL",
      "request_url_preview_status": "manual_copy_block_only",
      "source_approval_payload_hash": "b9c61b8a0139570226f1bc69c2cf5128dfbd1cfb17d3fe8c590ebd37fa9e773d",
      "source_approval_target_key": "x_approval_preview"
    },
    "youtube_deferred_dry_run_entry": {
      "adapter_class": "deferred_adapter",
      "approval_required": true,
      "approved": false,
      "credential_handle_status": "fixture_only",
      "deferred_reason": "Deferred until subsequent explicit publication task.",
      "destination_binding_status": "deferred_future",
      "dispatchable": false,
      "dry_run_entry_id": "dry_run_youtube_28f5ef142e404225",
      "dry_run_payload_hash": "a26ed74a8bd03727d4b43b2eaf52f6335ac057b9cc9e7f354d2c36160ea12074",
      "dry_run_payload_text": "Educational video script outline: How to qualitatively verify earnings quality and cash cycles from historical SEC documents.",
      "executable": false,
      "no_metrics_claim": true,
      "no_network_request_made": true,
      "no_public_url_claim": true,
      "no_secret_material_present": true,
      "platform_id": "youtube",
      "request_body_hash_preview": "f360cd63047e8dcccf738b2ca1719e62d026d9ae6b78ee3c86bdc6327881b944",
      "request_method_preview": "DEFERRED",
      "request_url_preview_status": "deferred_future_task",
      "source_approval_payload_hash": "a26ed74a8bd03727d4b43b2eaf52f6335ac057b9cc9e7f354d2c36160ea12074",
      "source_approval_target_key": "youtube_approval_preview"
    }
  },
  "dry_run_entries_created": true,
  "dry_run_outbox_package_created": true,
  "enabled_publish_send_dispatch_approve_controls": false,
  "env_value_read_made": false,
  "exact_payload_hash": "7cfc24c5b0c0ededb530c3d5ede21490ad49b0d46969e7d7ed3d8c7758769439",
  "exact_payload_hashes_preserved": true,
  "executable_outbox_entry_created": false,
  "final_article_approved": false,
  "forbidden_financial_advice_or_signal_wording_present": false,
  "kill_switch_active": true,
  "kill_switch_required": true,
  "live_action_allowed": false,
  "live_publish_performed_by_contentops": false,
  "llm_provider_call_made": false,
  "network_call_made": false,
  "packet_kind": "approval_packet_preview_to_dispatch_outbox_dry_run_v0",
  "platform_api_request_count": 0,
  "platform_api_used": false,
  "platform_payloads_approved": false,
  "provider_call_made": false,
  "public_url_fetch_made": false,
  "public_url_verification_performed": false,
  "ready_for_auto_publish": false,
  "ready_for_dispatch": false,
  "real_outbox_entry_created": false,
  "retry_enabled": false,
  "scheduler_enabled": false,
  "source_approval_preview_exact_payload_hash": "b02ec50b38399194d087d12c1e168ceef64fc527ddab1885517ca542f7a72678",
  "source_approval_preview_packet_id": "approval_preview_28f5ef142e404225",
  "source_draft_review_packet_id": "draft_review_1f81b17970b6c151",
  "source_final_review_hash": "11fc52e6e452c4d3fedd306ffbf796fae459e061c784eed86cc1e8f65b9d38f2",
  "source_final_review_packet_id": "final_review_preview_11fc52e6e452c4d3",
  "source_local_draft_hash": "1f81b17970b6c151d301c63af23e7adcc814e6ddf65bcd4e9a6b2c5def0c8b97",
  "source_local_draft_preview_packet_id": "local_draft_preview_1f81b17970b6c151",
  "task_label": "TASK_CONTENTOPS_V6_APPROVAL_PACKET_PREVIEW_TO_DISPATCH_OUTBOX_DRY_RUN_HEAVY_BATCH_V0",
  "webhook_request_count": 0
};
