"""Deterministic static JS bridge generator for the operator evidence surface.

Local-only, read-only, fail-closed. Reads the ALREADY-ACCEPTED 0174BU PREP02 PASS
surface fixture and emits a single canonical JavaScript artifact that defines the
read-only global ``window.CC_OPERATOR_EVIDENCE_SURFACE``. The generated artifact is
evidence-only and grants nothing: it performs no network, credential, env, platform,
provider, scheduler, posting, scraping, or browser-storage behavior.

Usage:
    python tools/build_operator_evidence_surface_js.py --check   # fail if stale
    python tools/build_operator_evidence_surface_js.py --write   # (re)write artifact

This tool imports only json/sys/pathlib. It reads no secrets and writes only the one
artifact below. It must not be wired into the V4 runtime in this task.
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE_FIXTURE = (
    ROOT / "fixtures" / "scd_operator_evidence_surface"
    / "evidence_surface_valid_pass_manual_only.json"
)
ARTIFACT = (
    ROOT / "ui" / "institutional_operator_cockpit_v4" / "operator_evidence_surface.js"
)
GLOBAL_NAME = "window.CC_OPERATOR_EVIDENCE_SURFACE"

# Literal substrings that must never appear in the generated artifact. Evidence-only
# JS carries no network/storage/credential behavior, so any hit is a hard failure.
FORBIDDEN_TOKENS = (
    "http://", "https://", "fetch(", "XMLHttpRequest", "WebSocket", "EventSource",
    "sendBeacon", "localStorage", "sessionStorage", "process.env", ".env",
    "API key", "bearer token", "platform endpoint", "market data", "credential string",
)

HEADER = (
    "// AUTO-GENERATED by tools/build_operator_evidence_surface_js.py -- do not edit by hand.\n"
    "// Source fixture: fixtures/scd_operator_evidence_surface/"
    "evidence_surface_valid_pass_manual_only.json\n"
    "// Local-only, evidence-only, no-grant projection. Defines a frozen read-only global.\n"
    "// Regenerate with: python tools/build_operator_evidence_surface_js.py --write\n"
)


def _load_surface():
    with open(SOURCE_FIXTURE, "r", encoding="utf-8") as handle:
        return json.load(handle)


def render_js(surface):
    """Render the canonical, deterministic JS artifact text for a surface packet."""
    body = json.dumps(surface, indent=2, sort_keys=True)
    return (
        HEADER
        + GLOBAL_NAME + " = " + body + ";\n"
        + "Object.freeze(" + GLOBAL_NAME + ");\n"
    )


def _safety_scan(text):
    """Return the list of forbidden literal tokens present in the artifact text."""
    return [token for token in FORBIDDEN_TOKENS if token in text]


def _build_expected():
    surface = _load_surface()
    text = render_js(surface)
    hits = _safety_scan(text)
    if hits:
        raise SystemExit("SAFETY_SCAN_FAILED tokens=" + ",".join(hits))
    if not text.startswith(HEADER + GLOBAL_NAME + " = {"):
        raise SystemExit("PREFIX_INVALID generated artifact missing required prefix")
    return text


def cmd_write():
    text = _build_expected()
    ARTIFACT.parent.mkdir(parents=True, exist_ok=True)
    ARTIFACT.write_text(text, encoding="utf-8", newline="\n")
    print("WROTE " + str(ARTIFACT.relative_to(ROOT)))
    print("BYTES " + str(len(text.encode("utf-8"))))
    print("SAFETY_SCAN_CLEAN")
    return 0


def cmd_check():
    expected = _build_expected()
    if not ARTIFACT.is_file():
        print("STALE artifact missing: " + str(ARTIFACT.relative_to(ROOT)))
        return 1
    actual = ARTIFACT.read_text(encoding="utf-8")
    if actual != expected:
        print("STALE artifact differs from regenerated output; run --write")
        return 1
    print("CHECK_OK artifact is byte-identical to regenerated output")
    print("SAFETY_SCAN_CLEAN")
    return 0


def main(argv):
    if "--write" in argv:
        return cmd_write()
    if "--check" in argv:
        return cmd_check()
    print(__doc__.strip().splitlines()[0])
    print("usage: build_operator_evidence_surface_js.py [--check|--write]")
    return 2


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
