"""Deterministic static TypeScript exporter for the Operator Input Capture Precheck Packet.

Part of TASK_CONTENTOPS_0175BO_OPERATOR_INPUT_CAPTURE_PRECHECK_TO_V5_READONLY_INPUT_PANEL_BINDING_V0.
Exports the 0175BN Operator Input Capture Precheck packet into V5 TypeScript format.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

ARTIFACT = (
    ROOT / "ui" / "contentops_v5" / "src" / "data" / "operatorInputCapturePrecheckPacket.ts"
)

HEADER = (
    "// AUTO-GENERATED by tools/export_v5_operator_input_capture_precheck_packet.py -- do not edit by hand.\n"
    "// Local-only, readonly, no-capture projection. Defines a frozen precheck packet.\n"
)

FORBIDDEN_TOKENS = (
    "process.env", ".env", "API key", "bearer token", "credential string",
    "buy", "sell", "hold", "guaranteed", "price target", "order execution",
    "<input", "<textarea", "onChange=", "onSubmit=", "capture now", "submit"
)

ALLOWED_DISALLOWED_OUTPUT_TOKENS = (
    "buy_sell_hold_sizing_signal_language",
    "headline",
    "hook",
    "caption",
    "draft_paragraph",
    "platform_copy",
    "prediction",
)


def load_packet() -> dict[str, Any]:
    """Loads or regenerates the 0175BN Operator Input Capture Precheck packet."""
    json_path = ROOT / "docs" / "automation" / "0175BN" / "review_only_intent_to_operator_input_capture_precheck_packet.json"
    if json_path.is_file():
        with open(json_path, "r", encoding="utf-8") as f:
            return json.load(f)

    intent_path = ROOT / "docs" / "automation" / "0175BL" / "content_intent_gate_to_review_only_intent_packet.json"
    with open(intent_path, "r", encoding="utf-8") as f:
        intent_packet = json.load(f)

    from live_contentops.review_only_intent_to_operator_input_capture_precheck import create_operator_input_capture_precheck
    return create_operator_input_capture_precheck(intent_packet)


def render_ts(packet: dict[str, Any]) -> str:
    """Render deterministic TS artifact text for the readonly precheck packet."""
    body = json.dumps(packet, indent=2, sort_keys=True, ensure_ascii=False)
    return HEADER + "export const operatorInputCapturePrecheckPacket = " + body + " as const;\n"


def _safety_scan(text: str) -> list[str]:
    clean_text = text
    for token in ALLOWED_DISALLOWED_OUTPUT_TOKENS:
        clean_text = clean_text.replace(f'"{token}"', '"_redacted_"')
    clean_text = clean_text.replace("buy_sell_hold", "_redacted_")
    return [token for token in FORBIDDEN_TOKENS if token in clean_text]


def _build_expected() -> str:
    packet = load_packet()
    text = render_ts(packet)
    hits = _safety_scan(text)
    if hits:
        raise SystemExit("SAFETY_SCAN_FAILED tokens=" + ",".join(hits))
    return text


def cmd_write() -> int:
    text = _build_expected()
    ARTIFACT.parent.mkdir(parents=True, exist_ok=True)
    ARTIFACT.write_text(text, encoding="utf-8", newline="\n")
    print("WROTE " + str(ARTIFACT.relative_to(ROOT)))
    print("BYTES " + str(len(text.encode("utf-8"))))
    print("SAFETY_SCAN_CLEAN")
    return 0


def cmd_check() -> int:
    expected = _build_expected()
    if not ARTIFACT.is_file():
        print("STALE artifact missing: " + str(ARTIFACT.relative_to(ROOT)))
        return 1
    actual = ARTIFACT.read_text(encoding="utf-8")
    if actual != expected:
        print("STALE artifact differs from regenerated output; run export script")
        return 1
    print("CHECK_OK artifact is byte-identical to regenerated output")
    print("SAFETY_SCAN_CLEAN")
    return 0


def main(argv: list[str]) -> int:
    if "--check" in argv:
        return cmd_check()
    return cmd_write()


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
