"""Deterministic static TypeScript exporter for the Content Lifecycle Read Model.

Part of TASK_CONTENTOPS_0175BF_OPERATOR_REVIEW_READ_MODEL_TO_V5_QUEUE_BINDING_V0.
Exports the 0175BE content lifecycle engine packet into V5 TypeScript format.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from live_contentops.content_lifecycle_engine import build_contract_packet

ARTIFACT = (
    ROOT / "ui" / "contentops_v5" / "src" / "data" / "contentLifecycleReadModelPacket.ts"
)

HEADER = (
    "// AUTO-GENERATED by tools/export_v5_lifecycle_read_model.py -- do not edit by hand.\n"
    "// Local-only, evidence-only, no-grant projection. Defines a frozen read-only packet.\n"
)

# Literal substrings that must never appear in the generated artifact.
FORBIDDEN_TOKENS = (
    "process.env", ".env", "API key", "bearer token", "credential string",
)


def render_ts(packet: dict[str, Any]) -> str:
    """Render the canonical, deterministic TS artifact text for a lifecycle packet."""
    body = json.dumps(packet, indent=2, sort_keys=True, ensure_ascii=False)
    return (
        HEADER
        + "export const contentLifecycleReadModelPacket = " + body + " as const;\n"
    )


def _safety_scan(text: str) -> list[str]:
    return [token for token in FORBIDDEN_TOKENS if token in text]


def _build_expected() -> str:
    packet = build_contract_packet()
    text = render_ts(packet)
    hits = _safety_scan(text)
    if hits:
        raise SystemExit("SAFETY_SCAN_FAILED tokens=" + ",".join(hits))
    return text


def cmd_write() -> int:
    text = _build_expected()
    ARTIFACT.parent.mkdir(parents=True, exist_ok=True)
    ARTIFACT.write_text(text, encoding="utf-8", newline="\n")
    print("WROTE " + str(ARTIFACT.relative_to(ROOT)))
    print("BYTES " + str(len(text.encode("utf-8"))))
    print("SAFETY_SCAN_CLEAN")
    return 0


def cmd_check() -> int:
    expected = _build_expected()
    if not ARTIFACT.is_file():
        print("STALE artifact missing: " + str(ARTIFACT.relative_to(ROOT)))
        return 1
    actual = ARTIFACT.read_text(encoding="utf-8")
    if actual != expected:
        print("STALE artifact differs from regenerated output; run export script")
        return 1
    print("CHECK_OK artifact is byte-identical to regenerated output")
    print("SAFETY_SCAN_CLEAN")
    return 0


def main(argv: list[str]) -> int:
    if "--check" in argv:
        return cmd_check()
    # Default behavior is to write the file
    return cmd_write()


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
